# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/project9/project1.srcs/constrs_1/new/project1.xdc

# Block Designs: C:/project9/project1.srcs/sources_1/bd/project1/project1.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==project1 || ORIG_REF_NAME==project1} -quiet] -quiet

# IP: C:/project9/project1.srcs/sources_1/bd/project1/ip/project1_processing_system7_0_0/project1_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==project1_processing_system7_0_0 || ORIG_REF_NAME==project1_processing_system7_0_0} -quiet] -quiet

# IP: C:/project9/project1.srcs/sources_1/bd/project1/ip/project1_dvi2rgb_0_0/project1_dvi2rgb_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==project1_dvi2rgb_0_0 || ORIG_REF_NAME==project1_dvi2rgb_0_0} -quiet] -quiet

# IP: C:/project9/project1.srcs/sources_1/bd/project1/ip/project1_rgb2dvi_0_0/project1_rgb2dvi_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==project1_rgb2dvi_0_0 || ORIG_REF_NAME==project1_rgb2dvi_0_0} -quiet] -quiet

# IP: C:/project9/project1.srcs/sources_1/bd/project1/ip/project1_v_axi4s_vid_out_0_0/project1_v_axi4s_vid_out_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==project1_v_axi4s_vid_out_0_0 || ORIG_REF_NAME==project1_v_axi4s_vid_out_0_0} -quiet] -quiet

# IP: C:/project9/project1.srcs/sources_1/bd/project1/ip/project1_v_vid_in_axi4s_0_0/project1_v_vid_in_axi4s_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==project1_v_vid_in_axi4s_0_0 || ORIG_REF_NAME==project1_v_vid_in_axi4s_0_0} -quiet] -quiet

# IP: C:/project9/project1.srcs/sources_1/bd/project1/ip/project1_axi_vdma_0_0/project1_axi_vdma_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==project1_axi_vdma_0_0 || ORIG_REF_NAME==project1_axi_vdma_0_0} -quiet] -quiet

# IP: C:/project9/project1.srcs/sources_1/bd/project1/ip/project1_v_tc_0_0/project1_v_tc_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==project1_v_tc_0_0 || ORIG_REF_NAME==project1_v_tc_0_0} -quiet] -quiet

# IP: C:/project9/project1.srcs/sources_1/bd/project1/ip/project1_v_tc_0_1/project1_v_tc_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==project1_v_tc_0_1 || ORIG_REF_NAME==project1_v_tc_0_1} -quiet] -quiet

# IP: C:/project9/project1.srcs/sources_1/bd/project1/ip/project1_axi_interconnect_0_imp_xbar_0/project1_axi_interconnect_0_imp_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==project1_axi_interconnect_0_imp_xbar_0 || ORIG_REF_NAME==project1_axi_interconnect_0_imp_xbar_0} -quiet] -quiet

# IP: C:/project9/project1.srcs/sources_1/bd/project1/ip/project1_axi_interconnect_0_0/project1_axi_interconnect_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==project1_axi_interconnect_0_0 || ORIG_REF_NAME==project1_axi_interconnect_0_0} -quiet] -quiet

# IP: C:/project9/project1.srcs/sources_1/bd/project1/ip/project1_rst_ps7_0_100M_0/project1_rst_ps7_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==project1_rst_ps7_0_100M_0 || ORIG_REF_NAME==project1_rst_ps7_0_100M_0} -quiet] -quiet

# IP: C:/project9/project1.srcs/sources_1/bd/project1/ip/project1_proc_sys_reset_0_0/project1_proc_sys_reset_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==project1_proc_sys_reset_0_0 || ORIG_REF_NAME==project1_proc_sys_reset_0_0} -quiet] -quiet

# IP: C:/project9/project1.srcs/sources_1/bd/project1/ip/project1_proc_sys_reset_0_1/project1_proc_sys_reset_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==project1_proc_sys_reset_0_1 || ORIG_REF_NAME==project1_proc_sys_reset_0_1} -quiet] -quiet

# IP: C:/project9/project1.srcs/sources_1/bd/project1/ip/project1_axi_dynclk_0_0/project1_axi_dynclk_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==project1_axi_dynclk_0_0 || ORIG_REF_NAME==project1_axi_dynclk_0_0} -quiet] -quiet

# IP: C:/project9/project1.srcs/sources_1/bd/project1/ip/project1_xlconstant_0_0/project1_xlconstant_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==project1_xlconstant_0_0 || ORIG_REF_NAME==project1_xlconstant_0_0} -quiet] -quiet

# IP: C:/project9/project1.srcs/sources_1/bd/project1/ip/project1_xlconstant_1_0/project1_xlconstant_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==project1_xlconstant_1_0 || ORIG_REF_NAME==project1_xlconstant_1_0} -quiet] -quiet

# IP: C:/project9/project1.srcs/sources_1/bd/project1/ip/project1_util_ds_buf_0_0/project1_util_ds_buf_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==project1_util_ds_buf_0_0 || ORIG_REF_NAME==project1_util_ds_buf_0_0} -quiet] -quiet

# IP: C:/project9/project1.srcs/sources_1/bd/project1/ip/project1_smartconnect_0_0/project1_smartconnect_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==project1_smartconnect_0_0 || ORIG_REF_NAME==project1_smartconnect_0_0} -quiet] -quiet

# IP: c:/project9/project1.srcs/sources_1/bd/project1/ip/project1_axi_interconnect_0_imp_auto_pc_0/project1_axi_interconnect_0_imp_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==project1_axi_interconnect_0_imp_auto_pc_0 || ORIG_REF_NAME==project1_axi_interconnect_0_imp_auto_pc_0} -quiet] -quiet

# IP: c:/project9/project1.srcs/sources_1/bd/project1/ip/project1_axi_interconnect_0_imp_auto_cc_0/project1_axi_interconnect_0_imp_auto_cc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==project1_axi_interconnect_0_imp_auto_cc_0 || ORIG_REF_NAME==project1_axi_interconnect_0_imp_auto_cc_0} -quiet] -quiet

# IP: c:/project9/project1.srcs/sources_1/bd/project1/ip/project1_quad_frame_remapper_0_0/project1_quad_frame_remapper_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==project1_quad_frame_remapper_0_0 || ORIG_REF_NAME==project1_quad_frame_remapper_0_0} -quiet] -quiet

# XDC: c:/project9/project1.gen/sources_1/bd/project1/project1_ooc.xdc
