# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "C:/quad_frame_remapper/quad_frame_remapper.runs/synth_1/project1_wrapper.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

OPTRACE "synth_1" START { ROLLUP_AUTO }
set_param general.usePosixSpawnForFork 1
set_param bd.open.in_stealth_mode 1
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7z020clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/quad_frame_remapper/quad_frame_remapper.cache/wt [current_project]
set_property parent.project_path C:/quad_frame_remapper/quad_frame_remapper.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part www.digilentinc.com:pynq-z1:part0:1.0 [current_project]
set_property ip_repo_paths {
  c:/quad_frame_remapper/ip_repo
  c:/quad_frame_remapper/vitis_hls_workspace/hls_component/hls_component/hls/impl/ip
} [current_project]
update_ip_catalog
set_property ip_output_repo c:/quad_frame_remapper/quad_frame_remapper.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_verilog -library xil_defaultlib c:/project9/project1.gen/sources_1/bd/project1/hdl/project1_wrapper.v
add_files C:/project9/project1.srcs/sources_1/bd/project1/project1.bd
set_property used_in_implementation false [get_files -all c:/project9/project1.gen/sources_1/bd/project1/ip/project1_processing_system7_0_0/project1_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/project9/project1.gen/sources_1/bd/project1/ip/project1_dvi2rgb_0_0/src/ila_refclk/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all c:/project9/project1.gen/sources_1/bd/project1/ip/project1_dvi2rgb_0_0/src/ila_refclk/ila_refclk_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/project9/project1.gen/sources_1/bd/project1/ip/project1_dvi2rgb_0_0/src/ila_pixclk/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all c:/project9/project1.gen/sources_1/bd/project1/ip/project1_dvi2rgb_0_0/src/ila_pixclk/ila_pixclk_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/project9/project1.gen/sources_1/bd/project1/ip/project1_dvi2rgb_0_0/src/ila_timing_workaround.xdc]
set_property used_in_implementation false [get_files -all c:/project9/project1.gen/sources_1/bd/project1/ip/project1_dvi2rgb_0_0/src/dvi2rgb.xdc]
set_property used_in_implementation false [get_files -all c:/project9/project1.gen/sources_1/bd/project1/ip/project1_dvi2rgb_0_0/src/dvi2rgb_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/project9/project1.gen/sources_1/bd/project1/ip/project1_rgb2dvi_0_0/src/rgb2dvi.xdc]
set_property used_in_implementation false [get_files -all c:/project9/project1.gen/sources_1/bd/project1/ip/project1_rgb2dvi_0_0/src/rgb2dvi_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/project9/project1.gen/sources_1/bd/project1/ip/project1_rgb2dvi_0_0/src/rgb2dvi_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/project9/project1.gen/sources_1/bd/project1/ip/project1_v_axi4s_vid_out_0_0/project1_v_axi4s_vid_out_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/project9/project1.gen/sources_1/bd/project1/ip/project1_v_axi4s_vid_out_0_0/project1_v_axi4s_vid_out_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/project9/project1.gen/sources_1/bd/project1/ip/project1_v_vid_in_axi4s_0_0/project1_v_vid_in_axi4s_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/project9/project1.gen/sources_1/bd/project1/ip/project1_v_vid_in_axi4s_0_0/project1_v_vid_in_axi4s_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/project9/project1.gen/sources_1/bd/project1/ip/project1_axi_vdma_0_0/project1_axi_vdma_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/project9/project1.gen/sources_1/bd/project1/ip/project1_axi_vdma_0_0/project1_axi_vdma_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/project9/project1.gen/sources_1/bd/project1/ip/project1_axi_vdma_0_0/project1_axi_vdma_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/project9/project1.gen/sources_1/bd/project1/ip/project1_v_tc_0_0/project1_v_tc_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/project9/project1.gen/sources_1/bd/project1/ip/project1_v_tc_0_0/project1_v_tc_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/project9/project1.gen/sources_1/bd/project1/ip/project1_v_tc_0_1/project1_v_tc_0_1_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/project9/project1.gen/sources_1/bd/project1/ip/project1_v_tc_0_1/project1_v_tc_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/project9/project1.gen/sources_1/bd/project1/ip/project1_axi_interconnect_0_imp_xbar_0/project1_axi_interconnect_0_imp_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/project9/project1.gen/sources_1/bd/project1/ip/project1_rst_ps7_0_100M_0/project1_rst_ps7_0_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/project9/project1.gen/sources_1/bd/project1/ip/project1_rst_ps7_0_100M_0/project1_rst_ps7_0_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/project9/project1.gen/sources_1/bd/project1/ip/project1_proc_sys_reset_0_0/project1_proc_sys_reset_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/project9/project1.gen/sources_1/bd/project1/ip/project1_proc_sys_reset_0_0/project1_proc_sys_reset_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/project9/project1.gen/sources_1/bd/project1/ip/project1_proc_sys_reset_0_1/project1_proc_sys_reset_0_1_board.xdc]
set_property used_in_implementation false [get_files -all c:/project9/project1.gen/sources_1/bd/project1/ip/project1_proc_sys_reset_0_1/project1_proc_sys_reset_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/project9/project1.gen/sources_1/bd/project1/ip/project1_axi_dynclk_0_0/src/axi_dynclk.xdc]
set_property used_in_implementation false [get_files -all c:/project9/project1.gen/sources_1/bd/project1/ip/project1_util_ds_buf_0_0/project1_util_ds_buf_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/project9/project1.gen/sources_1/bd/project1/ip/project1_util_ds_buf_0_0/project1_util_ds_buf_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/project9/project1.gen/sources_1/bd/project1/ip/project1_smartconnect_0_0/bd_0/ip/ip_1/bd_173e_psr_aclk_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/project9/project1.gen/sources_1/bd/project1/ip/project1_smartconnect_0_0/bd_0/ip/ip_2/bd_173e_arsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/project9/project1.gen/sources_1/bd/project1/ip/project1_smartconnect_0_0/bd_0/ip/ip_3/bd_173e_rsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/project9/project1.gen/sources_1/bd/project1/ip/project1_smartconnect_0_0/bd_0/ip/ip_4/bd_173e_awsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/project9/project1.gen/sources_1/bd/project1/ip/project1_smartconnect_0_0/bd_0/ip/ip_5/bd_173e_wsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/project9/project1.gen/sources_1/bd/project1/ip/project1_smartconnect_0_0/bd_0/ip/ip_6/bd_173e_bsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/project9/project1.gen/sources_1/bd/project1/ip/project1_smartconnect_0_0/bd_0/ip/ip_10/bd_173e_s00a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/project9/project1.gen/sources_1/bd/project1/ip/project1_smartconnect_0_0/bd_0/ip/ip_11/bd_173e_sarn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/project9/project1.gen/sources_1/bd/project1/ip/project1_smartconnect_0_0/bd_0/ip/ip_12/bd_173e_srn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/project9/project1.gen/sources_1/bd/project1/ip/project1_smartconnect_0_0/bd_0/ip/ip_16/bd_173e_s01a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/project9/project1.gen/sources_1/bd/project1/ip/project1_smartconnect_0_0/bd_0/ip/ip_17/bd_173e_sawn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/project9/project1.gen/sources_1/bd/project1/ip/project1_smartconnect_0_0/bd_0/ip/ip_18/bd_173e_swn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/project9/project1.gen/sources_1/bd/project1/ip/project1_smartconnect_0_0/bd_0/ip/ip_19/bd_173e_sbn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/project9/project1.gen/sources_1/bd/project1/ip/project1_smartconnect_0_0/bd_0/ip/ip_23/bd_173e_s02a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/project9/project1.gen/sources_1/bd/project1/ip/project1_smartconnect_0_0/bd_0/ip/ip_24/bd_173e_sarn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/project9/project1.gen/sources_1/bd/project1/ip/project1_smartconnect_0_0/bd_0/ip/ip_25/bd_173e_srn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/project9/project1.gen/sources_1/bd/project1/ip/project1_smartconnect_0_0/bd_0/ip/ip_29/bd_173e_s03a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/project9/project1.gen/sources_1/bd/project1/ip/project1_smartconnect_0_0/bd_0/ip/ip_30/bd_173e_sawn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/project9/project1.gen/sources_1/bd/project1/ip/project1_smartconnect_0_0/bd_0/ip/ip_31/bd_173e_swn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/project9/project1.gen/sources_1/bd/project1/ip/project1_smartconnect_0_0/bd_0/ip/ip_32/bd_173e_sbn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/project9/project1.gen/sources_1/bd/project1/ip/project1_smartconnect_0_0/bd_0/ip/ip_33/bd_173e_m00s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/project9/project1.gen/sources_1/bd/project1/ip/project1_smartconnect_0_0/bd_0/ip/ip_34/bd_173e_m00arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/project9/project1.gen/sources_1/bd/project1/ip/project1_smartconnect_0_0/bd_0/ip/ip_35/bd_173e_m00rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/project9/project1.gen/sources_1/bd/project1/ip/project1_smartconnect_0_0/bd_0/ip/ip_36/bd_173e_m00awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/project9/project1.gen/sources_1/bd/project1/ip/project1_smartconnect_0_0/bd_0/ip/ip_37/bd_173e_m00wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/project9/project1.gen/sources_1/bd/project1/ip/project1_smartconnect_0_0/bd_0/ip/ip_38/bd_173e_m00bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/project9/project1.gen/sources_1/bd/project1/ip/project1_smartconnect_0_0/ooc.xdc]
set_property used_in_implementation false [get_files -all c:/project9/project1.gen/sources_1/bd/project1/ip/project1_smartconnect_0_0/smartconnect.xdc]
set_property used_in_implementation false [get_files -all c:/project9/project1.gen/sources_1/bd/project1/ip/project1_axi_interconnect_0_imp_auto_pc_0/project1_axi_interconnect_0_imp_auto_pc_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all c:/project9/project1.gen/sources_1/bd/project1/ip/project1_axi_interconnect_0_imp_auto_cc_0/project1_axi_interconnect_0_imp_auto_cc_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/project9/project1.gen/sources_1/bd/project1/ip/project1_axi_interconnect_0_imp_auto_cc_0/project1_axi_interconnect_0_imp_auto_cc_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/project9/project1.gen/sources_1/bd/project1/ip/project1_axi_interconnect_0_imp_auto_cc_0/project1_axi_interconnect_0_imp_auto_cc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/project9/project1.gen/sources_1/bd/project1/ip/project1_quad_frame_remapper_0_0/constraints/quad_frame_remapper_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/project9/project1.gen/sources_1/bd/project1/project1_ooc.xdc]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/project9/project1.srcs/constrs_1/new/project1.xdc
set_property used_in_implementation false [get_files C:/project9/project1.srcs/constrs_1/new/project1.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top project1_wrapper -part xc7z020clg400-1
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef project1_wrapper.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
generate_parallel_reports -reports { "report_utilization -file project1_wrapper_utilization_synth.rpt -pb project1_wrapper_utilization_synth.pb"  } 
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
