// ==============================================================
// Generated by Vitis HLS v2025.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="quad_frame_remapper_quad_frame_remapper,hls_ip_2025_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=7.300000,HLS_SYN_LAT=3297241,HLS_SYN_TPT=none,HLS_SYN_MEM=28,HLS_SYN_DSP=0,HLS_SYN_FF=3818,HLS_SYN_LUT=9241,HLS_VERSION=2025_1}" *)

module quad_frame_remapper (
        ap_clk,
        ap_rst_n,
        m_axi_gmem0_AWVALID,
        m_axi_gmem0_AWREADY,
        m_axi_gmem0_AWADDR,
        m_axi_gmem0_AWID,
        m_axi_gmem0_AWLEN,
        m_axi_gmem0_AWSIZE,
        m_axi_gmem0_AWBURST,
        m_axi_gmem0_AWLOCK,
        m_axi_gmem0_AWCACHE,
        m_axi_gmem0_AWPROT,
        m_axi_gmem0_AWQOS,
        m_axi_gmem0_AWREGION,
        m_axi_gmem0_AWUSER,
        m_axi_gmem0_WVALID,
        m_axi_gmem0_WREADY,
        m_axi_gmem0_WDATA,
        m_axi_gmem0_WSTRB,
        m_axi_gmem0_WLAST,
        m_axi_gmem0_WID,
        m_axi_gmem0_WUSER,
        m_axi_gmem0_ARVALID,
        m_axi_gmem0_ARREADY,
        m_axi_gmem0_ARADDR,
        m_axi_gmem0_ARID,
        m_axi_gmem0_ARLEN,
        m_axi_gmem0_ARSIZE,
        m_axi_gmem0_ARBURST,
        m_axi_gmem0_ARLOCK,
        m_axi_gmem0_ARCACHE,
        m_axi_gmem0_ARPROT,
        m_axi_gmem0_ARQOS,
        m_axi_gmem0_ARREGION,
        m_axi_gmem0_ARUSER,
        m_axi_gmem0_RVALID,
        m_axi_gmem0_RREADY,
        m_axi_gmem0_RDATA,
        m_axi_gmem0_RLAST,
        m_axi_gmem0_RID,
        m_axi_gmem0_RUSER,
        m_axi_gmem0_RRESP,
        m_axi_gmem0_BVALID,
        m_axi_gmem0_BREADY,
        m_axi_gmem0_BRESP,
        m_axi_gmem0_BID,
        m_axi_gmem0_BUSER,
        m_axi_gmem1_AWVALID,
        m_axi_gmem1_AWREADY,
        m_axi_gmem1_AWADDR,
        m_axi_gmem1_AWID,
        m_axi_gmem1_AWLEN,
        m_axi_gmem1_AWSIZE,
        m_axi_gmem1_AWBURST,
        m_axi_gmem1_AWLOCK,
        m_axi_gmem1_AWCACHE,
        m_axi_gmem1_AWPROT,
        m_axi_gmem1_AWQOS,
        m_axi_gmem1_AWREGION,
        m_axi_gmem1_AWUSER,
        m_axi_gmem1_WVALID,
        m_axi_gmem1_WREADY,
        m_axi_gmem1_WDATA,
        m_axi_gmem1_WSTRB,
        m_axi_gmem1_WLAST,
        m_axi_gmem1_WID,
        m_axi_gmem1_WUSER,
        m_axi_gmem1_ARVALID,
        m_axi_gmem1_ARREADY,
        m_axi_gmem1_ARADDR,
        m_axi_gmem1_ARID,
        m_axi_gmem1_ARLEN,
        m_axi_gmem1_ARSIZE,
        m_axi_gmem1_ARBURST,
        m_axi_gmem1_ARLOCK,
        m_axi_gmem1_ARCACHE,
        m_axi_gmem1_ARPROT,
        m_axi_gmem1_ARQOS,
        m_axi_gmem1_ARREGION,
        m_axi_gmem1_ARUSER,
        m_axi_gmem1_RVALID,
        m_axi_gmem1_RREADY,
        m_axi_gmem1_RDATA,
        m_axi_gmem1_RLAST,
        m_axi_gmem1_RID,
        m_axi_gmem1_RUSER,
        m_axi_gmem1_RRESP,
        m_axi_gmem1_BVALID,
        m_axi_gmem1_BREADY,
        m_axi_gmem1_BRESP,
        m_axi_gmem1_BID,
        m_axi_gmem1_BUSER,
        s_axi_control_AWVALID,
        s_axi_control_AWREADY,
        s_axi_control_AWADDR,
        s_axi_control_WVALID,
        s_axi_control_WREADY,
        s_axi_control_WDATA,
        s_axi_control_WSTRB,
        s_axi_control_ARVALID,
        s_axi_control_ARREADY,
        s_axi_control_ARADDR,
        s_axi_control_RVALID,
        s_axi_control_RREADY,
        s_axi_control_RDATA,
        s_axi_control_RRESP,
        s_axi_control_BVALID,
        s_axi_control_BREADY,
        s_axi_control_BRESP,
        interrupt
);

parameter    ap_ST_fsm_state1 = 35'd1;
parameter    ap_ST_fsm_state2 = 35'd2;
parameter    ap_ST_fsm_state3 = 35'd4;
parameter    ap_ST_fsm_state4 = 35'd8;
parameter    ap_ST_fsm_state5 = 35'd16;
parameter    ap_ST_fsm_state6 = 35'd32;
parameter    ap_ST_fsm_state7 = 35'd64;
parameter    ap_ST_fsm_state8 = 35'd128;
parameter    ap_ST_fsm_state9 = 35'd256;
parameter    ap_ST_fsm_state10 = 35'd512;
parameter    ap_ST_fsm_state11 = 35'd1024;
parameter    ap_ST_fsm_state12 = 35'd2048;
parameter    ap_ST_fsm_state13 = 35'd4096;
parameter    ap_ST_fsm_state14 = 35'd8192;
parameter    ap_ST_fsm_state15 = 35'd16384;
parameter    ap_ST_fsm_state16 = 35'd32768;
parameter    ap_ST_fsm_state17 = 35'd65536;
parameter    ap_ST_fsm_state18 = 35'd131072;
parameter    ap_ST_fsm_state19 = 35'd262144;
parameter    ap_ST_fsm_state20 = 35'd524288;
parameter    ap_ST_fsm_state21 = 35'd1048576;
parameter    ap_ST_fsm_state22 = 35'd2097152;
parameter    ap_ST_fsm_state23 = 35'd4194304;
parameter    ap_ST_fsm_state24 = 35'd8388608;
parameter    ap_ST_fsm_state25 = 35'd16777216;
parameter    ap_ST_fsm_state26 = 35'd33554432;
parameter    ap_ST_fsm_state27 = 35'd67108864;
parameter    ap_ST_fsm_state28 = 35'd134217728;
parameter    ap_ST_fsm_state29 = 35'd268435456;
parameter    ap_ST_fsm_state30 = 35'd536870912;
parameter    ap_ST_fsm_state31 = 35'd1073741824;
parameter    ap_ST_fsm_state32 = 35'd2147483648;
parameter    ap_ST_fsm_state33 = 35'd4294967296;
parameter    ap_ST_fsm_state34 = 35'd8589934592;
parameter    ap_ST_fsm_state35 = 35'd17179869184;
parameter    C_S_AXI_CONTROL_DATA_WIDTH = 32;
parameter    C_S_AXI_CONTROL_ADDR_WIDTH = 6;
parameter    C_S_AXI_DATA_WIDTH = 32;
parameter    C_M_AXI_GMEM0_ID_WIDTH = 1;
parameter    C_M_AXI_GMEM0_ADDR_WIDTH = 64;
parameter    C_M_AXI_GMEM0_DATA_WIDTH = 128;
parameter    C_M_AXI_GMEM0_AWUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM0_ARUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM0_WUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM0_RUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM0_BUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM0_USER_VALUE = 0;
parameter    C_M_AXI_GMEM0_PROT_VALUE = 0;
parameter    C_M_AXI_GMEM0_CACHE_VALUE = 3;
parameter    C_M_AXI_DATA_WIDTH = 32;
parameter    C_M_AXI_GMEM1_ID_WIDTH = 1;
parameter    C_M_AXI_GMEM1_ADDR_WIDTH = 64;
parameter    C_M_AXI_GMEM1_DATA_WIDTH = 128;
parameter    C_M_AXI_GMEM1_AWUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM1_ARUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM1_WUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM1_RUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM1_BUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM1_USER_VALUE = 0;
parameter    C_M_AXI_GMEM1_PROT_VALUE = 0;
parameter    C_M_AXI_GMEM1_CACHE_VALUE = 3;

parameter C_S_AXI_CONTROL_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_GMEM0_WSTRB_WIDTH = (128 / 8);
parameter C_M_AXI_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_GMEM1_WSTRB_WIDTH = (128 / 8);

input   ap_clk;
input   ap_rst_n;
output   m_axi_gmem0_AWVALID;
input   m_axi_gmem0_AWREADY;
output  [C_M_AXI_GMEM0_ADDR_WIDTH - 1:0] m_axi_gmem0_AWADDR;
output  [C_M_AXI_GMEM0_ID_WIDTH - 1:0] m_axi_gmem0_AWID;
output  [7:0] m_axi_gmem0_AWLEN;
output  [2:0] m_axi_gmem0_AWSIZE;
output  [1:0] m_axi_gmem0_AWBURST;
output  [1:0] m_axi_gmem0_AWLOCK;
output  [3:0] m_axi_gmem0_AWCACHE;
output  [2:0] m_axi_gmem0_AWPROT;
output  [3:0] m_axi_gmem0_AWQOS;
output  [3:0] m_axi_gmem0_AWREGION;
output  [C_M_AXI_GMEM0_AWUSER_WIDTH - 1:0] m_axi_gmem0_AWUSER;
output   m_axi_gmem0_WVALID;
input   m_axi_gmem0_WREADY;
output  [C_M_AXI_GMEM0_DATA_WIDTH - 1:0] m_axi_gmem0_WDATA;
output  [C_M_AXI_GMEM0_WSTRB_WIDTH - 1:0] m_axi_gmem0_WSTRB;
output   m_axi_gmem0_WLAST;
output  [C_M_AXI_GMEM0_ID_WIDTH - 1:0] m_axi_gmem0_WID;
output  [C_M_AXI_GMEM0_WUSER_WIDTH - 1:0] m_axi_gmem0_WUSER;
output   m_axi_gmem0_ARVALID;
input   m_axi_gmem0_ARREADY;
output  [C_M_AXI_GMEM0_ADDR_WIDTH - 1:0] m_axi_gmem0_ARADDR;
output  [C_M_AXI_GMEM0_ID_WIDTH - 1:0] m_axi_gmem0_ARID;
output  [7:0] m_axi_gmem0_ARLEN;
output  [2:0] m_axi_gmem0_ARSIZE;
output  [1:0] m_axi_gmem0_ARBURST;
output  [1:0] m_axi_gmem0_ARLOCK;
output  [3:0] m_axi_gmem0_ARCACHE;
output  [2:0] m_axi_gmem0_ARPROT;
output  [3:0] m_axi_gmem0_ARQOS;
output  [3:0] m_axi_gmem0_ARREGION;
output  [C_M_AXI_GMEM0_ARUSER_WIDTH - 1:0] m_axi_gmem0_ARUSER;
input   m_axi_gmem0_RVALID;
output   m_axi_gmem0_RREADY;
input  [C_M_AXI_GMEM0_DATA_WIDTH - 1:0] m_axi_gmem0_RDATA;
input   m_axi_gmem0_RLAST;
input  [C_M_AXI_GMEM0_ID_WIDTH - 1:0] m_axi_gmem0_RID;
input  [C_M_AXI_GMEM0_RUSER_WIDTH - 1:0] m_axi_gmem0_RUSER;
input  [1:0] m_axi_gmem0_RRESP;
input   m_axi_gmem0_BVALID;
output   m_axi_gmem0_BREADY;
input  [1:0] m_axi_gmem0_BRESP;
input  [C_M_AXI_GMEM0_ID_WIDTH - 1:0] m_axi_gmem0_BID;
input  [C_M_AXI_GMEM0_BUSER_WIDTH - 1:0] m_axi_gmem0_BUSER;
output   m_axi_gmem1_AWVALID;
input   m_axi_gmem1_AWREADY;
output  [C_M_AXI_GMEM1_ADDR_WIDTH - 1:0] m_axi_gmem1_AWADDR;
output  [C_M_AXI_GMEM1_ID_WIDTH - 1:0] m_axi_gmem1_AWID;
output  [7:0] m_axi_gmem1_AWLEN;
output  [2:0] m_axi_gmem1_AWSIZE;
output  [1:0] m_axi_gmem1_AWBURST;
output  [1:0] m_axi_gmem1_AWLOCK;
output  [3:0] m_axi_gmem1_AWCACHE;
output  [2:0] m_axi_gmem1_AWPROT;
output  [3:0] m_axi_gmem1_AWQOS;
output  [3:0] m_axi_gmem1_AWREGION;
output  [C_M_AXI_GMEM1_AWUSER_WIDTH - 1:0] m_axi_gmem1_AWUSER;
output   m_axi_gmem1_WVALID;
input   m_axi_gmem1_WREADY;
output  [C_M_AXI_GMEM1_DATA_WIDTH - 1:0] m_axi_gmem1_WDATA;
output  [C_M_AXI_GMEM1_WSTRB_WIDTH - 1:0] m_axi_gmem1_WSTRB;
output   m_axi_gmem1_WLAST;
output  [C_M_AXI_GMEM1_ID_WIDTH - 1:0] m_axi_gmem1_WID;
output  [C_M_AXI_GMEM1_WUSER_WIDTH - 1:0] m_axi_gmem1_WUSER;
output   m_axi_gmem1_ARVALID;
input   m_axi_gmem1_ARREADY;
output  [C_M_AXI_GMEM1_ADDR_WIDTH - 1:0] m_axi_gmem1_ARADDR;
output  [C_M_AXI_GMEM1_ID_WIDTH - 1:0] m_axi_gmem1_ARID;
output  [7:0] m_axi_gmem1_ARLEN;
output  [2:0] m_axi_gmem1_ARSIZE;
output  [1:0] m_axi_gmem1_ARBURST;
output  [1:0] m_axi_gmem1_ARLOCK;
output  [3:0] m_axi_gmem1_ARCACHE;
output  [2:0] m_axi_gmem1_ARPROT;
output  [3:0] m_axi_gmem1_ARQOS;
output  [3:0] m_axi_gmem1_ARREGION;
output  [C_M_AXI_GMEM1_ARUSER_WIDTH - 1:0] m_axi_gmem1_ARUSER;
input   m_axi_gmem1_RVALID;
output   m_axi_gmem1_RREADY;
input  [C_M_AXI_GMEM1_DATA_WIDTH - 1:0] m_axi_gmem1_RDATA;
input   m_axi_gmem1_RLAST;
input  [C_M_AXI_GMEM1_ID_WIDTH - 1:0] m_axi_gmem1_RID;
input  [C_M_AXI_GMEM1_RUSER_WIDTH - 1:0] m_axi_gmem1_RUSER;
input  [1:0] m_axi_gmem1_RRESP;
input   m_axi_gmem1_BVALID;
output   m_axi_gmem1_BREADY;
input  [1:0] m_axi_gmem1_BRESP;
input  [C_M_AXI_GMEM1_ID_WIDTH - 1:0] m_axi_gmem1_BID;
input  [C_M_AXI_GMEM1_BUSER_WIDTH - 1:0] m_axi_gmem1_BUSER;
input   s_axi_control_AWVALID;
output   s_axi_control_AWREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_AWADDR;
input   s_axi_control_WVALID;
output   s_axi_control_WREADY;
input  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_WDATA;
input  [C_S_AXI_CONTROL_WSTRB_WIDTH - 1:0] s_axi_control_WSTRB;
input   s_axi_control_ARVALID;
output   s_axi_control_ARREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_ARADDR;
output   s_axi_control_RVALID;
input   s_axi_control_RREADY;
output  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_RDATA;
output  [1:0] s_axi_control_RRESP;
output   s_axi_control_BVALID;
input   s_axi_control_BREADY;
output  [1:0] s_axi_control_BRESP;
output   interrupt;

 reg    ap_rst_n_inv;
wire    ap_start;
reg    ap_done;
reg    ap_idle;
(* fsm_encoding = "none" *) reg   [34:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_ready;
wire   [63:0] src;
wire   [63:0] dst;
wire   [31:0] size_in_16bytes;
reg    gmem0_blk_n_AR;
wire    ap_CS_fsm_state6;
reg    gmem1_blk_n_AW;
wire    ap_CS_fsm_state28;
reg    gmem1_blk_n_B;
wire    ap_CS_fsm_state35;
wire    ap_CS_fsm_state19;
wire    ap_CS_fsm_state26;
reg   [0:0] or_ln102_reg_526;
wire  signed [59:0] grp_fu_235_p4;
reg   [59:0] reg_244;
wire    ap_CS_fsm_state4;
reg   [63:0] dst_read_reg_487;
reg   [63:0] src_read_reg_492;
wire   [22:0] add_ln91_fu_266_p2;
reg   [22:0] add_ln91_reg_497;
wire    ap_CS_fsm_state2;
wire   [10:0] y_2_fu_278_p2;
reg   [10:0] y_2_reg_505;
wire   [63:0] add_ln95_fu_292_p2;
reg   [63:0] add_ln95_reg_510;
wire   [0:0] is_bottom_fu_297_p2;
reg   [0:0] is_bottom_reg_515;
wire   [9:0] local_y_fu_309_p3;
reg   [9:0] local_y_reg_520;
wire   [0:0] or_ln102_fu_329_p2;
wire   [10:0] src_y_fu_391_p3;
reg   [10:0] src_y_reg_530;
wire    ap_CS_fsm_state3;
wire   [18:0] mul_ln123_fu_401_p2;
reg   [18:0] mul_ln123_reg_535;
reg   [59:0] trunc_ln1_reg_540;
wire    ap_CS_fsm_state5;
reg   [8:0] line_buf_in_address0;
reg    line_buf_in_ce0;
reg    line_buf_in_we0;
wire   [127:0] line_buf_in_q0;
reg   [8:0] line_buf_in_address1;
reg    line_buf_in_ce1;
wire   [127:0] line_buf_in_q1;
reg   [8:0] line_buf_out_address0;
reg    line_buf_out_ce0;
reg   [15:0] line_buf_out_we0;
reg   [127:0] line_buf_out_d0;
wire   [127:0] line_buf_out_q0;
wire    grp_quad_frame_remapper_Pipeline_1_fu_189_ap_start;
wire    grp_quad_frame_remapper_Pipeline_1_fu_189_ap_done;
wire    grp_quad_frame_remapper_Pipeline_1_fu_189_ap_idle;
wire    grp_quad_frame_remapper_Pipeline_1_fu_189_ap_ready;
wire   [8:0] grp_quad_frame_remapper_Pipeline_1_fu_189_line_buf_out_address0;
wire    grp_quad_frame_remapper_Pipeline_1_fu_189_line_buf_out_ce0;
wire   [15:0] grp_quad_frame_remapper_Pipeline_1_fu_189_line_buf_out_we0;
wire   [127:0] grp_quad_frame_remapper_Pipeline_1_fu_189_line_buf_out_d0;
wire    grp_quad_frame_remapper_Pipeline_3_fu_194_ap_start;
wire    grp_quad_frame_remapper_Pipeline_3_fu_194_ap_done;
wire    grp_quad_frame_remapper_Pipeline_3_fu_194_ap_idle;
wire    grp_quad_frame_remapper_Pipeline_3_fu_194_ap_ready;
wire    grp_quad_frame_remapper_Pipeline_3_fu_194_m_axi_gmem0_0_AWVALID;
wire   [63:0] grp_quad_frame_remapper_Pipeline_3_fu_194_m_axi_gmem0_0_AWADDR;
wire   [0:0] grp_quad_frame_remapper_Pipeline_3_fu_194_m_axi_gmem0_0_AWID;
wire   [31:0] grp_quad_frame_remapper_Pipeline_3_fu_194_m_axi_gmem0_0_AWLEN;
wire   [2:0] grp_quad_frame_remapper_Pipeline_3_fu_194_m_axi_gmem0_0_AWSIZE;
wire   [1:0] grp_quad_frame_remapper_Pipeline_3_fu_194_m_axi_gmem0_0_AWBURST;
wire   [1:0] grp_quad_frame_remapper_Pipeline_3_fu_194_m_axi_gmem0_0_AWLOCK;
wire   [3:0] grp_quad_frame_remapper_Pipeline_3_fu_194_m_axi_gmem0_0_AWCACHE;
wire   [2:0] grp_quad_frame_remapper_Pipeline_3_fu_194_m_axi_gmem0_0_AWPROT;
wire   [3:0] grp_quad_frame_remapper_Pipeline_3_fu_194_m_axi_gmem0_0_AWQOS;
wire   [3:0] grp_quad_frame_remapper_Pipeline_3_fu_194_m_axi_gmem0_0_AWREGION;
wire   [0:0] grp_quad_frame_remapper_Pipeline_3_fu_194_m_axi_gmem0_0_AWUSER;
wire    grp_quad_frame_remapper_Pipeline_3_fu_194_m_axi_gmem0_0_WVALID;
wire   [127:0] grp_quad_frame_remapper_Pipeline_3_fu_194_m_axi_gmem0_0_WDATA;
wire   [15:0] grp_quad_frame_remapper_Pipeline_3_fu_194_m_axi_gmem0_0_WSTRB;
wire    grp_quad_frame_remapper_Pipeline_3_fu_194_m_axi_gmem0_0_WLAST;
wire   [0:0] grp_quad_frame_remapper_Pipeline_3_fu_194_m_axi_gmem0_0_WID;
wire   [0:0] grp_quad_frame_remapper_Pipeline_3_fu_194_m_axi_gmem0_0_WUSER;
wire    grp_quad_frame_remapper_Pipeline_3_fu_194_m_axi_gmem0_0_ARVALID;
wire   [63:0] grp_quad_frame_remapper_Pipeline_3_fu_194_m_axi_gmem0_0_ARADDR;
wire   [0:0] grp_quad_frame_remapper_Pipeline_3_fu_194_m_axi_gmem0_0_ARID;
wire   [31:0] grp_quad_frame_remapper_Pipeline_3_fu_194_m_axi_gmem0_0_ARLEN;
wire   [2:0] grp_quad_frame_remapper_Pipeline_3_fu_194_m_axi_gmem0_0_ARSIZE;
wire   [1:0] grp_quad_frame_remapper_Pipeline_3_fu_194_m_axi_gmem0_0_ARBURST;
wire   [1:0] grp_quad_frame_remapper_Pipeline_3_fu_194_m_axi_gmem0_0_ARLOCK;
wire   [3:0] grp_quad_frame_remapper_Pipeline_3_fu_194_m_axi_gmem0_0_ARCACHE;
wire   [2:0] grp_quad_frame_remapper_Pipeline_3_fu_194_m_axi_gmem0_0_ARPROT;
wire   [3:0] grp_quad_frame_remapper_Pipeline_3_fu_194_m_axi_gmem0_0_ARQOS;
wire   [3:0] grp_quad_frame_remapper_Pipeline_3_fu_194_m_axi_gmem0_0_ARREGION;
wire   [0:0] grp_quad_frame_remapper_Pipeline_3_fu_194_m_axi_gmem0_0_ARUSER;
wire    grp_quad_frame_remapper_Pipeline_3_fu_194_m_axi_gmem0_0_RREADY;
wire    grp_quad_frame_remapper_Pipeline_3_fu_194_m_axi_gmem0_0_BREADY;
wire   [8:0] grp_quad_frame_remapper_Pipeline_3_fu_194_line_buf_in_address0;
wire    grp_quad_frame_remapper_Pipeline_3_fu_194_line_buf_in_ce0;
wire    grp_quad_frame_remapper_Pipeline_3_fu_194_line_buf_in_we0;
wire   [127:0] grp_quad_frame_remapper_Pipeline_3_fu_194_line_buf_in_d0;
wire    grp_quad_frame_remapper_Pipeline_4_fu_202_ap_start;
wire    grp_quad_frame_remapper_Pipeline_4_fu_202_ap_done;
wire    grp_quad_frame_remapper_Pipeline_4_fu_202_ap_idle;
wire    grp_quad_frame_remapper_Pipeline_4_fu_202_ap_ready;
wire   [8:0] grp_quad_frame_remapper_Pipeline_4_fu_202_line_buf_out_address0;
wire    grp_quad_frame_remapper_Pipeline_4_fu_202_line_buf_out_ce0;
wire   [15:0] grp_quad_frame_remapper_Pipeline_4_fu_202_line_buf_out_we0;
wire   [127:0] grp_quad_frame_remapper_Pipeline_4_fu_202_line_buf_out_d0;
wire    grp_quad_frame_remapper_Pipeline_VITIS_LOOP_132_2_fu_207_ap_start;
wire    grp_quad_frame_remapper_Pipeline_VITIS_LOOP_132_2_fu_207_ap_done;
wire    grp_quad_frame_remapper_Pipeline_VITIS_LOOP_132_2_fu_207_ap_idle;
wire    grp_quad_frame_remapper_Pipeline_VITIS_LOOP_132_2_fu_207_ap_ready;
wire   [8:0] grp_quad_frame_remapper_Pipeline_VITIS_LOOP_132_2_fu_207_line_buf_in_address0;
wire    grp_quad_frame_remapper_Pipeline_VITIS_LOOP_132_2_fu_207_line_buf_in_ce0;
wire   [8:0] grp_quad_frame_remapper_Pipeline_VITIS_LOOP_132_2_fu_207_line_buf_in_address1;
wire    grp_quad_frame_remapper_Pipeline_VITIS_LOOP_132_2_fu_207_line_buf_in_ce1;
wire   [8:0] grp_quad_frame_remapper_Pipeline_VITIS_LOOP_132_2_fu_207_line_buf_out_address0;
wire    grp_quad_frame_remapper_Pipeline_VITIS_LOOP_132_2_fu_207_line_buf_out_ce0;
wire   [15:0] grp_quad_frame_remapper_Pipeline_VITIS_LOOP_132_2_fu_207_line_buf_out_we0;
wire   [127:0] grp_quad_frame_remapper_Pipeline_VITIS_LOOP_132_2_fu_207_line_buf_out_d0;
wire    grp_quad_frame_remapper_Pipeline_VITIS_LOOP_146_3_fu_213_ap_start;
wire    grp_quad_frame_remapper_Pipeline_VITIS_LOOP_146_3_fu_213_ap_done;
wire    grp_quad_frame_remapper_Pipeline_VITIS_LOOP_146_3_fu_213_ap_idle;
wire    grp_quad_frame_remapper_Pipeline_VITIS_LOOP_146_3_fu_213_ap_ready;
wire   [8:0] grp_quad_frame_remapper_Pipeline_VITIS_LOOP_146_3_fu_213_line_buf_in_address0;
wire    grp_quad_frame_remapper_Pipeline_VITIS_LOOP_146_3_fu_213_line_buf_in_ce0;
wire   [8:0] grp_quad_frame_remapper_Pipeline_VITIS_LOOP_146_3_fu_213_line_buf_in_address1;
wire    grp_quad_frame_remapper_Pipeline_VITIS_LOOP_146_3_fu_213_line_buf_in_ce1;
wire   [8:0] grp_quad_frame_remapper_Pipeline_VITIS_LOOP_146_3_fu_213_line_buf_out_address0;
wire    grp_quad_frame_remapper_Pipeline_VITIS_LOOP_146_3_fu_213_line_buf_out_ce0;
wire   [15:0] grp_quad_frame_remapper_Pipeline_VITIS_LOOP_146_3_fu_213_line_buf_out_we0;
wire   [127:0] grp_quad_frame_remapper_Pipeline_VITIS_LOOP_146_3_fu_213_line_buf_out_d0;
wire    grp_quad_frame_remapper_Pipeline_7_fu_219_ap_start;
wire    grp_quad_frame_remapper_Pipeline_7_fu_219_ap_done;
wire    grp_quad_frame_remapper_Pipeline_7_fu_219_ap_idle;
wire    grp_quad_frame_remapper_Pipeline_7_fu_219_ap_ready;
wire    grp_quad_frame_remapper_Pipeline_7_fu_219_m_axi_gmem1_0_AWVALID;
wire   [63:0] grp_quad_frame_remapper_Pipeline_7_fu_219_m_axi_gmem1_0_AWADDR;
wire   [0:0] grp_quad_frame_remapper_Pipeline_7_fu_219_m_axi_gmem1_0_AWID;
wire   [31:0] grp_quad_frame_remapper_Pipeline_7_fu_219_m_axi_gmem1_0_AWLEN;
wire   [2:0] grp_quad_frame_remapper_Pipeline_7_fu_219_m_axi_gmem1_0_AWSIZE;
wire   [1:0] grp_quad_frame_remapper_Pipeline_7_fu_219_m_axi_gmem1_0_AWBURST;
wire   [1:0] grp_quad_frame_remapper_Pipeline_7_fu_219_m_axi_gmem1_0_AWLOCK;
wire   [3:0] grp_quad_frame_remapper_Pipeline_7_fu_219_m_axi_gmem1_0_AWCACHE;
wire   [2:0] grp_quad_frame_remapper_Pipeline_7_fu_219_m_axi_gmem1_0_AWPROT;
wire   [3:0] grp_quad_frame_remapper_Pipeline_7_fu_219_m_axi_gmem1_0_AWQOS;
wire   [3:0] grp_quad_frame_remapper_Pipeline_7_fu_219_m_axi_gmem1_0_AWREGION;
wire   [0:0] grp_quad_frame_remapper_Pipeline_7_fu_219_m_axi_gmem1_0_AWUSER;
wire    grp_quad_frame_remapper_Pipeline_7_fu_219_m_axi_gmem1_0_WVALID;
wire   [127:0] grp_quad_frame_remapper_Pipeline_7_fu_219_m_axi_gmem1_0_WDATA;
wire   [15:0] grp_quad_frame_remapper_Pipeline_7_fu_219_m_axi_gmem1_0_WSTRB;
wire    grp_quad_frame_remapper_Pipeline_7_fu_219_m_axi_gmem1_0_WLAST;
wire   [0:0] grp_quad_frame_remapper_Pipeline_7_fu_219_m_axi_gmem1_0_WID;
wire   [0:0] grp_quad_frame_remapper_Pipeline_7_fu_219_m_axi_gmem1_0_WUSER;
wire    grp_quad_frame_remapper_Pipeline_7_fu_219_m_axi_gmem1_0_ARVALID;
wire   [63:0] grp_quad_frame_remapper_Pipeline_7_fu_219_m_axi_gmem1_0_ARADDR;
wire   [0:0] grp_quad_frame_remapper_Pipeline_7_fu_219_m_axi_gmem1_0_ARID;
wire   [31:0] grp_quad_frame_remapper_Pipeline_7_fu_219_m_axi_gmem1_0_ARLEN;
wire   [2:0] grp_quad_frame_remapper_Pipeline_7_fu_219_m_axi_gmem1_0_ARSIZE;
wire   [1:0] grp_quad_frame_remapper_Pipeline_7_fu_219_m_axi_gmem1_0_ARBURST;
wire   [1:0] grp_quad_frame_remapper_Pipeline_7_fu_219_m_axi_gmem1_0_ARLOCK;
wire   [3:0] grp_quad_frame_remapper_Pipeline_7_fu_219_m_axi_gmem1_0_ARCACHE;
wire   [2:0] grp_quad_frame_remapper_Pipeline_7_fu_219_m_axi_gmem1_0_ARPROT;
wire   [3:0] grp_quad_frame_remapper_Pipeline_7_fu_219_m_axi_gmem1_0_ARQOS;
wire   [3:0] grp_quad_frame_remapper_Pipeline_7_fu_219_m_axi_gmem1_0_ARREGION;
wire   [0:0] grp_quad_frame_remapper_Pipeline_7_fu_219_m_axi_gmem1_0_ARUSER;
wire    grp_quad_frame_remapper_Pipeline_7_fu_219_m_axi_gmem1_0_RREADY;
wire    grp_quad_frame_remapper_Pipeline_7_fu_219_m_axi_gmem1_0_BREADY;
wire   [8:0] grp_quad_frame_remapper_Pipeline_7_fu_219_line_buf_out_address0;
wire    grp_quad_frame_remapper_Pipeline_7_fu_219_line_buf_out_ce0;
wire    grp_quad_frame_remapper_Pipeline_2_fu_227_ap_start;
wire    grp_quad_frame_remapper_Pipeline_2_fu_227_ap_done;
wire    grp_quad_frame_remapper_Pipeline_2_fu_227_ap_idle;
wire    grp_quad_frame_remapper_Pipeline_2_fu_227_ap_ready;
wire    grp_quad_frame_remapper_Pipeline_2_fu_227_m_axi_gmem1_0_AWVALID;
wire   [63:0] grp_quad_frame_remapper_Pipeline_2_fu_227_m_axi_gmem1_0_AWADDR;
wire   [0:0] grp_quad_frame_remapper_Pipeline_2_fu_227_m_axi_gmem1_0_AWID;
wire   [31:0] grp_quad_frame_remapper_Pipeline_2_fu_227_m_axi_gmem1_0_AWLEN;
wire   [2:0] grp_quad_frame_remapper_Pipeline_2_fu_227_m_axi_gmem1_0_AWSIZE;
wire   [1:0] grp_quad_frame_remapper_Pipeline_2_fu_227_m_axi_gmem1_0_AWBURST;
wire   [1:0] grp_quad_frame_remapper_Pipeline_2_fu_227_m_axi_gmem1_0_AWLOCK;
wire   [3:0] grp_quad_frame_remapper_Pipeline_2_fu_227_m_axi_gmem1_0_AWCACHE;
wire   [2:0] grp_quad_frame_remapper_Pipeline_2_fu_227_m_axi_gmem1_0_AWPROT;
wire   [3:0] grp_quad_frame_remapper_Pipeline_2_fu_227_m_axi_gmem1_0_AWQOS;
wire   [3:0] grp_quad_frame_remapper_Pipeline_2_fu_227_m_axi_gmem1_0_AWREGION;
wire   [0:0] grp_quad_frame_remapper_Pipeline_2_fu_227_m_axi_gmem1_0_AWUSER;
wire    grp_quad_frame_remapper_Pipeline_2_fu_227_m_axi_gmem1_0_WVALID;
wire   [127:0] grp_quad_frame_remapper_Pipeline_2_fu_227_m_axi_gmem1_0_WDATA;
wire   [15:0] grp_quad_frame_remapper_Pipeline_2_fu_227_m_axi_gmem1_0_WSTRB;
wire    grp_quad_frame_remapper_Pipeline_2_fu_227_m_axi_gmem1_0_WLAST;
wire   [0:0] grp_quad_frame_remapper_Pipeline_2_fu_227_m_axi_gmem1_0_WID;
wire   [0:0] grp_quad_frame_remapper_Pipeline_2_fu_227_m_axi_gmem1_0_WUSER;
wire    grp_quad_frame_remapper_Pipeline_2_fu_227_m_axi_gmem1_0_ARVALID;
wire   [63:0] grp_quad_frame_remapper_Pipeline_2_fu_227_m_axi_gmem1_0_ARADDR;
wire   [0:0] grp_quad_frame_remapper_Pipeline_2_fu_227_m_axi_gmem1_0_ARID;
wire   [31:0] grp_quad_frame_remapper_Pipeline_2_fu_227_m_axi_gmem1_0_ARLEN;
wire   [2:0] grp_quad_frame_remapper_Pipeline_2_fu_227_m_axi_gmem1_0_ARSIZE;
wire   [1:0] grp_quad_frame_remapper_Pipeline_2_fu_227_m_axi_gmem1_0_ARBURST;
wire   [1:0] grp_quad_frame_remapper_Pipeline_2_fu_227_m_axi_gmem1_0_ARLOCK;
wire   [3:0] grp_quad_frame_remapper_Pipeline_2_fu_227_m_axi_gmem1_0_ARCACHE;
wire   [2:0] grp_quad_frame_remapper_Pipeline_2_fu_227_m_axi_gmem1_0_ARPROT;
wire   [3:0] grp_quad_frame_remapper_Pipeline_2_fu_227_m_axi_gmem1_0_ARQOS;
wire   [3:0] grp_quad_frame_remapper_Pipeline_2_fu_227_m_axi_gmem1_0_ARREGION;
wire   [0:0] grp_quad_frame_remapper_Pipeline_2_fu_227_m_axi_gmem1_0_ARUSER;
wire    grp_quad_frame_remapper_Pipeline_2_fu_227_m_axi_gmem1_0_RREADY;
wire    grp_quad_frame_remapper_Pipeline_2_fu_227_m_axi_gmem1_0_BREADY;
wire   [8:0] grp_quad_frame_remapper_Pipeline_2_fu_227_line_buf_out_address0;
wire    grp_quad_frame_remapper_Pipeline_2_fu_227_line_buf_out_ce0;
wire    gmem0_0_AWREADY;
wire    gmem0_0_WREADY;
reg    gmem0_0_ARVALID;
wire    gmem0_0_ARREADY;
reg   [63:0] gmem0_0_ARADDR;
reg   [31:0] gmem0_0_ARLEN;
wire    gmem0_0_RVALID;
reg    gmem0_0_RREADY;
wire   [127:0] gmem0_0_RDATA;
wire   [10:0] gmem0_0_RFIFONUM;
wire    gmem0_0_BVALID;
reg    gmem1_0_AWVALID;
wire    gmem1_0_AWREADY;
reg   [63:0] gmem1_0_AWADDR;
reg   [31:0] gmem1_0_AWLEN;
reg    gmem1_0_WVALID;
wire    gmem1_0_WREADY;
reg   [127:0] gmem1_0_WDATA;
reg   [15:0] gmem1_0_WSTRB;
wire    gmem1_0_ARREADY;
wire    gmem1_0_RVALID;
wire   [127:0] gmem1_0_RDATA;
wire   [8:0] gmem1_0_RFIFONUM;
wire    gmem1_0_BVALID;
reg    gmem1_0_BREADY;
reg    grp_quad_frame_remapper_Pipeline_1_fu_189_ap_start_reg;
wire   [0:0] icmp_ln91_fu_272_p2;
wire    ap_CS_fsm_state27;
reg    grp_quad_frame_remapper_Pipeline_3_fu_194_ap_start_reg;
wire    ap_CS_fsm_state14;
wire    ap_CS_fsm_state15;
reg    grp_quad_frame_remapper_Pipeline_4_fu_202_ap_start_reg;
reg    grp_quad_frame_remapper_Pipeline_VITIS_LOOP_132_2_fu_207_ap_start_reg;
wire    ap_CS_fsm_state16;
wire    ap_CS_fsm_state17;
reg    grp_quad_frame_remapper_Pipeline_VITIS_LOOP_146_3_fu_213_ap_start_reg;
wire    ap_CS_fsm_state18;
reg    grp_quad_frame_remapper_Pipeline_7_fu_219_ap_start_reg;
wire    ap_CS_fsm_state20;
wire    ap_CS_fsm_state21;
reg    grp_quad_frame_remapper_Pipeline_2_fu_227_ap_start_reg;
wire    ap_CS_fsm_state29;
wire    ap_CS_fsm_state30;
wire  signed [63:0] sext_ln123_fu_433_p1;
wire  signed [63:0] sext_ln160_fu_443_p1;
wire  signed [63:0] sext_ln107_fu_462_p1;
reg    ap_block_state26;
reg   [22:0] phi_mul_fu_142;
reg   [10:0] y_fu_146;
wire   [63:0] zext_ln95_fu_288_p1;
wire   [9:0] trunc_ln91_fu_284_p1;
wire   [9:0] add_ln98_fu_303_p2;
wire   [0:0] icmp_ln102_fu_317_p2;
wire   [0:0] icmp_ln102_1_fu_323_p2;
wire   [8:0] trunc_ln117_fu_335_p1;
wire   [11:0] tmp_fu_338_p3;
wire   [9:0] shl_ln117_fu_350_p2;
wire   [12:0] zext_ln117_fu_346_p1;
wire   [12:0] zext_ln117_2_fu_355_p1;
wire   [12:0] add_ln117_1_fu_359_p2;
wire   [12:0] add_ln117_fu_365_p2;
wire   [9:0] src_local_y_fu_371_p4;
wire   [10:0] zext_ln117_1_fu_381_p1;
wire   [10:0] add_ln120_fu_385_p2;
wire   [10:0] mul_ln123_fu_401_p0;
wire   [9:0] mul_ln123_fu_401_p1;
wire   [22:0] shl_ln_fu_407_p3;
wire   [63:0] zext_ln123_1_fu_414_p1;
wire   [63:0] add_ln123_fu_418_p2;
reg   [34:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
reg    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
wire    ap_ST_fsm_state11_blk;
wire    ap_ST_fsm_state12_blk;
wire    ap_ST_fsm_state13_blk;
wire    ap_ST_fsm_state14_blk;
reg    ap_block_state15_on_subcall_done;
reg    ap_ST_fsm_state15_blk;
wire    ap_ST_fsm_state16_blk;
reg    ap_ST_fsm_state17_blk;
wire    ap_ST_fsm_state18_blk;
reg    ap_ST_fsm_state19_blk;
wire    ap_ST_fsm_state20_blk;
reg    ap_ST_fsm_state21_blk;
wire    ap_ST_fsm_state22_blk;
wire    ap_ST_fsm_state23_blk;
wire    ap_ST_fsm_state24_blk;
wire    ap_ST_fsm_state25_blk;
reg    ap_ST_fsm_state26_blk;
reg    ap_ST_fsm_state27_blk;
reg    ap_ST_fsm_state28_blk;
wire    ap_ST_fsm_state29_blk;
reg    ap_ST_fsm_state30_blk;
wire    ap_ST_fsm_state31_blk;
wire    ap_ST_fsm_state32_blk;
wire    ap_ST_fsm_state33_blk;
wire    ap_ST_fsm_state34_blk;
reg    ap_ST_fsm_state35_blk;
wire   [18:0] mul_ln123_fu_401_p00;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 35'd1;
#0 grp_quad_frame_remapper_Pipeline_1_fu_189_ap_start_reg = 1'b0;
#0 grp_quad_frame_remapper_Pipeline_3_fu_194_ap_start_reg = 1'b0;
#0 grp_quad_frame_remapper_Pipeline_4_fu_202_ap_start_reg = 1'b0;
#0 grp_quad_frame_remapper_Pipeline_VITIS_LOOP_132_2_fu_207_ap_start_reg = 1'b0;
#0 grp_quad_frame_remapper_Pipeline_VITIS_LOOP_146_3_fu_213_ap_start_reg = 1'b0;
#0 grp_quad_frame_remapper_Pipeline_7_fu_219_ap_start_reg = 1'b0;
#0 grp_quad_frame_remapper_Pipeline_2_fu_227_ap_start_reg = 1'b0;
#0 phi_mul_fu_142 = 23'd0;
#0 y_fu_146 = 11'd0;
end

quad_frame_remapper_line_buf_in_RAM_1WNR_AUTO_1R1W #(
    .DataWidth( 128 ),
    .AddressRange( 360 ),
    .AddressWidth( 9 ))
line_buf_in_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(line_buf_in_address0),
    .ce0(line_buf_in_ce0),
    .we0(line_buf_in_we0),
    .d0(grp_quad_frame_remapper_Pipeline_3_fu_194_line_buf_in_d0),
    .q0(line_buf_in_q0),
    .address1(line_buf_in_address1),
    .ce1(line_buf_in_ce1),
    .q1(line_buf_in_q1)
);

quad_frame_remapper_line_buf_out_RAM_AUTO_1R1W #(
    .DataWidth( 128 ),
    .AddressRange( 360 ),
    .AddressWidth( 9 ))
line_buf_out_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(line_buf_out_address0),
    .ce0(line_buf_out_ce0),
    .we0(line_buf_out_we0),
    .d0(line_buf_out_d0),
    .q0(line_buf_out_q0)
);

quad_frame_remapper_quad_frame_remapper_Pipeline_1 grp_quad_frame_remapper_Pipeline_1_fu_189(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_quad_frame_remapper_Pipeline_1_fu_189_ap_start),
    .ap_done(grp_quad_frame_remapper_Pipeline_1_fu_189_ap_done),
    .ap_idle(grp_quad_frame_remapper_Pipeline_1_fu_189_ap_idle),
    .ap_ready(grp_quad_frame_remapper_Pipeline_1_fu_189_ap_ready),
    .line_buf_out_address0(grp_quad_frame_remapper_Pipeline_1_fu_189_line_buf_out_address0),
    .line_buf_out_ce0(grp_quad_frame_remapper_Pipeline_1_fu_189_line_buf_out_ce0),
    .line_buf_out_we0(grp_quad_frame_remapper_Pipeline_1_fu_189_line_buf_out_we0),
    .line_buf_out_d0(grp_quad_frame_remapper_Pipeline_1_fu_189_line_buf_out_d0)
);

quad_frame_remapper_quad_frame_remapper_Pipeline_3 grp_quad_frame_remapper_Pipeline_3_fu_194(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_quad_frame_remapper_Pipeline_3_fu_194_ap_start),
    .ap_done(grp_quad_frame_remapper_Pipeline_3_fu_194_ap_done),
    .ap_idle(grp_quad_frame_remapper_Pipeline_3_fu_194_ap_idle),
    .ap_ready(grp_quad_frame_remapper_Pipeline_3_fu_194_ap_ready),
    .m_axi_gmem0_0_AWVALID(grp_quad_frame_remapper_Pipeline_3_fu_194_m_axi_gmem0_0_AWVALID),
    .m_axi_gmem0_0_AWREADY(1'b0),
    .m_axi_gmem0_0_AWADDR(grp_quad_frame_remapper_Pipeline_3_fu_194_m_axi_gmem0_0_AWADDR),
    .m_axi_gmem0_0_AWID(grp_quad_frame_remapper_Pipeline_3_fu_194_m_axi_gmem0_0_AWID),
    .m_axi_gmem0_0_AWLEN(grp_quad_frame_remapper_Pipeline_3_fu_194_m_axi_gmem0_0_AWLEN),
    .m_axi_gmem0_0_AWSIZE(grp_quad_frame_remapper_Pipeline_3_fu_194_m_axi_gmem0_0_AWSIZE),
    .m_axi_gmem0_0_AWBURST(grp_quad_frame_remapper_Pipeline_3_fu_194_m_axi_gmem0_0_AWBURST),
    .m_axi_gmem0_0_AWLOCK(grp_quad_frame_remapper_Pipeline_3_fu_194_m_axi_gmem0_0_AWLOCK),
    .m_axi_gmem0_0_AWCACHE(grp_quad_frame_remapper_Pipeline_3_fu_194_m_axi_gmem0_0_AWCACHE),
    .m_axi_gmem0_0_AWPROT(grp_quad_frame_remapper_Pipeline_3_fu_194_m_axi_gmem0_0_AWPROT),
    .m_axi_gmem0_0_AWQOS(grp_quad_frame_remapper_Pipeline_3_fu_194_m_axi_gmem0_0_AWQOS),
    .m_axi_gmem0_0_AWREGION(grp_quad_frame_remapper_Pipeline_3_fu_194_m_axi_gmem0_0_AWREGION),
    .m_axi_gmem0_0_AWUSER(grp_quad_frame_remapper_Pipeline_3_fu_194_m_axi_gmem0_0_AWUSER),
    .m_axi_gmem0_0_WVALID(grp_quad_frame_remapper_Pipeline_3_fu_194_m_axi_gmem0_0_WVALID),
    .m_axi_gmem0_0_WREADY(1'b0),
    .m_axi_gmem0_0_WDATA(grp_quad_frame_remapper_Pipeline_3_fu_194_m_axi_gmem0_0_WDATA),
    .m_axi_gmem0_0_WSTRB(grp_quad_frame_remapper_Pipeline_3_fu_194_m_axi_gmem0_0_WSTRB),
    .m_axi_gmem0_0_WLAST(grp_quad_frame_remapper_Pipeline_3_fu_194_m_axi_gmem0_0_WLAST),
    .m_axi_gmem0_0_WID(grp_quad_frame_remapper_Pipeline_3_fu_194_m_axi_gmem0_0_WID),
    .m_axi_gmem0_0_WUSER(grp_quad_frame_remapper_Pipeline_3_fu_194_m_axi_gmem0_0_WUSER),
    .m_axi_gmem0_0_ARVALID(grp_quad_frame_remapper_Pipeline_3_fu_194_m_axi_gmem0_0_ARVALID),
    .m_axi_gmem0_0_ARREADY(gmem0_0_ARREADY),
    .m_axi_gmem0_0_ARADDR(grp_quad_frame_remapper_Pipeline_3_fu_194_m_axi_gmem0_0_ARADDR),
    .m_axi_gmem0_0_ARID(grp_quad_frame_remapper_Pipeline_3_fu_194_m_axi_gmem0_0_ARID),
    .m_axi_gmem0_0_ARLEN(grp_quad_frame_remapper_Pipeline_3_fu_194_m_axi_gmem0_0_ARLEN),
    .m_axi_gmem0_0_ARSIZE(grp_quad_frame_remapper_Pipeline_3_fu_194_m_axi_gmem0_0_ARSIZE),
    .m_axi_gmem0_0_ARBURST(grp_quad_frame_remapper_Pipeline_3_fu_194_m_axi_gmem0_0_ARBURST),
    .m_axi_gmem0_0_ARLOCK(grp_quad_frame_remapper_Pipeline_3_fu_194_m_axi_gmem0_0_ARLOCK),
    .m_axi_gmem0_0_ARCACHE(grp_quad_frame_remapper_Pipeline_3_fu_194_m_axi_gmem0_0_ARCACHE),
    .m_axi_gmem0_0_ARPROT(grp_quad_frame_remapper_Pipeline_3_fu_194_m_axi_gmem0_0_ARPROT),
    .m_axi_gmem0_0_ARQOS(grp_quad_frame_remapper_Pipeline_3_fu_194_m_axi_gmem0_0_ARQOS),
    .m_axi_gmem0_0_ARREGION(grp_quad_frame_remapper_Pipeline_3_fu_194_m_axi_gmem0_0_ARREGION),
    .m_axi_gmem0_0_ARUSER(grp_quad_frame_remapper_Pipeline_3_fu_194_m_axi_gmem0_0_ARUSER),
    .m_axi_gmem0_0_RVALID(gmem0_0_RVALID),
    .m_axi_gmem0_0_RREADY(grp_quad_frame_remapper_Pipeline_3_fu_194_m_axi_gmem0_0_RREADY),
    .m_axi_gmem0_0_RDATA(gmem0_0_RDATA),
    .m_axi_gmem0_0_RLAST(1'b0),
    .m_axi_gmem0_0_RID(1'd0),
    .m_axi_gmem0_0_RFIFONUM(gmem0_0_RFIFONUM),
    .m_axi_gmem0_0_RUSER(1'd0),
    .m_axi_gmem0_0_RRESP(2'd0),
    .m_axi_gmem0_0_BVALID(1'b0),
    .m_axi_gmem0_0_BREADY(grp_quad_frame_remapper_Pipeline_3_fu_194_m_axi_gmem0_0_BREADY),
    .m_axi_gmem0_0_BRESP(2'd0),
    .m_axi_gmem0_0_BID(1'd0),
    .m_axi_gmem0_0_BUSER(1'd0),
    .sext_ln123(trunc_ln1_reg_540),
    .line_buf_in_address0(grp_quad_frame_remapper_Pipeline_3_fu_194_line_buf_in_address0),
    .line_buf_in_ce0(grp_quad_frame_remapper_Pipeline_3_fu_194_line_buf_in_ce0),
    .line_buf_in_we0(grp_quad_frame_remapper_Pipeline_3_fu_194_line_buf_in_we0),
    .line_buf_in_d0(grp_quad_frame_remapper_Pipeline_3_fu_194_line_buf_in_d0)
);

quad_frame_remapper_quad_frame_remapper_Pipeline_4 grp_quad_frame_remapper_Pipeline_4_fu_202(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_quad_frame_remapper_Pipeline_4_fu_202_ap_start),
    .ap_done(grp_quad_frame_remapper_Pipeline_4_fu_202_ap_done),
    .ap_idle(grp_quad_frame_remapper_Pipeline_4_fu_202_ap_idle),
    .ap_ready(grp_quad_frame_remapper_Pipeline_4_fu_202_ap_ready),
    .line_buf_out_address0(grp_quad_frame_remapper_Pipeline_4_fu_202_line_buf_out_address0),
    .line_buf_out_ce0(grp_quad_frame_remapper_Pipeline_4_fu_202_line_buf_out_ce0),
    .line_buf_out_we0(grp_quad_frame_remapper_Pipeline_4_fu_202_line_buf_out_we0),
    .line_buf_out_d0(grp_quad_frame_remapper_Pipeline_4_fu_202_line_buf_out_d0)
);

quad_frame_remapper_quad_frame_remapper_Pipeline_VITIS_LOOP_132_2 grp_quad_frame_remapper_Pipeline_VITIS_LOOP_132_2_fu_207(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_quad_frame_remapper_Pipeline_VITIS_LOOP_132_2_fu_207_ap_start),
    .ap_done(grp_quad_frame_remapper_Pipeline_VITIS_LOOP_132_2_fu_207_ap_done),
    .ap_idle(grp_quad_frame_remapper_Pipeline_VITIS_LOOP_132_2_fu_207_ap_idle),
    .ap_ready(grp_quad_frame_remapper_Pipeline_VITIS_LOOP_132_2_fu_207_ap_ready),
    .line_buf_in_address0(grp_quad_frame_remapper_Pipeline_VITIS_LOOP_132_2_fu_207_line_buf_in_address0),
    .line_buf_in_ce0(grp_quad_frame_remapper_Pipeline_VITIS_LOOP_132_2_fu_207_line_buf_in_ce0),
    .line_buf_in_q0(line_buf_in_q0),
    .line_buf_in_address1(grp_quad_frame_remapper_Pipeline_VITIS_LOOP_132_2_fu_207_line_buf_in_address1),
    .line_buf_in_ce1(grp_quad_frame_remapper_Pipeline_VITIS_LOOP_132_2_fu_207_line_buf_in_ce1),
    .line_buf_in_q1(line_buf_in_q1),
    .line_buf_out_address0(grp_quad_frame_remapper_Pipeline_VITIS_LOOP_132_2_fu_207_line_buf_out_address0),
    .line_buf_out_ce0(grp_quad_frame_remapper_Pipeline_VITIS_LOOP_132_2_fu_207_line_buf_out_ce0),
    .line_buf_out_we0(grp_quad_frame_remapper_Pipeline_VITIS_LOOP_132_2_fu_207_line_buf_out_we0),
    .line_buf_out_d0(grp_quad_frame_remapper_Pipeline_VITIS_LOOP_132_2_fu_207_line_buf_out_d0)
);

quad_frame_remapper_quad_frame_remapper_Pipeline_VITIS_LOOP_146_3 grp_quad_frame_remapper_Pipeline_VITIS_LOOP_146_3_fu_213(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_quad_frame_remapper_Pipeline_VITIS_LOOP_146_3_fu_213_ap_start),
    .ap_done(grp_quad_frame_remapper_Pipeline_VITIS_LOOP_146_3_fu_213_ap_done),
    .ap_idle(grp_quad_frame_remapper_Pipeline_VITIS_LOOP_146_3_fu_213_ap_idle),
    .ap_ready(grp_quad_frame_remapper_Pipeline_VITIS_LOOP_146_3_fu_213_ap_ready),
    .line_buf_in_address0(grp_quad_frame_remapper_Pipeline_VITIS_LOOP_146_3_fu_213_line_buf_in_address0),
    .line_buf_in_ce0(grp_quad_frame_remapper_Pipeline_VITIS_LOOP_146_3_fu_213_line_buf_in_ce0),
    .line_buf_in_q0(line_buf_in_q0),
    .line_buf_in_address1(grp_quad_frame_remapper_Pipeline_VITIS_LOOP_146_3_fu_213_line_buf_in_address1),
    .line_buf_in_ce1(grp_quad_frame_remapper_Pipeline_VITIS_LOOP_146_3_fu_213_line_buf_in_ce1),
    .line_buf_in_q1(line_buf_in_q1),
    .line_buf_out_address0(grp_quad_frame_remapper_Pipeline_VITIS_LOOP_146_3_fu_213_line_buf_out_address0),
    .line_buf_out_ce0(grp_quad_frame_remapper_Pipeline_VITIS_LOOP_146_3_fu_213_line_buf_out_ce0),
    .line_buf_out_we0(grp_quad_frame_remapper_Pipeline_VITIS_LOOP_146_3_fu_213_line_buf_out_we0),
    .line_buf_out_d0(grp_quad_frame_remapper_Pipeline_VITIS_LOOP_146_3_fu_213_line_buf_out_d0)
);

quad_frame_remapper_quad_frame_remapper_Pipeline_7 grp_quad_frame_remapper_Pipeline_7_fu_219(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_quad_frame_remapper_Pipeline_7_fu_219_ap_start),
    .ap_done(grp_quad_frame_remapper_Pipeline_7_fu_219_ap_done),
    .ap_idle(grp_quad_frame_remapper_Pipeline_7_fu_219_ap_idle),
    .ap_ready(grp_quad_frame_remapper_Pipeline_7_fu_219_ap_ready),
    .m_axi_gmem1_0_AWVALID(grp_quad_frame_remapper_Pipeline_7_fu_219_m_axi_gmem1_0_AWVALID),
    .m_axi_gmem1_0_AWREADY(gmem1_0_AWREADY),
    .m_axi_gmem1_0_AWADDR(grp_quad_frame_remapper_Pipeline_7_fu_219_m_axi_gmem1_0_AWADDR),
    .m_axi_gmem1_0_AWID(grp_quad_frame_remapper_Pipeline_7_fu_219_m_axi_gmem1_0_AWID),
    .m_axi_gmem1_0_AWLEN(grp_quad_frame_remapper_Pipeline_7_fu_219_m_axi_gmem1_0_AWLEN),
    .m_axi_gmem1_0_AWSIZE(grp_quad_frame_remapper_Pipeline_7_fu_219_m_axi_gmem1_0_AWSIZE),
    .m_axi_gmem1_0_AWBURST(grp_quad_frame_remapper_Pipeline_7_fu_219_m_axi_gmem1_0_AWBURST),
    .m_axi_gmem1_0_AWLOCK(grp_quad_frame_remapper_Pipeline_7_fu_219_m_axi_gmem1_0_AWLOCK),
    .m_axi_gmem1_0_AWCACHE(grp_quad_frame_remapper_Pipeline_7_fu_219_m_axi_gmem1_0_AWCACHE),
    .m_axi_gmem1_0_AWPROT(grp_quad_frame_remapper_Pipeline_7_fu_219_m_axi_gmem1_0_AWPROT),
    .m_axi_gmem1_0_AWQOS(grp_quad_frame_remapper_Pipeline_7_fu_219_m_axi_gmem1_0_AWQOS),
    .m_axi_gmem1_0_AWREGION(grp_quad_frame_remapper_Pipeline_7_fu_219_m_axi_gmem1_0_AWREGION),
    .m_axi_gmem1_0_AWUSER(grp_quad_frame_remapper_Pipeline_7_fu_219_m_axi_gmem1_0_AWUSER),
    .m_axi_gmem1_0_WVALID(grp_quad_frame_remapper_Pipeline_7_fu_219_m_axi_gmem1_0_WVALID),
    .m_axi_gmem1_0_WREADY(gmem1_0_WREADY),
    .m_axi_gmem1_0_WDATA(grp_quad_frame_remapper_Pipeline_7_fu_219_m_axi_gmem1_0_WDATA),
    .m_axi_gmem1_0_WSTRB(grp_quad_frame_remapper_Pipeline_7_fu_219_m_axi_gmem1_0_WSTRB),
    .m_axi_gmem1_0_WLAST(grp_quad_frame_remapper_Pipeline_7_fu_219_m_axi_gmem1_0_WLAST),
    .m_axi_gmem1_0_WID(grp_quad_frame_remapper_Pipeline_7_fu_219_m_axi_gmem1_0_WID),
    .m_axi_gmem1_0_WUSER(grp_quad_frame_remapper_Pipeline_7_fu_219_m_axi_gmem1_0_WUSER),
    .m_axi_gmem1_0_ARVALID(grp_quad_frame_remapper_Pipeline_7_fu_219_m_axi_gmem1_0_ARVALID),
    .m_axi_gmem1_0_ARREADY(1'b0),
    .m_axi_gmem1_0_ARADDR(grp_quad_frame_remapper_Pipeline_7_fu_219_m_axi_gmem1_0_ARADDR),
    .m_axi_gmem1_0_ARID(grp_quad_frame_remapper_Pipeline_7_fu_219_m_axi_gmem1_0_ARID),
    .m_axi_gmem1_0_ARLEN(grp_quad_frame_remapper_Pipeline_7_fu_219_m_axi_gmem1_0_ARLEN),
    .m_axi_gmem1_0_ARSIZE(grp_quad_frame_remapper_Pipeline_7_fu_219_m_axi_gmem1_0_ARSIZE),
    .m_axi_gmem1_0_ARBURST(grp_quad_frame_remapper_Pipeline_7_fu_219_m_axi_gmem1_0_ARBURST),
    .m_axi_gmem1_0_ARLOCK(grp_quad_frame_remapper_Pipeline_7_fu_219_m_axi_gmem1_0_ARLOCK),
    .m_axi_gmem1_0_ARCACHE(grp_quad_frame_remapper_Pipeline_7_fu_219_m_axi_gmem1_0_ARCACHE),
    .m_axi_gmem1_0_ARPROT(grp_quad_frame_remapper_Pipeline_7_fu_219_m_axi_gmem1_0_ARPROT),
    .m_axi_gmem1_0_ARQOS(grp_quad_frame_remapper_Pipeline_7_fu_219_m_axi_gmem1_0_ARQOS),
    .m_axi_gmem1_0_ARREGION(grp_quad_frame_remapper_Pipeline_7_fu_219_m_axi_gmem1_0_ARREGION),
    .m_axi_gmem1_0_ARUSER(grp_quad_frame_remapper_Pipeline_7_fu_219_m_axi_gmem1_0_ARUSER),
    .m_axi_gmem1_0_RVALID(1'b0),
    .m_axi_gmem1_0_RREADY(grp_quad_frame_remapper_Pipeline_7_fu_219_m_axi_gmem1_0_RREADY),
    .m_axi_gmem1_0_RDATA(128'd0),
    .m_axi_gmem1_0_RLAST(1'b0),
    .m_axi_gmem1_0_RID(1'd0),
    .m_axi_gmem1_0_RFIFONUM(9'd0),
    .m_axi_gmem1_0_RUSER(1'd0),
    .m_axi_gmem1_0_RRESP(2'd0),
    .m_axi_gmem1_0_BVALID(gmem1_0_BVALID),
    .m_axi_gmem1_0_BREADY(grp_quad_frame_remapper_Pipeline_7_fu_219_m_axi_gmem1_0_BREADY),
    .m_axi_gmem1_0_BRESP(2'd0),
    .m_axi_gmem1_0_BID(1'd0),
    .m_axi_gmem1_0_BUSER(1'd0),
    .sext_ln160(reg_244),
    .line_buf_out_address0(grp_quad_frame_remapper_Pipeline_7_fu_219_line_buf_out_address0),
    .line_buf_out_ce0(grp_quad_frame_remapper_Pipeline_7_fu_219_line_buf_out_ce0),
    .line_buf_out_q0(line_buf_out_q0)
);

quad_frame_remapper_quad_frame_remapper_Pipeline_2 grp_quad_frame_remapper_Pipeline_2_fu_227(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_quad_frame_remapper_Pipeline_2_fu_227_ap_start),
    .ap_done(grp_quad_frame_remapper_Pipeline_2_fu_227_ap_done),
    .ap_idle(grp_quad_frame_remapper_Pipeline_2_fu_227_ap_idle),
    .ap_ready(grp_quad_frame_remapper_Pipeline_2_fu_227_ap_ready),
    .m_axi_gmem1_0_AWVALID(grp_quad_frame_remapper_Pipeline_2_fu_227_m_axi_gmem1_0_AWVALID),
    .m_axi_gmem1_0_AWREADY(gmem1_0_AWREADY),
    .m_axi_gmem1_0_AWADDR(grp_quad_frame_remapper_Pipeline_2_fu_227_m_axi_gmem1_0_AWADDR),
    .m_axi_gmem1_0_AWID(grp_quad_frame_remapper_Pipeline_2_fu_227_m_axi_gmem1_0_AWID),
    .m_axi_gmem1_0_AWLEN(grp_quad_frame_remapper_Pipeline_2_fu_227_m_axi_gmem1_0_AWLEN),
    .m_axi_gmem1_0_AWSIZE(grp_quad_frame_remapper_Pipeline_2_fu_227_m_axi_gmem1_0_AWSIZE),
    .m_axi_gmem1_0_AWBURST(grp_quad_frame_remapper_Pipeline_2_fu_227_m_axi_gmem1_0_AWBURST),
    .m_axi_gmem1_0_AWLOCK(grp_quad_frame_remapper_Pipeline_2_fu_227_m_axi_gmem1_0_AWLOCK),
    .m_axi_gmem1_0_AWCACHE(grp_quad_frame_remapper_Pipeline_2_fu_227_m_axi_gmem1_0_AWCACHE),
    .m_axi_gmem1_0_AWPROT(grp_quad_frame_remapper_Pipeline_2_fu_227_m_axi_gmem1_0_AWPROT),
    .m_axi_gmem1_0_AWQOS(grp_quad_frame_remapper_Pipeline_2_fu_227_m_axi_gmem1_0_AWQOS),
    .m_axi_gmem1_0_AWREGION(grp_quad_frame_remapper_Pipeline_2_fu_227_m_axi_gmem1_0_AWREGION),
    .m_axi_gmem1_0_AWUSER(grp_quad_frame_remapper_Pipeline_2_fu_227_m_axi_gmem1_0_AWUSER),
    .m_axi_gmem1_0_WVALID(grp_quad_frame_remapper_Pipeline_2_fu_227_m_axi_gmem1_0_WVALID),
    .m_axi_gmem1_0_WREADY(gmem1_0_WREADY),
    .m_axi_gmem1_0_WDATA(grp_quad_frame_remapper_Pipeline_2_fu_227_m_axi_gmem1_0_WDATA),
    .m_axi_gmem1_0_WSTRB(grp_quad_frame_remapper_Pipeline_2_fu_227_m_axi_gmem1_0_WSTRB),
    .m_axi_gmem1_0_WLAST(grp_quad_frame_remapper_Pipeline_2_fu_227_m_axi_gmem1_0_WLAST),
    .m_axi_gmem1_0_WID(grp_quad_frame_remapper_Pipeline_2_fu_227_m_axi_gmem1_0_WID),
    .m_axi_gmem1_0_WUSER(grp_quad_frame_remapper_Pipeline_2_fu_227_m_axi_gmem1_0_WUSER),
    .m_axi_gmem1_0_ARVALID(grp_quad_frame_remapper_Pipeline_2_fu_227_m_axi_gmem1_0_ARVALID),
    .m_axi_gmem1_0_ARREADY(1'b0),
    .m_axi_gmem1_0_ARADDR(grp_quad_frame_remapper_Pipeline_2_fu_227_m_axi_gmem1_0_ARADDR),
    .m_axi_gmem1_0_ARID(grp_quad_frame_remapper_Pipeline_2_fu_227_m_axi_gmem1_0_ARID),
    .m_axi_gmem1_0_ARLEN(grp_quad_frame_remapper_Pipeline_2_fu_227_m_axi_gmem1_0_ARLEN),
    .m_axi_gmem1_0_ARSIZE(grp_quad_frame_remapper_Pipeline_2_fu_227_m_axi_gmem1_0_ARSIZE),
    .m_axi_gmem1_0_ARBURST(grp_quad_frame_remapper_Pipeline_2_fu_227_m_axi_gmem1_0_ARBURST),
    .m_axi_gmem1_0_ARLOCK(grp_quad_frame_remapper_Pipeline_2_fu_227_m_axi_gmem1_0_ARLOCK),
    .m_axi_gmem1_0_ARCACHE(grp_quad_frame_remapper_Pipeline_2_fu_227_m_axi_gmem1_0_ARCACHE),
    .m_axi_gmem1_0_ARPROT(grp_quad_frame_remapper_Pipeline_2_fu_227_m_axi_gmem1_0_ARPROT),
    .m_axi_gmem1_0_ARQOS(grp_quad_frame_remapper_Pipeline_2_fu_227_m_axi_gmem1_0_ARQOS),
    .m_axi_gmem1_0_ARREGION(grp_quad_frame_remapper_Pipeline_2_fu_227_m_axi_gmem1_0_ARREGION),
    .m_axi_gmem1_0_ARUSER(grp_quad_frame_remapper_Pipeline_2_fu_227_m_axi_gmem1_0_ARUSER),
    .m_axi_gmem1_0_RVALID(1'b0),
    .m_axi_gmem1_0_RREADY(grp_quad_frame_remapper_Pipeline_2_fu_227_m_axi_gmem1_0_RREADY),
    .m_axi_gmem1_0_RDATA(128'd0),
    .m_axi_gmem1_0_RLAST(1'b0),
    .m_axi_gmem1_0_RID(1'd0),
    .m_axi_gmem1_0_RFIFONUM(9'd0),
    .m_axi_gmem1_0_RUSER(1'd0),
    .m_axi_gmem1_0_RRESP(2'd0),
    .m_axi_gmem1_0_BVALID(gmem1_0_BVALID),
    .m_axi_gmem1_0_BREADY(grp_quad_frame_remapper_Pipeline_2_fu_227_m_axi_gmem1_0_BREADY),
    .m_axi_gmem1_0_BRESP(2'd0),
    .m_axi_gmem1_0_BID(1'd0),
    .m_axi_gmem1_0_BUSER(1'd0),
    .sext_ln107(reg_244),
    .line_buf_out_address0(grp_quad_frame_remapper_Pipeline_2_fu_227_line_buf_out_address0),
    .line_buf_out_ce0(grp_quad_frame_remapper_Pipeline_2_fu_227_line_buf_out_ce0),
    .line_buf_out_q0(line_buf_out_q0)
);

quad_frame_remapper_control_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CONTROL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CONTROL_DATA_WIDTH ))
control_s_axi_U(
    .AWVALID(s_axi_control_AWVALID),
    .AWREADY(s_axi_control_AWREADY),
    .AWADDR(s_axi_control_AWADDR),
    .WVALID(s_axi_control_WVALID),
    .WREADY(s_axi_control_WREADY),
    .WDATA(s_axi_control_WDATA),
    .WSTRB(s_axi_control_WSTRB),
    .ARVALID(s_axi_control_ARVALID),
    .ARREADY(s_axi_control_ARREADY),
    .ARADDR(s_axi_control_ARADDR),
    .RVALID(s_axi_control_RVALID),
    .RREADY(s_axi_control_RREADY),
    .RDATA(s_axi_control_RDATA),
    .RRESP(s_axi_control_RRESP),
    .BVALID(s_axi_control_BVALID),
    .BREADY(s_axi_control_BREADY),
    .BRESP(s_axi_control_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .src(src),
    .dst(dst),
    .size_in_16bytes(size_in_16bytes),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_idle(ap_idle)
);

quad_frame_remapper_gmem0_m_axi #(
    .CONSERVATIVE( 1 ),
    .USER_MAXREQS( 7 ),
    .MAX_READ_BURST_LENGTH( 256 ),
    .MAX_WRITE_BURST_LENGTH( 16 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_GMEM0_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_GMEM0_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_GMEM0_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_GMEM0_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_GMEM0_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_GMEM0_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_GMEM0_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_GMEM0_BUSER_WIDTH ),
    .C_USER_VALUE( C_M_AXI_GMEM0_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_GMEM0_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_GMEM0_CACHE_VALUE ),
    .CH0_NUM_READ_OUTSTANDING( 4 ),
    .CH0_NUM_WRITE_OUTSTANDING( 16 ),
    .CH0_USER_RFIFONUM_WIDTH( 11 ),
    .CH0_USER_DW( 128 ),
    .CH0_USER_AW( 64 ),
    .NUM_READ_OUTSTANDING( 4 ),
    .NUM_WRITE_OUTSTANDING( 0 ))
gmem0_m_axi_U(
    .AWVALID(m_axi_gmem0_AWVALID),
    .AWREADY(m_axi_gmem0_AWREADY),
    .AWADDR(m_axi_gmem0_AWADDR),
    .AWID(m_axi_gmem0_AWID),
    .AWLEN(m_axi_gmem0_AWLEN),
    .AWSIZE(m_axi_gmem0_AWSIZE),
    .AWBURST(m_axi_gmem0_AWBURST),
    .AWLOCK(m_axi_gmem0_AWLOCK),
    .AWCACHE(m_axi_gmem0_AWCACHE),
    .AWPROT(m_axi_gmem0_AWPROT),
    .AWQOS(m_axi_gmem0_AWQOS),
    .AWREGION(m_axi_gmem0_AWREGION),
    .AWUSER(m_axi_gmem0_AWUSER),
    .WVALID(m_axi_gmem0_WVALID),
    .WREADY(m_axi_gmem0_WREADY),
    .WDATA(m_axi_gmem0_WDATA),
    .WSTRB(m_axi_gmem0_WSTRB),
    .WLAST(m_axi_gmem0_WLAST),
    .WID(m_axi_gmem0_WID),
    .WUSER(m_axi_gmem0_WUSER),
    .ARVALID(m_axi_gmem0_ARVALID),
    .ARREADY(m_axi_gmem0_ARREADY),
    .ARADDR(m_axi_gmem0_ARADDR),
    .ARID(m_axi_gmem0_ARID),
    .ARLEN(m_axi_gmem0_ARLEN),
    .ARSIZE(m_axi_gmem0_ARSIZE),
    .ARBURST(m_axi_gmem0_ARBURST),
    .ARLOCK(m_axi_gmem0_ARLOCK),
    .ARCACHE(m_axi_gmem0_ARCACHE),
    .ARPROT(m_axi_gmem0_ARPROT),
    .ARQOS(m_axi_gmem0_ARQOS),
    .ARREGION(m_axi_gmem0_ARREGION),
    .ARUSER(m_axi_gmem0_ARUSER),
    .RVALID(m_axi_gmem0_RVALID),
    .RREADY(m_axi_gmem0_RREADY),
    .RDATA(m_axi_gmem0_RDATA),
    .RLAST(m_axi_gmem0_RLAST),
    .RID(m_axi_gmem0_RID),
    .RUSER(m_axi_gmem0_RUSER),
    .RRESP(m_axi_gmem0_RRESP),
    .BVALID(m_axi_gmem0_BVALID),
    .BREADY(m_axi_gmem0_BREADY),
    .BRESP(m_axi_gmem0_BRESP),
    .BID(m_axi_gmem0_BID),
    .BUSER(m_axi_gmem0_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_CH0_ARVALID(gmem0_0_ARVALID),
    .I_CH0_ARREADY(gmem0_0_ARREADY),
    .I_CH0_ARADDR(gmem0_0_ARADDR),
    .I_CH0_ARLEN(gmem0_0_ARLEN),
    .I_CH0_RVALID(gmem0_0_RVALID),
    .I_CH0_RREADY(gmem0_0_RREADY),
    .I_CH0_RDATA(gmem0_0_RDATA),
    .I_CH0_RFIFONUM(gmem0_0_RFIFONUM),
    .I_CH0_AWVALID(1'b0),
    .I_CH0_AWREADY(gmem0_0_AWREADY),
    .I_CH0_AWADDR(64'd0),
    .I_CH0_AWLEN(32'd0),
    .I_CH0_WVALID(1'b0),
    .I_CH0_WREADY(gmem0_0_WREADY),
    .I_CH0_WDATA(128'd0),
    .I_CH0_WSTRB(16'd0),
    .I_CH0_BVALID(gmem0_0_BVALID),
    .I_CH0_BREADY(1'b0)
);

quad_frame_remapper_gmem1_m_axi #(
    .CONSERVATIVE( 1 ),
    .USER_MAXREQS( 4 ),
    .MAX_READ_BURST_LENGTH( 16 ),
    .MAX_WRITE_BURST_LENGTH( 32 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_GMEM1_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_GMEM1_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_GMEM1_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_GMEM1_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_GMEM1_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_GMEM1_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_GMEM1_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_GMEM1_BUSER_WIDTH ),
    .C_USER_VALUE( C_M_AXI_GMEM1_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_GMEM1_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_GMEM1_CACHE_VALUE ),
    .CH0_NUM_READ_OUTSTANDING( 16 ),
    .CH0_NUM_WRITE_OUTSTANDING( 2 ),
    .CH0_USER_RFIFONUM_WIDTH( 9 ),
    .CH0_USER_DW( 128 ),
    .CH0_USER_AW( 64 ),
    .NUM_READ_OUTSTANDING( 0 ),
    .NUM_WRITE_OUTSTANDING( 2 ))
gmem1_m_axi_U(
    .AWVALID(m_axi_gmem1_AWVALID),
    .AWREADY(m_axi_gmem1_AWREADY),
    .AWADDR(m_axi_gmem1_AWADDR),
    .AWID(m_axi_gmem1_AWID),
    .AWLEN(m_axi_gmem1_AWLEN),
    .AWSIZE(m_axi_gmem1_AWSIZE),
    .AWBURST(m_axi_gmem1_AWBURST),
    .AWLOCK(m_axi_gmem1_AWLOCK),
    .AWCACHE(m_axi_gmem1_AWCACHE),
    .AWPROT(m_axi_gmem1_AWPROT),
    .AWQOS(m_axi_gmem1_AWQOS),
    .AWREGION(m_axi_gmem1_AWREGION),
    .AWUSER(m_axi_gmem1_AWUSER),
    .WVALID(m_axi_gmem1_WVALID),
    .WREADY(m_axi_gmem1_WREADY),
    .WDATA(m_axi_gmem1_WDATA),
    .WSTRB(m_axi_gmem1_WSTRB),
    .WLAST(m_axi_gmem1_WLAST),
    .WID(m_axi_gmem1_WID),
    .WUSER(m_axi_gmem1_WUSER),
    .ARVALID(m_axi_gmem1_ARVALID),
    .ARREADY(m_axi_gmem1_ARREADY),
    .ARADDR(m_axi_gmem1_ARADDR),
    .ARID(m_axi_gmem1_ARID),
    .ARLEN(m_axi_gmem1_ARLEN),
    .ARSIZE(m_axi_gmem1_ARSIZE),
    .ARBURST(m_axi_gmem1_ARBURST),
    .ARLOCK(m_axi_gmem1_ARLOCK),
    .ARCACHE(m_axi_gmem1_ARCACHE),
    .ARPROT(m_axi_gmem1_ARPROT),
    .ARQOS(m_axi_gmem1_ARQOS),
    .ARREGION(m_axi_gmem1_ARREGION),
    .ARUSER(m_axi_gmem1_ARUSER),
    .RVALID(m_axi_gmem1_RVALID),
    .RREADY(m_axi_gmem1_RREADY),
    .RDATA(m_axi_gmem1_RDATA),
    .RLAST(m_axi_gmem1_RLAST),
    .RID(m_axi_gmem1_RID),
    .RUSER(m_axi_gmem1_RUSER),
    .RRESP(m_axi_gmem1_RRESP),
    .BVALID(m_axi_gmem1_BVALID),
    .BREADY(m_axi_gmem1_BREADY),
    .BRESP(m_axi_gmem1_BRESP),
    .BID(m_axi_gmem1_BID),
    .BUSER(m_axi_gmem1_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_CH0_ARVALID(1'b0),
    .I_CH0_ARREADY(gmem1_0_ARREADY),
    .I_CH0_ARADDR(64'd0),
    .I_CH0_ARLEN(32'd0),
    .I_CH0_RVALID(gmem1_0_RVALID),
    .I_CH0_RREADY(1'b0),
    .I_CH0_RDATA(gmem1_0_RDATA),
    .I_CH0_RFIFONUM(gmem1_0_RFIFONUM),
    .I_CH0_AWVALID(gmem1_0_AWVALID),
    .I_CH0_AWREADY(gmem1_0_AWREADY),
    .I_CH0_AWADDR(gmem1_0_AWADDR),
    .I_CH0_AWLEN(gmem1_0_AWLEN),
    .I_CH0_WVALID(gmem1_0_WVALID),
    .I_CH0_WREADY(gmem1_0_WREADY),
    .I_CH0_WDATA(gmem1_0_WDATA),
    .I_CH0_WSTRB(gmem1_0_WSTRB),
    .I_CH0_BVALID(gmem1_0_BVALID),
    .I_CH0_BREADY(gmem1_0_BREADY)
);

quad_frame_remapper_mul_11ns_10ns_19_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 11 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 19 ))
mul_11ns_10ns_19_1_1_U16(
    .din0(mul_ln123_fu_401_p0),
    .din1(mul_ln123_fu_401_p1),
    .dout(mul_ln123_fu_401_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_quad_frame_remapper_Pipeline_1_fu_189_ap_start_reg <= 1'b0;
    end else begin
        if (((icmp_ln91_fu_272_p2 == 1'd0) & (or_ln102_fu_329_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
            grp_quad_frame_remapper_Pipeline_1_fu_189_ap_start_reg <= 1'b1;
        end else if ((grp_quad_frame_remapper_Pipeline_1_fu_189_ap_ready == 1'b1)) begin
            grp_quad_frame_remapper_Pipeline_1_fu_189_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_quad_frame_remapper_Pipeline_2_fu_227_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state29)) begin
            grp_quad_frame_remapper_Pipeline_2_fu_227_ap_start_reg <= 1'b1;
        end else if ((grp_quad_frame_remapper_Pipeline_2_fu_227_ap_ready == 1'b1)) begin
            grp_quad_frame_remapper_Pipeline_2_fu_227_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_quad_frame_remapper_Pipeline_3_fu_194_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state14)) begin
            grp_quad_frame_remapper_Pipeline_3_fu_194_ap_start_reg <= 1'b1;
        end else if ((grp_quad_frame_remapper_Pipeline_3_fu_194_ap_ready == 1'b1)) begin
            grp_quad_frame_remapper_Pipeline_3_fu_194_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_quad_frame_remapper_Pipeline_4_fu_202_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state14)) begin
            grp_quad_frame_remapper_Pipeline_4_fu_202_ap_start_reg <= 1'b1;
        end else if ((grp_quad_frame_remapper_Pipeline_4_fu_202_ap_ready == 1'b1)) begin
            grp_quad_frame_remapper_Pipeline_4_fu_202_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_quad_frame_remapper_Pipeline_7_fu_219_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state20)) begin
            grp_quad_frame_remapper_Pipeline_7_fu_219_ap_start_reg <= 1'b1;
        end else if ((grp_quad_frame_remapper_Pipeline_7_fu_219_ap_ready == 1'b1)) begin
            grp_quad_frame_remapper_Pipeline_7_fu_219_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_quad_frame_remapper_Pipeline_VITIS_LOOP_132_2_fu_207_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state16)) begin
            grp_quad_frame_remapper_Pipeline_VITIS_LOOP_132_2_fu_207_ap_start_reg <= 1'b1;
        end else if ((grp_quad_frame_remapper_Pipeline_VITIS_LOOP_132_2_fu_207_ap_ready == 1'b1)) begin
            grp_quad_frame_remapper_Pipeline_VITIS_LOOP_132_2_fu_207_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_quad_frame_remapper_Pipeline_VITIS_LOOP_146_3_fu_213_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state18)) begin
            grp_quad_frame_remapper_Pipeline_VITIS_LOOP_146_3_fu_213_ap_start_reg <= 1'b1;
        end else if ((grp_quad_frame_remapper_Pipeline_VITIS_LOOP_146_3_fu_213_ap_ready == 1'b1)) begin
            grp_quad_frame_remapper_Pipeline_VITIS_LOOP_146_3_fu_213_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        phi_mul_fu_142 <= 23'd0;
    end else if (((1'b0 == ap_block_state26) & (1'b1 == ap_CS_fsm_state26))) begin
        phi_mul_fu_142 <= add_ln91_reg_497;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        y_fu_146 <= 11'd0;
    end else if (((1'b0 == ap_block_state26) & (1'b1 == ap_CS_fsm_state26))) begin
        y_fu_146 <= y_2_reg_505;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        add_ln91_reg_497 <= add_ln91_fu_266_p2;
        add_ln95_reg_510 <= add_ln95_fu_292_p2;
        is_bottom_reg_515 <= is_bottom_fu_297_p2;
        local_y_reg_520 <= local_y_fu_309_p3;
        or_ln102_reg_526 <= or_ln102_fu_329_p2;
        y_2_reg_505 <= y_2_fu_278_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        dst_read_reg_487 <= dst;
        src_read_reg_492 <= src;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        mul_ln123_reg_535 <= mul_ln123_fu_401_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state28))) begin
        reg_244 <= {{add_ln95_reg_510[63:4]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        src_y_reg_530 <= src_y_fu_391_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        trunc_ln1_reg_540 <= {{add_ln123_fu_418_p2[63:4]}};
    end
end

assign ap_ST_fsm_state10_blk = 1'b0;

assign ap_ST_fsm_state11_blk = 1'b0;

assign ap_ST_fsm_state12_blk = 1'b0;

assign ap_ST_fsm_state13_blk = 1'b0;

assign ap_ST_fsm_state14_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_block_state15_on_subcall_done)) begin
        ap_ST_fsm_state15_blk = 1'b1;
    end else begin
        ap_ST_fsm_state15_blk = 1'b0;
    end
end

assign ap_ST_fsm_state16_blk = 1'b0;

always @ (*) begin
    if ((grp_quad_frame_remapper_Pipeline_VITIS_LOOP_132_2_fu_207_ap_done == 1'b0)) begin
        ap_ST_fsm_state17_blk = 1'b1;
    end else begin
        ap_ST_fsm_state17_blk = 1'b0;
    end
end

assign ap_ST_fsm_state18_blk = 1'b0;

always @ (*) begin
    if (((gmem1_0_AWREADY == 1'b0) | (grp_quad_frame_remapper_Pipeline_VITIS_LOOP_146_3_fu_213_ap_done == 1'b0))) begin
        ap_ST_fsm_state19_blk = 1'b1;
    end else begin
        ap_ST_fsm_state19_blk = 1'b0;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state20_blk = 1'b0;

always @ (*) begin
    if ((grp_quad_frame_remapper_Pipeline_7_fu_219_ap_done == 1'b0)) begin
        ap_ST_fsm_state21_blk = 1'b1;
    end else begin
        ap_ST_fsm_state21_blk = 1'b0;
    end
end

assign ap_ST_fsm_state22_blk = 1'b0;

assign ap_ST_fsm_state23_blk = 1'b0;

assign ap_ST_fsm_state24_blk = 1'b0;

assign ap_ST_fsm_state25_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_block_state26)) begin
        ap_ST_fsm_state26_blk = 1'b1;
    end else begin
        ap_ST_fsm_state26_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_quad_frame_remapper_Pipeline_1_fu_189_ap_done == 1'b0)) begin
        ap_ST_fsm_state27_blk = 1'b1;
    end else begin
        ap_ST_fsm_state27_blk = 1'b0;
    end
end

always @ (*) begin
    if ((gmem1_0_AWREADY == 1'b0)) begin
        ap_ST_fsm_state28_blk = 1'b1;
    end else begin
        ap_ST_fsm_state28_blk = 1'b0;
    end
end

assign ap_ST_fsm_state29_blk = 1'b0;

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if ((grp_quad_frame_remapper_Pipeline_2_fu_227_ap_done == 1'b0)) begin
        ap_ST_fsm_state30_blk = 1'b1;
    end else begin
        ap_ST_fsm_state30_blk = 1'b0;
    end
end

assign ap_ST_fsm_state31_blk = 1'b0;

assign ap_ST_fsm_state32_blk = 1'b0;

assign ap_ST_fsm_state33_blk = 1'b0;

assign ap_ST_fsm_state34_blk = 1'b0;

always @ (*) begin
    if ((gmem1_0_BVALID == 1'b0)) begin
        ap_ST_fsm_state35_blk = 1'b1;
    end else begin
        ap_ST_fsm_state35_blk = 1'b0;
    end
end

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

always @ (*) begin
    if ((gmem0_0_ARREADY == 1'b0)) begin
        ap_ST_fsm_state6_blk = 1'b1;
    end else begin
        ap_ST_fsm_state6_blk = 1'b0;
    end
end

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if (((icmp_ln91_fu_272_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln91_fu_272_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((gmem0_0_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state6))) begin
        gmem0_0_ARADDR = sext_ln123_fu_433_p1;
    end else if (((1'b1 == ap_CS_fsm_state15) | (1'b1 == ap_CS_fsm_state14))) begin
        gmem0_0_ARADDR = grp_quad_frame_remapper_Pipeline_3_fu_194_m_axi_gmem0_0_ARADDR;
    end else begin
        gmem0_0_ARADDR = 'bx;
    end
end

always @ (*) begin
    if (((gmem0_0_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state6))) begin
        gmem0_0_ARLEN = 64'd360;
    end else if (((1'b1 == ap_CS_fsm_state15) | (1'b1 == ap_CS_fsm_state14))) begin
        gmem0_0_ARLEN = grp_quad_frame_remapper_Pipeline_3_fu_194_m_axi_gmem0_0_ARLEN;
    end else begin
        gmem0_0_ARLEN = 'bx;
    end
end

always @ (*) begin
    if (((gmem0_0_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state6))) begin
        gmem0_0_ARVALID = 1'b1;
    end else if (((1'b1 == ap_CS_fsm_state15) | (1'b1 == ap_CS_fsm_state14))) begin
        gmem0_0_ARVALID = grp_quad_frame_remapper_Pipeline_3_fu_194_m_axi_gmem0_0_ARVALID;
    end else begin
        gmem0_0_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state15) | (1'b1 == ap_CS_fsm_state14))) begin
        gmem0_0_RREADY = grp_quad_frame_remapper_Pipeline_3_fu_194_m_axi_gmem0_0_RREADY;
    end else begin
        gmem0_0_RREADY = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        gmem0_blk_n_AR = m_axi_gmem0_ARREADY;
    end else begin
        gmem0_blk_n_AR = 1'b1;
    end
end

always @ (*) begin
    if (((gmem1_0_AWREADY == 1'b1) & (1'b1 == ap_CS_fsm_state28))) begin
        gmem1_0_AWADDR = sext_ln107_fu_462_p1;
    end else if ((~((gmem1_0_AWREADY == 1'b0) | (grp_quad_frame_remapper_Pipeline_VITIS_LOOP_146_3_fu_213_ap_done == 1'b0)) & (1'b1 == ap_CS_fsm_state19))) begin
        gmem1_0_AWADDR = sext_ln160_fu_443_p1;
    end else if (((1'b1 == ap_CS_fsm_state30) | (1'b1 == ap_CS_fsm_state29))) begin
        gmem1_0_AWADDR = grp_quad_frame_remapper_Pipeline_2_fu_227_m_axi_gmem1_0_AWADDR;
    end else if (((1'b1 == ap_CS_fsm_state21) | (1'b1 == ap_CS_fsm_state20))) begin
        gmem1_0_AWADDR = grp_quad_frame_remapper_Pipeline_7_fu_219_m_axi_gmem1_0_AWADDR;
    end else begin
        gmem1_0_AWADDR = 'bx;
    end
end

always @ (*) begin
    if ((((gmem1_0_AWREADY == 1'b1) & (1'b1 == ap_CS_fsm_state28)) | (~((gmem1_0_AWREADY == 1'b0) | (grp_quad_frame_remapper_Pipeline_VITIS_LOOP_146_3_fu_213_ap_done == 1'b0)) & (1'b1 == ap_CS_fsm_state19)))) begin
        gmem1_0_AWLEN = 64'd360;
    end else if (((1'b1 == ap_CS_fsm_state30) | (1'b1 == ap_CS_fsm_state29))) begin
        gmem1_0_AWLEN = grp_quad_frame_remapper_Pipeline_2_fu_227_m_axi_gmem1_0_AWLEN;
    end else if (((1'b1 == ap_CS_fsm_state21) | (1'b1 == ap_CS_fsm_state20))) begin
        gmem1_0_AWLEN = grp_quad_frame_remapper_Pipeline_7_fu_219_m_axi_gmem1_0_AWLEN;
    end else begin
        gmem1_0_AWLEN = 'bx;
    end
end

always @ (*) begin
    if ((((gmem1_0_AWREADY == 1'b1) & (1'b1 == ap_CS_fsm_state28)) | (~((gmem1_0_AWREADY == 1'b0) | (grp_quad_frame_remapper_Pipeline_VITIS_LOOP_146_3_fu_213_ap_done == 1'b0)) & (1'b1 == ap_CS_fsm_state19)))) begin
        gmem1_0_AWVALID = 1'b1;
    end else if (((1'b1 == ap_CS_fsm_state30) | (1'b1 == ap_CS_fsm_state29))) begin
        gmem1_0_AWVALID = grp_quad_frame_remapper_Pipeline_2_fu_227_m_axi_gmem1_0_AWVALID;
    end else if (((1'b1 == ap_CS_fsm_state21) | (1'b1 == ap_CS_fsm_state20))) begin
        gmem1_0_AWVALID = grp_quad_frame_remapper_Pipeline_7_fu_219_m_axi_gmem1_0_AWVALID;
    end else begin
        gmem1_0_AWVALID = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_state26) & (1'b1 == ap_CS_fsm_state26) & (or_ln102_reg_526 == 1'd0)) | ((gmem1_0_BVALID == 1'b1) & (1'b1 == ap_CS_fsm_state35)))) begin
        gmem1_0_BREADY = 1'b1;
    end else if (((1'b1 == ap_CS_fsm_state30) | (1'b1 == ap_CS_fsm_state29))) begin
        gmem1_0_BREADY = grp_quad_frame_remapper_Pipeline_2_fu_227_m_axi_gmem1_0_BREADY;
    end else if (((1'b1 == ap_CS_fsm_state21) | (1'b1 == ap_CS_fsm_state20))) begin
        gmem1_0_BREADY = grp_quad_frame_remapper_Pipeline_7_fu_219_m_axi_gmem1_0_BREADY;
    end else begin
        gmem1_0_BREADY = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state30) | (1'b1 == ap_CS_fsm_state29))) begin
        gmem1_0_WDATA = grp_quad_frame_remapper_Pipeline_2_fu_227_m_axi_gmem1_0_WDATA;
    end else if (((1'b1 == ap_CS_fsm_state21) | (1'b1 == ap_CS_fsm_state20))) begin
        gmem1_0_WDATA = grp_quad_frame_remapper_Pipeline_7_fu_219_m_axi_gmem1_0_WDATA;
    end else begin
        gmem1_0_WDATA = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state30) | (1'b1 == ap_CS_fsm_state29))) begin
        gmem1_0_WSTRB = grp_quad_frame_remapper_Pipeline_2_fu_227_m_axi_gmem1_0_WSTRB;
    end else if (((1'b1 == ap_CS_fsm_state21) | (1'b1 == ap_CS_fsm_state20))) begin
        gmem1_0_WSTRB = grp_quad_frame_remapper_Pipeline_7_fu_219_m_axi_gmem1_0_WSTRB;
    end else begin
        gmem1_0_WSTRB = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state30) | (1'b1 == ap_CS_fsm_state29))) begin
        gmem1_0_WVALID = grp_quad_frame_remapper_Pipeline_2_fu_227_m_axi_gmem1_0_WVALID;
    end else if (((1'b1 == ap_CS_fsm_state21) | (1'b1 == ap_CS_fsm_state20))) begin
        gmem1_0_WVALID = grp_quad_frame_remapper_Pipeline_7_fu_219_m_axi_gmem1_0_WVALID;
    end else begin
        gmem1_0_WVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state19) | (1'b1 == ap_CS_fsm_state28))) begin
        gmem1_blk_n_AW = m_axi_gmem1_AWREADY;
    end else begin
        gmem1_blk_n_AW = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state35) | ((1'b1 == ap_CS_fsm_state26) & (or_ln102_reg_526 == 1'd0)))) begin
        gmem1_blk_n_B = m_axi_gmem1_BVALID;
    end else begin
        gmem1_blk_n_B = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state19)) begin
        line_buf_in_address0 = grp_quad_frame_remapper_Pipeline_VITIS_LOOP_146_3_fu_213_line_buf_in_address0;
    end else if ((1'b1 == ap_CS_fsm_state17)) begin
        line_buf_in_address0 = grp_quad_frame_remapper_Pipeline_VITIS_LOOP_132_2_fu_207_line_buf_in_address0;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        line_buf_in_address0 = grp_quad_frame_remapper_Pipeline_3_fu_194_line_buf_in_address0;
    end else begin
        line_buf_in_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state19)) begin
        line_buf_in_address1 = grp_quad_frame_remapper_Pipeline_VITIS_LOOP_146_3_fu_213_line_buf_in_address1;
    end else if ((1'b1 == ap_CS_fsm_state17)) begin
        line_buf_in_address1 = grp_quad_frame_remapper_Pipeline_VITIS_LOOP_132_2_fu_207_line_buf_in_address1;
    end else begin
        line_buf_in_address1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state19)) begin
        line_buf_in_ce0 = grp_quad_frame_remapper_Pipeline_VITIS_LOOP_146_3_fu_213_line_buf_in_ce0;
    end else if ((1'b1 == ap_CS_fsm_state17)) begin
        line_buf_in_ce0 = grp_quad_frame_remapper_Pipeline_VITIS_LOOP_132_2_fu_207_line_buf_in_ce0;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        line_buf_in_ce0 = grp_quad_frame_remapper_Pipeline_3_fu_194_line_buf_in_ce0;
    end else begin
        line_buf_in_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state19)) begin
        line_buf_in_ce1 = grp_quad_frame_remapper_Pipeline_VITIS_LOOP_146_3_fu_213_line_buf_in_ce1;
    end else if ((1'b1 == ap_CS_fsm_state17)) begin
        line_buf_in_ce1 = grp_quad_frame_remapper_Pipeline_VITIS_LOOP_132_2_fu_207_line_buf_in_ce1;
    end else begin
        line_buf_in_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        line_buf_in_we0 = grp_quad_frame_remapper_Pipeline_3_fu_194_line_buf_in_we0;
    end else begin
        line_buf_in_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state30)) begin
        line_buf_out_address0 = grp_quad_frame_remapper_Pipeline_2_fu_227_line_buf_out_address0;
    end else if ((1'b1 == ap_CS_fsm_state21)) begin
        line_buf_out_address0 = grp_quad_frame_remapper_Pipeline_7_fu_219_line_buf_out_address0;
    end else if ((1'b1 == ap_CS_fsm_state19)) begin
        line_buf_out_address0 = grp_quad_frame_remapper_Pipeline_VITIS_LOOP_146_3_fu_213_line_buf_out_address0;
    end else if ((1'b1 == ap_CS_fsm_state17)) begin
        line_buf_out_address0 = grp_quad_frame_remapper_Pipeline_VITIS_LOOP_132_2_fu_207_line_buf_out_address0;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        line_buf_out_address0 = grp_quad_frame_remapper_Pipeline_4_fu_202_line_buf_out_address0;
    end else if ((1'b1 == ap_CS_fsm_state27)) begin
        line_buf_out_address0 = grp_quad_frame_remapper_Pipeline_1_fu_189_line_buf_out_address0;
    end else begin
        line_buf_out_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state30)) begin
        line_buf_out_ce0 = grp_quad_frame_remapper_Pipeline_2_fu_227_line_buf_out_ce0;
    end else if ((1'b1 == ap_CS_fsm_state21)) begin
        line_buf_out_ce0 = grp_quad_frame_remapper_Pipeline_7_fu_219_line_buf_out_ce0;
    end else if ((1'b1 == ap_CS_fsm_state19)) begin
        line_buf_out_ce0 = grp_quad_frame_remapper_Pipeline_VITIS_LOOP_146_3_fu_213_line_buf_out_ce0;
    end else if ((1'b1 == ap_CS_fsm_state17)) begin
        line_buf_out_ce0 = grp_quad_frame_remapper_Pipeline_VITIS_LOOP_132_2_fu_207_line_buf_out_ce0;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        line_buf_out_ce0 = grp_quad_frame_remapper_Pipeline_4_fu_202_line_buf_out_ce0;
    end else if ((1'b1 == ap_CS_fsm_state27)) begin
        line_buf_out_ce0 = grp_quad_frame_remapper_Pipeline_1_fu_189_line_buf_out_ce0;
    end else begin
        line_buf_out_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state19)) begin
        line_buf_out_d0 = grp_quad_frame_remapper_Pipeline_VITIS_LOOP_146_3_fu_213_line_buf_out_d0;
    end else if ((1'b1 == ap_CS_fsm_state17)) begin
        line_buf_out_d0 = grp_quad_frame_remapper_Pipeline_VITIS_LOOP_132_2_fu_207_line_buf_out_d0;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        line_buf_out_d0 = grp_quad_frame_remapper_Pipeline_4_fu_202_line_buf_out_d0;
    end else if ((1'b1 == ap_CS_fsm_state27)) begin
        line_buf_out_d0 = grp_quad_frame_remapper_Pipeline_1_fu_189_line_buf_out_d0;
    end else begin
        line_buf_out_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state19)) begin
        line_buf_out_we0 = grp_quad_frame_remapper_Pipeline_VITIS_LOOP_146_3_fu_213_line_buf_out_we0;
    end else if ((1'b1 == ap_CS_fsm_state17)) begin
        line_buf_out_we0 = grp_quad_frame_remapper_Pipeline_VITIS_LOOP_132_2_fu_207_line_buf_out_we0;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        line_buf_out_we0 = grp_quad_frame_remapper_Pipeline_4_fu_202_line_buf_out_we0;
    end else if ((1'b1 == ap_CS_fsm_state27)) begin
        line_buf_out_we0 = grp_quad_frame_remapper_Pipeline_1_fu_189_line_buf_out_we0;
    end else begin
        line_buf_out_we0 = 16'd0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((icmp_ln91_fu_272_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else if (((icmp_ln91_fu_272_p2 == 1'd0) & (or_ln102_fu_329_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state27;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            if (((gmem0_0_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state6))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            if (((1'b0 == ap_block_state15_on_subcall_done) & (1'b1 == ap_CS_fsm_state15))) begin
                ap_NS_fsm = ap_ST_fsm_state16;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state15;
            end
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state17;
        end
        ap_ST_fsm_state17 : begin
            if (((grp_quad_frame_remapper_Pipeline_VITIS_LOOP_132_2_fu_207_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state17))) begin
                ap_NS_fsm = ap_ST_fsm_state18;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state17;
            end
        end
        ap_ST_fsm_state18 : begin
            ap_NS_fsm = ap_ST_fsm_state19;
        end
        ap_ST_fsm_state19 : begin
            if ((~((gmem1_0_AWREADY == 1'b0) | (grp_quad_frame_remapper_Pipeline_VITIS_LOOP_146_3_fu_213_ap_done == 1'b0)) & (1'b1 == ap_CS_fsm_state19))) begin
                ap_NS_fsm = ap_ST_fsm_state20;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state19;
            end
        end
        ap_ST_fsm_state20 : begin
            ap_NS_fsm = ap_ST_fsm_state21;
        end
        ap_ST_fsm_state21 : begin
            if (((grp_quad_frame_remapper_Pipeline_7_fu_219_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state21))) begin
                ap_NS_fsm = ap_ST_fsm_state22;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state21;
            end
        end
        ap_ST_fsm_state22 : begin
            ap_NS_fsm = ap_ST_fsm_state23;
        end
        ap_ST_fsm_state23 : begin
            ap_NS_fsm = ap_ST_fsm_state24;
        end
        ap_ST_fsm_state24 : begin
            ap_NS_fsm = ap_ST_fsm_state25;
        end
        ap_ST_fsm_state25 : begin
            ap_NS_fsm = ap_ST_fsm_state26;
        end
        ap_ST_fsm_state26 : begin
            if (((1'b0 == ap_block_state26) & (1'b1 == ap_CS_fsm_state26))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state26;
            end
        end
        ap_ST_fsm_state27 : begin
            if (((grp_quad_frame_remapper_Pipeline_1_fu_189_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state27))) begin
                ap_NS_fsm = ap_ST_fsm_state28;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state27;
            end
        end
        ap_ST_fsm_state28 : begin
            if (((gmem1_0_AWREADY == 1'b1) & (1'b1 == ap_CS_fsm_state28))) begin
                ap_NS_fsm = ap_ST_fsm_state29;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state28;
            end
        end
        ap_ST_fsm_state29 : begin
            ap_NS_fsm = ap_ST_fsm_state30;
        end
        ap_ST_fsm_state30 : begin
            if (((grp_quad_frame_remapper_Pipeline_2_fu_227_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state30))) begin
                ap_NS_fsm = ap_ST_fsm_state31;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state30;
            end
        end
        ap_ST_fsm_state31 : begin
            ap_NS_fsm = ap_ST_fsm_state32;
        end
        ap_ST_fsm_state32 : begin
            ap_NS_fsm = ap_ST_fsm_state33;
        end
        ap_ST_fsm_state33 : begin
            ap_NS_fsm = ap_ST_fsm_state34;
        end
        ap_ST_fsm_state34 : begin
            ap_NS_fsm = ap_ST_fsm_state35;
        end
        ap_ST_fsm_state35 : begin
            if (((gmem1_0_BVALID == 1'b1) & (1'b1 == ap_CS_fsm_state35))) begin
                ap_NS_fsm = ap_ST_fsm_state26;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state35;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln117_1_fu_359_p2 = (zext_ln117_fu_346_p1 + zext_ln117_2_fu_355_p1);

assign add_ln117_fu_365_p2 = ($signed(add_ln117_1_fu_359_p2) + $signed(13'd7652));

assign add_ln120_fu_385_p2 = (zext_ln117_1_fu_381_p1 + 11'd540);

assign add_ln123_fu_418_p2 = (zext_ln123_1_fu_414_p1 + src_read_reg_492);

assign add_ln91_fu_266_p2 = (phi_mul_fu_142 + 23'd5760);

assign add_ln95_fu_292_p2 = (zext_ln95_fu_288_p1 + dst_read_reg_487);

assign add_ln98_fu_303_p2 = (trunc_ln91_fu_284_p1 + 10'd484);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state15 = ap_CS_fsm[32'd14];

assign ap_CS_fsm_state16 = ap_CS_fsm[32'd15];

assign ap_CS_fsm_state17 = ap_CS_fsm[32'd16];

assign ap_CS_fsm_state18 = ap_CS_fsm[32'd17];

assign ap_CS_fsm_state19 = ap_CS_fsm[32'd18];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state20 = ap_CS_fsm[32'd19];

assign ap_CS_fsm_state21 = ap_CS_fsm[32'd20];

assign ap_CS_fsm_state26 = ap_CS_fsm[32'd25];

assign ap_CS_fsm_state27 = ap_CS_fsm[32'd26];

assign ap_CS_fsm_state28 = ap_CS_fsm[32'd27];

assign ap_CS_fsm_state29 = ap_CS_fsm[32'd28];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state30 = ap_CS_fsm[32'd29];

assign ap_CS_fsm_state35 = ap_CS_fsm[32'd34];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

always @ (*) begin
    ap_block_state15_on_subcall_done = ((grp_quad_frame_remapper_Pipeline_4_fu_202_ap_done == 1'b0) | (grp_quad_frame_remapper_Pipeline_3_fu_194_ap_done == 1'b0));
end

always @ (*) begin
    ap_block_state26 = ((gmem1_0_BVALID == 1'b0) & (or_ln102_reg_526 == 1'd0));
end

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign grp_fu_235_p4 = {{add_ln95_reg_510[63:4]}};

assign grp_quad_frame_remapper_Pipeline_1_fu_189_ap_start = grp_quad_frame_remapper_Pipeline_1_fu_189_ap_start_reg;

assign grp_quad_frame_remapper_Pipeline_2_fu_227_ap_start = grp_quad_frame_remapper_Pipeline_2_fu_227_ap_start_reg;

assign grp_quad_frame_remapper_Pipeline_3_fu_194_ap_start = grp_quad_frame_remapper_Pipeline_3_fu_194_ap_start_reg;

assign grp_quad_frame_remapper_Pipeline_4_fu_202_ap_start = grp_quad_frame_remapper_Pipeline_4_fu_202_ap_start_reg;

assign grp_quad_frame_remapper_Pipeline_7_fu_219_ap_start = grp_quad_frame_remapper_Pipeline_7_fu_219_ap_start_reg;

assign grp_quad_frame_remapper_Pipeline_VITIS_LOOP_132_2_fu_207_ap_start = grp_quad_frame_remapper_Pipeline_VITIS_LOOP_132_2_fu_207_ap_start_reg;

assign grp_quad_frame_remapper_Pipeline_VITIS_LOOP_146_3_fu_213_ap_start = grp_quad_frame_remapper_Pipeline_VITIS_LOOP_146_3_fu_213_ap_start_reg;

assign icmp_ln102_1_fu_323_p2 = ((local_y_fu_309_p3 > 10'd485) ? 1'b1 : 1'b0);

assign icmp_ln102_fu_317_p2 = ((local_y_fu_309_p3 < 10'd54) ? 1'b1 : 1'b0);

assign icmp_ln91_fu_272_p2 = ((y_fu_146 == 11'd1080) ? 1'b1 : 1'b0);

assign is_bottom_fu_297_p2 = ((y_fu_146 > 11'd539) ? 1'b1 : 1'b0);

assign local_y_fu_309_p3 = ((is_bottom_fu_297_p2[0:0] == 1'b1) ? add_ln98_fu_303_p2 : trunc_ln91_fu_284_p1);

assign mul_ln123_fu_401_p0 = mul_ln123_fu_401_p00;

assign mul_ln123_fu_401_p00 = src_y_reg_530;

assign mul_ln123_fu_401_p1 = 19'd360;

assign or_ln102_fu_329_p2 = (icmp_ln102_fu_317_p2 | icmp_ln102_1_fu_323_p2);

assign sext_ln107_fu_462_p1 = grp_fu_235_p4;

assign sext_ln123_fu_433_p1 = $signed(trunc_ln1_reg_540);

assign sext_ln160_fu_443_p1 = $signed(reg_244);

assign shl_ln117_fu_350_p2 = local_y_reg_520 << 10'd1;

assign shl_ln_fu_407_p3 = {{mul_ln123_reg_535}, {4'd0}};

assign src_local_y_fu_371_p4 = {{add_ln117_fu_365_p2[12:3]}};

assign src_y_fu_391_p3 = ((is_bottom_reg_515[0:0] == 1'b1) ? add_ln120_fu_385_p2 : zext_ln117_1_fu_381_p1);

assign tmp_fu_338_p3 = {{trunc_ln117_fu_335_p1}, {3'd0}};

assign trunc_ln117_fu_335_p1 = local_y_reg_520[8:0];

assign trunc_ln91_fu_284_p1 = y_fu_146[9:0];

assign y_2_fu_278_p2 = (y_fu_146 + 11'd1);

assign zext_ln117_1_fu_381_p1 = src_local_y_fu_371_p4;

assign zext_ln117_2_fu_355_p1 = shl_ln117_fu_350_p2;

assign zext_ln117_fu_346_p1 = tmp_fu_338_p3;

assign zext_ln123_1_fu_414_p1 = shl_ln_fu_407_p3;

assign zext_ln95_fu_288_p1 = phi_mul_fu_142;

endmodule //quad_frame_remapper
