// ==============================================================
// Generated by Vitis HLS v2025.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module quad_frame_remapper_quad_frame_remapper_Pipeline_VITIS_LOOP_146_3 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        line_buf_in_address0,
        line_buf_in_ce0,
        line_buf_in_q0,
        line_buf_in_address1,
        line_buf_in_ce1,
        line_buf_in_q1,
        line_buf_out_address0,
        line_buf_out_ce0,
        line_buf_out_we0,
        line_buf_out_d0
);

parameter    ap_ST_fsm_pp0_stage0 = 3'd1;
parameter    ap_ST_fsm_pp0_stage1 = 3'd2;
parameter    ap_ST_fsm_pp0_stage2 = 3'd4;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [8:0] line_buf_in_address0;
output   line_buf_in_ce0;
input  [127:0] line_buf_in_q0;
output  [8:0] line_buf_in_address1;
output   line_buf_in_ce1;
input  [127:0] line_buf_in_q1;
output  [8:0] line_buf_out_address0;
output   line_buf_out_ce0;
output  [15:0] line_buf_out_we0;
output  [127:0] line_buf_out_d0;

reg ap_idle;

(* fsm_encoding = "none" *) reg   [2:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_idle_pp0;
wire    ap_CS_fsm_pp0_stage2;
wire    ap_block_pp0_stage2_subdone;
reg    ap_enable_reg_pp0_iter0_reg;
reg   [0:0] icmp_ln146_reg_553;
reg    ap_condition_exit_pp0_iter0_stage2;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg   [127:0] reg_135;
wire    ap_block_pp0_stage2_11001;
wire    ap_block_pp0_stage0_11001;
reg   [9:0] i_1_reg_546;
wire   [0:0] icmp_ln146_fu_148_p2;
reg   [9:0] tmp_7_reg_557;
wire   [12:0] zext_ln154_1_fu_206_p1;
reg   [12:0] zext_ln154_1_reg_563;
wire    ap_CS_fsm_pp0_stage1;
wire    ap_block_pp0_stage1_11001;
wire   [3:0] trunc_ln154_fu_231_p1;
reg   [3:0] trunc_ln154_reg_573;
wire   [3:0] trunc_ln155_fu_256_p1;
reg   [3:0] trunc_ln155_reg_583;
reg   [127:0] line_buf_in_load_1_reg_588;
wire   [3:0] trunc_ln156_fu_285_p1;
reg   [3:0] trunc_ln156_reg_598;
wire   [7:0] trunc_ln154_1_fu_314_p1;
reg   [7:0] trunc_ln154_1_reg_603;
wire   [12:0] zext_ln154_6_fu_331_p1;
reg   [12:0] zext_ln154_6_reg_608;
wire   [3:0] trunc_ln154_2_fu_341_p1;
reg   [3:0] trunc_ln154_2_reg_614;
wire   [15:0] shl_ln154_fu_349_p2;
reg   [15:0] shl_ln154_reg_619;
reg   [8:0] lshr_ln154_2_reg_624;
wire   [7:0] trunc_ln155_1_fu_381_p1;
reg   [7:0] trunc_ln155_1_reg_629;
wire   [3:0] trunc_ln155_2_fu_415_p1;
reg   [3:0] trunc_ln155_2_reg_634;
wire   [15:0] shl_ln155_fu_423_p2;
reg   [15:0] shl_ln155_reg_639;
reg   [8:0] lshr_ln155_2_reg_644;
wire   [7:0] trunc_ln156_1_fu_456_p1;
reg   [7:0] trunc_ln156_1_reg_649;
wire   [15:0] shl_ln156_fu_501_p2;
reg   [15:0] shl_ln156_reg_654;
wire   [127:0] shl_ln156_1_fu_519_p2;
reg   [127:0] shl_ln156_1_reg_659;
reg   [8:0] lshr_ln156_2_reg_664;
wire    ap_block_pp0_stage0_subdone;
wire   [63:0] zext_ln154_fu_226_p1;
wire    ap_block_pp0_stage1;
wire   [63:0] zext_ln155_fu_251_p1;
wire   [63:0] zext_ln156_fu_280_p1;
wire    ap_block_pp0_stage2;
wire   [63:0] zext_ln154_8_fu_406_p1;
wire   [63:0] zext_ln155_5_fu_481_p1;
wire   [63:0] zext_ln156_5_fu_535_p1;
wire    ap_block_pp0_stage0;
reg   [9:0] i_fu_72;
wire   [9:0] add_ln146_fu_260_p2;
wire    ap_loop_init;
reg   [9:0] ap_sig_allocacmp_i_1;
reg    line_buf_in_ce1_local;
reg    line_buf_in_ce0_local;
reg   [8:0] line_buf_in_address0_local;
reg    line_buf_out_ce0_local;
reg   [15:0] line_buf_out_we0_local;
reg   [8:0] line_buf_out_address0_local;
reg   [127:0] line_buf_out_d0_local;
wire   [127:0] shl_ln154_1_fu_399_p2;
wire   [127:0] shl_ln155_1_fu_474_p2;
wire   [10:0] tmp_fu_162_p3;
wire   [12:0] p_shl1_fu_154_p3;
wire   [12:0] zext_ln148_fu_170_p1;
wire   [12:0] add_ln148_fu_174_p2;
wire   [11:0] p_shl2_fu_193_p3;
wire   [11:0] zext_ln154_4_fu_190_p1;
wire   [11:0] sub_ln154_fu_200_p2;
wire   [12:0] add_ln154_fu_210_p2;
wire   [8:0] lshr_ln3_fu_216_p4;
wire   [12:0] add_ln155_fu_235_p2;
wire   [8:0] lshr_ln4_fu_241_p4;
wire   [12:0] add_ln156_fu_265_p2;
wire   [8:0] lshr_ln5_fu_270_p4;
wire   [6:0] shl_ln4_fu_297_p3;
wire   [127:0] zext_ln154_5_fu_304_p1;
wire   [127:0] lshr_ln154_fu_308_p2;
wire   [11:0] p_shl_fu_318_p3;
wire   [11:0] zext_ln146_fu_294_p1;
wire   [11:0] sub_ln154_1_fu_325_p2;
wire   [12:0] add_ln154_1_fu_335_p2;
wire   [15:0] zext_ln154_3_fu_345_p1;
wire   [6:0] shl_ln5_fu_365_p3;
wire   [127:0] zext_ln155_1_fu_372_p1;
wire   [127:0] lshr_ln155_fu_376_p2;
wire   [6:0] shl_ln154_2_fu_388_p3;
wire   [127:0] zext_ln154_2_fu_385_p1;
wire   [127:0] zext_ln154_7_fu_395_p1;
wire   [12:0] add_ln155_1_fu_410_p2;
wire   [15:0] zext_ln155_3_fu_419_p1;
wire   [6:0] shl_ln6_fu_439_p3;
wire   [127:0] zext_ln156_1_fu_446_p1;
wire   [127:0] lshr_ln156_fu_450_p2;
wire   [6:0] shl_ln155_2_fu_463_p3;
wire   [127:0] zext_ln155_2_fu_460_p1;
wire   [127:0] zext_ln155_4_fu_470_p1;
wire   [12:0] add_ln156_1_fu_485_p2;
wire   [3:0] trunc_ln156_2_fu_493_p1;
wire   [15:0] zext_ln156_3_fu_497_p1;
wire   [6:0] shl_ln156_2_fu_507_p3;
wire   [127:0] zext_ln156_2_fu_490_p1;
wire   [127:0] zext_ln156_4_fu_515_p1;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_condition_exit_pp0_iter1_stage0;
reg    ap_idle_pp0_0to0;
reg   [2:0] ap_NS_fsm;
reg    ap_idle_pp0_1to2;
wire    ap_block_pp0_stage1_subdone;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 3'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter0_reg = 1'b0;
#0 i_fu_72 = 10'd0;
#0 ap_done_reg = 1'b0;
end

quad_frame_remapper_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage2),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            ap_enable_reg_pp0_iter0_reg <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage2)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage2_subdone) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter2 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage2_subdone) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to0 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter1_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        i_fu_72 <= 10'd0;
    end else if (((icmp_ln146_reg_553 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        i_fu_72 <= add_ln146_fu_260_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        reg_135 <= line_buf_in_q0;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        reg_135 <= line_buf_in_q1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        i_1_reg_546 <= ap_sig_allocacmp_i_1;
        icmp_ln146_reg_553 <= icmp_ln146_fu_148_p2;
        lshr_ln154_2_reg_624 <= {{add_ln154_1_fu_335_p2[12:4]}};
        shl_ln154_reg_619 <= shl_ln154_fu_349_p2;
        tmp_7_reg_557 <= {{add_ln148_fu_174_p2[12:3]}};
        trunc_ln154_1_reg_603 <= trunc_ln154_1_fu_314_p1;
        trunc_ln154_2_reg_614 <= trunc_ln154_2_fu_341_p1;
        trunc_ln155_1_reg_629 <= trunc_ln155_1_fu_381_p1;
        zext_ln154_6_reg_608[11 : 0] <= zext_ln154_6_fu_331_p1[11 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        line_buf_in_load_1_reg_588 <= line_buf_in_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        lshr_ln155_2_reg_644 <= {{add_ln155_1_fu_410_p2[12:4]}};
        shl_ln155_reg_639 <= shl_ln155_fu_423_p2;
        trunc_ln154_reg_573 <= trunc_ln154_fu_231_p1;
        trunc_ln155_2_reg_634 <= trunc_ln155_2_fu_415_p1;
        trunc_ln155_reg_583 <= trunc_ln155_fu_256_p1;
        trunc_ln156_1_reg_649 <= trunc_ln156_1_fu_456_p1;
        zext_ln154_1_reg_563[11 : 0] <= zext_ln154_1_fu_206_p1[11 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        lshr_ln156_2_reg_664 <= {{add_ln156_1_fu_485_p2[12:4]}};
        shl_ln156_1_reg_659 <= shl_ln156_1_fu_519_p2;
        shl_ln156_reg_654 <= shl_ln156_fu_501_p2;
        trunc_ln156_reg_598 <= trunc_ln156_fu_285_p1;
    end
end

always @ (*) begin
    if (((icmp_ln146_reg_553 == 1'd1) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2_subdone) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        ap_condition_exit_pp0_iter0_stage2 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage2 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln146_reg_553 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        ap_enable_reg_pp0_iter0 = ap_start_int;
    end else begin
        ap_enable_reg_pp0_iter0 = ap_enable_reg_pp0_iter0_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b0)) begin
        ap_idle_pp0_0to0 = 1'b1;
    end else begin
        ap_idle_pp0_0to0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0))) begin
        ap_idle_pp0_1to2 = 1'b1;
    end else begin
        ap_idle_pp0_1to2 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2_subdone) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_i_1 = 10'd0;
    end else begin
        ap_sig_allocacmp_i_1 = i_fu_72;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0_reg == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            line_buf_in_address0_local = zext_ln156_fu_280_p1;
        end else if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            line_buf_in_address0_local = zext_ln155_fu_251_p1;
        end else begin
            line_buf_in_address0_local = 'bx;
        end
    end else begin
        line_buf_in_address0_local = 'bx;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
        line_buf_in_ce0_local = 1'b1;
    end else begin
        line_buf_in_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        line_buf_in_ce1_local = 1'b1;
    end else begin
        line_buf_in_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        line_buf_out_address0_local = zext_ln156_5_fu_535_p1;
    end else if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        line_buf_out_address0_local = zext_ln155_5_fu_481_p1;
    end else if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        line_buf_out_address0_local = zext_ln154_8_fu_406_p1;
    end else begin
        line_buf_out_address0_local = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
        line_buf_out_ce0_local = 1'b1;
    end else begin
        line_buf_out_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        line_buf_out_d0_local = shl_ln156_1_reg_659;
    end else if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        line_buf_out_d0_local = shl_ln155_1_fu_474_p2;
    end else if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        line_buf_out_d0_local = shl_ln154_1_fu_399_p2;
    end else begin
        line_buf_out_d0_local = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        line_buf_out_we0_local = shl_ln156_reg_654;
    end else if (((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        line_buf_out_we0_local = shl_ln155_reg_639;
    end else if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        line_buf_out_we0_local = shl_ln154_reg_619;
    end else begin
        line_buf_out_we0_local = 16'd0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            if (((ap_idle_pp0_0to0 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter1_stage0))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((~((ap_start_int == 1'b0) & (ap_idle_pp0_1to2 == 1'b1)) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        ap_ST_fsm_pp0_stage2 : begin
            if ((1'b0 == ap_block_pp0_stage2_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln146_fu_260_p2 = (i_1_reg_546 + 10'd1);

assign add_ln148_fu_174_p2 = (p_shl1_fu_154_p3 + zext_ln148_fu_170_p1);

assign add_ln154_1_fu_335_p2 = (zext_ln154_6_fu_331_p1 + 13'd3168);

assign add_ln154_fu_210_p2 = (zext_ln154_1_fu_206_p1 + 13'd2880);

assign add_ln155_1_fu_410_p2 = (zext_ln154_6_reg_608 + 13'd3169);

assign add_ln155_fu_235_p2 = (zext_ln154_1_fu_206_p1 + 13'd2881);

assign add_ln156_1_fu_485_p2 = (zext_ln154_6_reg_608 + 13'd3170);

assign add_ln156_fu_265_p2 = (zext_ln154_1_reg_563 + 13'd2882);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_pp0_stage2 = ap_CS_fsm[32'd2];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage2;

assign ap_ready = ap_ready_sig;

assign icmp_ln146_fu_148_p2 = ((ap_sig_allocacmp_i_1 == 10'd768) ? 1'b1 : 1'b0);

assign line_buf_in_address0 = line_buf_in_address0_local;

assign line_buf_in_address1 = zext_ln154_fu_226_p1;

assign line_buf_in_ce0 = line_buf_in_ce0_local;

assign line_buf_in_ce1 = line_buf_in_ce1_local;

assign line_buf_out_address0 = line_buf_out_address0_local;

assign line_buf_out_ce0 = line_buf_out_ce0_local;

assign line_buf_out_d0 = line_buf_out_d0_local;

assign line_buf_out_we0 = line_buf_out_we0_local;

assign lshr_ln154_fu_308_p2 = reg_135 >> zext_ln154_5_fu_304_p1;

assign lshr_ln155_fu_376_p2 = line_buf_in_load_1_reg_588 >> zext_ln155_1_fu_372_p1;

assign lshr_ln156_fu_450_p2 = reg_135 >> zext_ln156_1_fu_446_p1;

assign lshr_ln3_fu_216_p4 = {{add_ln154_fu_210_p2[12:4]}};

assign lshr_ln4_fu_241_p4 = {{add_ln155_fu_235_p2[12:4]}};

assign lshr_ln5_fu_270_p4 = {{add_ln156_fu_265_p2[12:4]}};

assign p_shl1_fu_154_p3 = {{ap_sig_allocacmp_i_1}, {3'd0}};

assign p_shl2_fu_193_p3 = {{tmp_7_reg_557}, {2'd0}};

assign p_shl_fu_318_p3 = {{i_1_reg_546}, {2'd0}};

assign shl_ln154_1_fu_399_p2 = zext_ln154_2_fu_385_p1 << zext_ln154_7_fu_395_p1;

assign shl_ln154_2_fu_388_p3 = {{trunc_ln154_2_reg_614}, {3'd0}};

assign shl_ln154_fu_349_p2 = 16'd1 << zext_ln154_3_fu_345_p1;

assign shl_ln155_1_fu_474_p2 = zext_ln155_2_fu_460_p1 << zext_ln155_4_fu_470_p1;

assign shl_ln155_2_fu_463_p3 = {{trunc_ln155_2_reg_634}, {3'd0}};

assign shl_ln155_fu_423_p2 = 16'd1 << zext_ln155_3_fu_419_p1;

assign shl_ln156_1_fu_519_p2 = zext_ln156_2_fu_490_p1 << zext_ln156_4_fu_515_p1;

assign shl_ln156_2_fu_507_p3 = {{trunc_ln156_2_fu_493_p1}, {3'd0}};

assign shl_ln156_fu_501_p2 = 16'd1 << zext_ln156_3_fu_497_p1;

assign shl_ln4_fu_297_p3 = {{trunc_ln154_reg_573}, {3'd0}};

assign shl_ln5_fu_365_p3 = {{trunc_ln155_reg_583}, {3'd0}};

assign shl_ln6_fu_439_p3 = {{trunc_ln156_reg_598}, {3'd0}};

assign sub_ln154_1_fu_325_p2 = (p_shl_fu_318_p3 - zext_ln146_fu_294_p1);

assign sub_ln154_fu_200_p2 = (p_shl2_fu_193_p3 - zext_ln154_4_fu_190_p1);

assign tmp_fu_162_p3 = {{ap_sig_allocacmp_i_1}, {1'd0}};

assign trunc_ln154_1_fu_314_p1 = lshr_ln154_fu_308_p2[7:0];

assign trunc_ln154_2_fu_341_p1 = add_ln154_1_fu_335_p2[3:0];

assign trunc_ln154_fu_231_p1 = add_ln154_fu_210_p2[3:0];

assign trunc_ln155_1_fu_381_p1 = lshr_ln155_fu_376_p2[7:0];

assign trunc_ln155_2_fu_415_p1 = add_ln155_1_fu_410_p2[3:0];

assign trunc_ln155_fu_256_p1 = add_ln155_fu_235_p2[3:0];

assign trunc_ln156_1_fu_456_p1 = lshr_ln156_fu_450_p2[7:0];

assign trunc_ln156_2_fu_493_p1 = add_ln156_1_fu_485_p2[3:0];

assign trunc_ln156_fu_285_p1 = add_ln156_fu_265_p2[3:0];

assign zext_ln146_fu_294_p1 = i_1_reg_546;

assign zext_ln148_fu_170_p1 = tmp_fu_162_p3;

assign zext_ln154_1_fu_206_p1 = sub_ln154_fu_200_p2;

assign zext_ln154_2_fu_385_p1 = trunc_ln154_1_reg_603;

assign zext_ln154_3_fu_345_p1 = trunc_ln154_2_fu_341_p1;

assign zext_ln154_4_fu_190_p1 = tmp_7_reg_557;

assign zext_ln154_5_fu_304_p1 = shl_ln4_fu_297_p3;

assign zext_ln154_6_fu_331_p1 = sub_ln154_1_fu_325_p2;

assign zext_ln154_7_fu_395_p1 = shl_ln154_2_fu_388_p3;

assign zext_ln154_8_fu_406_p1 = lshr_ln154_2_reg_624;

assign zext_ln154_fu_226_p1 = lshr_ln3_fu_216_p4;

assign zext_ln155_1_fu_372_p1 = shl_ln5_fu_365_p3;

assign zext_ln155_2_fu_460_p1 = trunc_ln155_1_reg_629;

assign zext_ln155_3_fu_419_p1 = trunc_ln155_2_fu_415_p1;

assign zext_ln155_4_fu_470_p1 = shl_ln155_2_fu_463_p3;

assign zext_ln155_5_fu_481_p1 = lshr_ln155_2_reg_644;

assign zext_ln155_fu_251_p1 = lshr_ln4_fu_241_p4;

assign zext_ln156_1_fu_446_p1 = shl_ln6_fu_439_p3;

assign zext_ln156_2_fu_490_p1 = trunc_ln156_1_reg_649;

assign zext_ln156_3_fu_497_p1 = trunc_ln156_2_fu_493_p1;

assign zext_ln156_4_fu_515_p1 = shl_ln156_2_fu_507_p3;

assign zext_ln156_5_fu_535_p1 = lshr_ln156_2_reg_664;

assign zext_ln156_fu_280_p1 = lshr_ln5_fu_270_p4;

always @ (posedge ap_clk) begin
    zext_ln154_1_reg_563[12] <= 1'b0;
    zext_ln154_6_reg_608[12] <= 1'b0;
end

endmodule //quad_frame_remapper_quad_frame_remapper_Pipeline_VITIS_LOOP_146_3
