-- ==============================================================
-- Generated by Vitis HLS v2025.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity quad_frame_remapper_quad_frame_remapper_Pipeline_VITIS_LOOP_146_3 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    line_buf_in_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
    line_buf_in_ce0 : OUT STD_LOGIC;
    line_buf_in_q0 : IN STD_LOGIC_VECTOR (127 downto 0);
    line_buf_in_address1 : OUT STD_LOGIC_VECTOR (8 downto 0);
    line_buf_in_ce1 : OUT STD_LOGIC;
    line_buf_in_q1 : IN STD_LOGIC_VECTOR (127 downto 0);
    line_buf_out_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
    line_buf_out_ce0 : OUT STD_LOGIC;
    line_buf_out_we0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    line_buf_out_d0 : OUT STD_LOGIC_VECTOR (127 downto 0) );
end;


architecture behav of quad_frame_remapper_quad_frame_remapper_Pipeline_VITIS_LOOP_146_3 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_ST_fsm_pp0_stage1 : STD_LOGIC_VECTOR (2 downto 0) := "010";
    constant ap_ST_fsm_pp0_stage2 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv10_0 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_lv10_300 : STD_LOGIC_VECTOR (9 downto 0) := "1100000000";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001100";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv13_B40 : STD_LOGIC_VECTOR (12 downto 0) := "0101101000000";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv13_B41 : STD_LOGIC_VECTOR (12 downto 0) := "0101101000001";
    constant ap_const_lv10_1 : STD_LOGIC_VECTOR (9 downto 0) := "0000000001";
    constant ap_const_lv13_B42 : STD_LOGIC_VECTOR (12 downto 0) := "0101101000010";
    constant ap_const_lv13_C60 : STD_LOGIC_VECTOR (12 downto 0) := "0110001100000";
    constant ap_const_lv16_1 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000001";
    constant ap_const_lv13_C61 : STD_LOGIC_VECTOR (12 downto 0) := "0110001100001";
    constant ap_const_lv13_C62 : STD_LOGIC_VECTOR (12 downto 0) := "0110001100010";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (2 downto 0) := "001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_CS_fsm_pp0_stage2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage2 : signal is "none";
    signal ap_block_pp0_stage2_subdone : BOOLEAN;
    signal ap_enable_reg_pp0_iter0_reg : STD_LOGIC := '0';
    signal icmp_ln146_reg_553 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage2 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal reg_135 : STD_LOGIC_VECTOR (127 downto 0);
    signal ap_block_pp0_stage2_11001 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal i_1_reg_546 : STD_LOGIC_VECTOR (9 downto 0);
    signal icmp_ln146_fu_148_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_7_reg_557 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln154_1_fu_206_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal zext_ln154_1_reg_563 : STD_LOGIC_VECTOR (12 downto 0);
    signal ap_CS_fsm_pp0_stage1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage1 : signal is "none";
    signal ap_block_pp0_stage1_11001 : BOOLEAN;
    signal trunc_ln154_fu_231_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal trunc_ln154_reg_573 : STD_LOGIC_VECTOR (3 downto 0);
    signal trunc_ln155_fu_256_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal trunc_ln155_reg_583 : STD_LOGIC_VECTOR (3 downto 0);
    signal line_buf_in_load_1_reg_588 : STD_LOGIC_VECTOR (127 downto 0);
    signal trunc_ln156_fu_285_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal trunc_ln156_reg_598 : STD_LOGIC_VECTOR (3 downto 0);
    signal trunc_ln154_1_fu_314_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln154_1_reg_603 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln154_6_fu_331_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal zext_ln154_6_reg_608 : STD_LOGIC_VECTOR (12 downto 0);
    signal trunc_ln154_2_fu_341_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal trunc_ln154_2_reg_614 : STD_LOGIC_VECTOR (3 downto 0);
    signal shl_ln154_fu_349_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal shl_ln154_reg_619 : STD_LOGIC_VECTOR (15 downto 0);
    signal lshr_ln154_2_reg_624 : STD_LOGIC_VECTOR (8 downto 0);
    signal trunc_ln155_1_fu_381_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln155_1_reg_629 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln155_2_fu_415_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal trunc_ln155_2_reg_634 : STD_LOGIC_VECTOR (3 downto 0);
    signal shl_ln155_fu_423_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal shl_ln155_reg_639 : STD_LOGIC_VECTOR (15 downto 0);
    signal lshr_ln155_2_reg_644 : STD_LOGIC_VECTOR (8 downto 0);
    signal trunc_ln156_1_fu_456_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln156_1_reg_649 : STD_LOGIC_VECTOR (7 downto 0);
    signal shl_ln156_fu_501_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal shl_ln156_reg_654 : STD_LOGIC_VECTOR (15 downto 0);
    signal shl_ln156_1_fu_519_p2 : STD_LOGIC_VECTOR (127 downto 0);
    signal shl_ln156_1_reg_659 : STD_LOGIC_VECTOR (127 downto 0);
    signal lshr_ln156_2_reg_664 : STD_LOGIC_VECTOR (8 downto 0);
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal zext_ln154_fu_226_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage1 : BOOLEAN;
    signal zext_ln155_fu_251_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln156_fu_280_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage2 : BOOLEAN;
    signal zext_ln154_8_fu_406_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln155_5_fu_481_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln156_5_fu_535_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal i_fu_72 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    signal add_ln146_fu_260_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_i_1 : STD_LOGIC_VECTOR (9 downto 0);
    signal line_buf_in_ce1_local : STD_LOGIC;
    signal line_buf_in_ce0_local : STD_LOGIC;
    signal line_buf_in_address0_local : STD_LOGIC_VECTOR (8 downto 0);
    signal line_buf_out_ce0_local : STD_LOGIC;
    signal line_buf_out_we0_local : STD_LOGIC_VECTOR (15 downto 0);
    signal line_buf_out_address0_local : STD_LOGIC_VECTOR (8 downto 0);
    signal line_buf_out_d0_local : STD_LOGIC_VECTOR (127 downto 0);
    signal shl_ln154_1_fu_399_p2 : STD_LOGIC_VECTOR (127 downto 0);
    signal shl_ln155_1_fu_474_p2 : STD_LOGIC_VECTOR (127 downto 0);
    signal tmp_fu_162_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal p_shl1_fu_154_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal zext_ln148_fu_170_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal add_ln148_fu_174_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal p_shl2_fu_193_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal zext_ln154_4_fu_190_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal sub_ln154_fu_200_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal add_ln154_fu_210_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal lshr_ln3_fu_216_p4 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln155_fu_235_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal lshr_ln4_fu_241_p4 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln156_fu_265_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal lshr_ln5_fu_270_p4 : STD_LOGIC_VECTOR (8 downto 0);
    signal shl_ln4_fu_297_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal zext_ln154_5_fu_304_p1 : STD_LOGIC_VECTOR (127 downto 0);
    signal lshr_ln154_fu_308_p2 : STD_LOGIC_VECTOR (127 downto 0);
    signal p_shl_fu_318_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal zext_ln146_fu_294_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal sub_ln154_1_fu_325_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal add_ln154_1_fu_335_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal zext_ln154_3_fu_345_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal shl_ln5_fu_365_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal zext_ln155_1_fu_372_p1 : STD_LOGIC_VECTOR (127 downto 0);
    signal lshr_ln155_fu_376_p2 : STD_LOGIC_VECTOR (127 downto 0);
    signal shl_ln154_2_fu_388_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal zext_ln154_2_fu_385_p1 : STD_LOGIC_VECTOR (127 downto 0);
    signal zext_ln154_7_fu_395_p1 : STD_LOGIC_VECTOR (127 downto 0);
    signal add_ln155_1_fu_410_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal zext_ln155_3_fu_419_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal shl_ln6_fu_439_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal zext_ln156_1_fu_446_p1 : STD_LOGIC_VECTOR (127 downto 0);
    signal lshr_ln156_fu_450_p2 : STD_LOGIC_VECTOR (127 downto 0);
    signal shl_ln155_2_fu_463_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal zext_ln155_2_fu_460_p1 : STD_LOGIC_VECTOR (127 downto 0);
    signal zext_ln155_4_fu_470_p1 : STD_LOGIC_VECTOR (127 downto 0);
    signal add_ln156_1_fu_485_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal trunc_ln156_2_fu_493_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal zext_ln156_3_fu_497_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal shl_ln156_2_fu_507_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal zext_ln156_2_fu_490_p1 : STD_LOGIC_VECTOR (127 downto 0);
    signal zext_ln156_4_fu_515_p1 : STD_LOGIC_VECTOR (127 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_condition_exit_pp0_iter1_stage0 : STD_LOGIC;
    signal ap_idle_pp0_0to0 : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_idle_pp0_1to2 : STD_LOGIC;
    signal ap_block_pp0_stage1_subdone : BOOLEAN;
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component quad_frame_remapper_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    flow_control_loop_pipe_sequential_init_U : component quad_frame_remapper_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage2,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter0_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter0_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then 
                    ap_enable_reg_pp0_iter0_reg <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage2)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage2_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
                    ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage2_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_loop_exit_ready_pp0_iter1_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_idle_pp0_0to0 = ap_const_logic_1) and (ap_const_logic_1 = ap_condition_exit_pp0_iter1_stage0))) then 
                ap_loop_exit_ready_pp0_iter1_reg <= ap_const_logic_0;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
            end if; 
        end if;
    end process;

    i_fu_72_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
                i_fu_72 <= ap_const_lv10_0;
            elsif (((icmp_ln146_reg_553 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
                i_fu_72 <= add_ln146_fu_260_p2;
            end if; 
        end if;
    end process;

    reg_135_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                reg_135 <= line_buf_in_q0;
            elsif (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
                reg_135 <= line_buf_in_q1;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                i_1_reg_546 <= ap_sig_allocacmp_i_1;
                icmp_ln146_reg_553 <= icmp_ln146_fu_148_p2;
                lshr_ln154_2_reg_624 <= add_ln154_1_fu_335_p2(12 downto 4);
                shl_ln154_reg_619 <= shl_ln154_fu_349_p2;
                tmp_7_reg_557 <= add_ln148_fu_174_p2(12 downto 3);
                trunc_ln154_1_reg_603 <= trunc_ln154_1_fu_314_p1;
                trunc_ln154_2_reg_614 <= trunc_ln154_2_fu_341_p1;
                trunc_ln155_1_reg_629 <= trunc_ln155_1_fu_381_p1;
                    zext_ln154_6_reg_608(11 downto 0) <= zext_ln154_6_fu_331_p1(11 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then
                line_buf_in_load_1_reg_588 <= line_buf_in_q0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then
                lshr_ln155_2_reg_644 <= add_ln155_1_fu_410_p2(12 downto 4);
                shl_ln155_reg_639 <= shl_ln155_fu_423_p2;
                trunc_ln154_reg_573 <= trunc_ln154_fu_231_p1;
                trunc_ln155_2_reg_634 <= trunc_ln155_2_fu_415_p1;
                trunc_ln155_reg_583 <= trunc_ln155_fu_256_p1;
                trunc_ln156_1_reg_649 <= trunc_ln156_1_fu_456_p1;
                    zext_ln154_1_reg_563(11 downto 0) <= zext_ln154_1_fu_206_p1(11 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then
                lshr_ln156_2_reg_664 <= add_ln156_1_fu_485_p2(12 downto 4);
                shl_ln156_1_reg_659 <= shl_ln156_1_fu_519_p2;
                shl_ln156_reg_654 <= shl_ln156_fu_501_p2;
                trunc_ln156_reg_598 <= trunc_ln156_fu_285_p1;
            end if;
        end if;
    end process;
    zext_ln154_1_reg_563(12) <= '0';
    zext_ln154_6_reg_608(12) <= '0';

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_block_pp0_stage2_subdone, ap_block_pp0_stage0_subdone, ap_condition_exit_pp0_iter1_stage0, ap_idle_pp0_0to0, ap_idle_pp0_1to2, ap_block_pp0_stage1_subdone, ap_start_int)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                if (((ap_idle_pp0_0to0 = ap_const_logic_1) and (ap_const_logic_1 = ap_condition_exit_pp0_iter1_stage0))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                elsif ((not(((ap_start_int = ap_const_logic_0) and (ap_idle_pp0_1to2 = ap_const_logic_1))) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when ap_ST_fsm_pp0_stage1 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage1_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage2;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                end if;
            when ap_ST_fsm_pp0_stage2 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage2_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage2;
                end if;
            when others =>  
                ap_NS_fsm <= "XXX";
        end case;
    end process;
    add_ln146_fu_260_p2 <= std_logic_vector(unsigned(i_1_reg_546) + unsigned(ap_const_lv10_1));
    add_ln148_fu_174_p2 <= std_logic_vector(unsigned(p_shl1_fu_154_p3) + unsigned(zext_ln148_fu_170_p1));
    add_ln154_1_fu_335_p2 <= std_logic_vector(unsigned(zext_ln154_6_fu_331_p1) + unsigned(ap_const_lv13_C60));
    add_ln154_fu_210_p2 <= std_logic_vector(unsigned(zext_ln154_1_fu_206_p1) + unsigned(ap_const_lv13_B40));
    add_ln155_1_fu_410_p2 <= std_logic_vector(unsigned(zext_ln154_6_reg_608) + unsigned(ap_const_lv13_C61));
    add_ln155_fu_235_p2 <= std_logic_vector(unsigned(zext_ln154_1_fu_206_p1) + unsigned(ap_const_lv13_B41));
    add_ln156_1_fu_485_p2 <= std_logic_vector(unsigned(zext_ln154_6_reg_608) + unsigned(ap_const_lv13_C62));
    add_ln156_fu_265_p2 <= std_logic_vector(unsigned(zext_ln154_1_reg_563) + unsigned(ap_const_lv13_B42));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
    ap_CS_fsm_pp0_stage1 <= ap_CS_fsm(1);
    ap_CS_fsm_pp0_stage2 <= ap_CS_fsm(2);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage2_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage2_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter0_stage2_assign_proc : process(ap_CS_fsm_pp0_stage2, ap_block_pp0_stage2_subdone, ap_enable_reg_pp0_iter0_reg, icmp_ln146_reg_553)
    begin
        if (((icmp_ln146_reg_553 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage2_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
            ap_condition_exit_pp0_iter0_stage2 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage2 <= ap_const_logic_0;
        end if; 
    end process;


    ap_condition_exit_pp0_iter1_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln146_reg_553, ap_block_pp0_stage0_subdone)
    begin
        if (((icmp_ln146_reg_553 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter1_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter1_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter1_reg)
    begin
        if (((ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);

    ap_enable_reg_pp0_iter0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0_reg, ap_start_int)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then 
            ap_enable_reg_pp0_iter0 <= ap_start_int;
        else 
            ap_enable_reg_pp0_iter0 <= ap_enable_reg_pp0_iter0_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_0to0_assign_proc : process(ap_enable_reg_pp0_iter0)
    begin
        if ((ap_enable_reg_pp0_iter0 = ap_const_logic_0)) then 
            ap_idle_pp0_0to0 <= ap_const_logic_1;
        else 
            ap_idle_pp0_0to0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_1to2_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0))) then 
            ap_idle_pp0_1to2 <= ap_const_logic_1;
        else 
            ap_idle_pp0_1to2 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage2;
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage2, ap_block_pp0_stage2_subdone, ap_enable_reg_pp0_iter0_reg)
    begin
        if (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage2_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_i_1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, i_fu_72, ap_loop_init)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_i_1 <= ap_const_lv10_0;
        else 
            ap_sig_allocacmp_i_1 <= i_fu_72;
        end if; 
    end process;

    icmp_ln146_fu_148_p2 <= "1" when (ap_sig_allocacmp_i_1 = ap_const_lv10_300) else "0";
    line_buf_in_address0 <= line_buf_in_address0_local;

    line_buf_in_address0_local_assign_proc : process(ap_CS_fsm_pp0_stage2, ap_enable_reg_pp0_iter0_reg, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1, zext_ln155_fu_251_p1, zext_ln156_fu_280_p1, ap_block_pp0_stage2)
    begin
        if ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1)) then
            if (((ap_const_boolean_0 = ap_block_pp0_stage2) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
                line_buf_in_address0_local <= zext_ln156_fu_280_p1(9 - 1 downto 0);
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                line_buf_in_address0_local <= zext_ln155_fu_251_p1(9 - 1 downto 0);
            else 
                line_buf_in_address0_local <= "XXXXXXXXX";
            end if;
        else 
            line_buf_in_address0_local <= "XXXXXXXXX";
        end if; 
    end process;

    line_buf_in_address1 <= zext_ln154_fu_226_p1(9 - 1 downto 0);
    line_buf_in_ce0 <= line_buf_in_ce0_local;

    line_buf_in_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage2, ap_enable_reg_pp0_iter0_reg, ap_block_pp0_stage2_11001, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001)
    begin
        if ((((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2)) or ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)))) then 
            line_buf_in_ce0_local <= ap_const_logic_1;
        else 
            line_buf_in_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    line_buf_in_ce1 <= line_buf_in_ce1_local;

    line_buf_in_ce1_local_assign_proc : process(ap_enable_reg_pp0_iter0_reg, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001)
    begin
        if (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            line_buf_in_ce1_local <= ap_const_logic_1;
        else 
            line_buf_in_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    line_buf_out_address0 <= line_buf_out_address0_local;

    line_buf_out_address0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_CS_fsm_pp0_stage2, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1, ap_block_pp0_stage2, zext_ln154_8_fu_406_p1, zext_ln155_5_fu_481_p1, zext_ln156_5_fu_535_p1, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            line_buf_out_address0_local <= zext_ln156_5_fu_535_p1(9 - 1 downto 0);
        elsif (((ap_const_boolean_0 = ap_block_pp0_stage2) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
            line_buf_out_address0_local <= zext_ln155_5_fu_481_p1(9 - 1 downto 0);
        elsif (((ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            line_buf_out_address0_local <= zext_ln154_8_fu_406_p1(9 - 1 downto 0);
        else 
            line_buf_out_address0_local <= "XXXXXXXXX";
        end if; 
    end process;

    line_buf_out_ce0 <= line_buf_out_ce0_local;

    line_buf_out_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_CS_fsm_pp0_stage2, ap_block_pp0_stage2_11001, ap_block_pp0_stage0_11001, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2)) or ((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)))) then 
            line_buf_out_ce0_local <= ap_const_logic_1;
        else 
            line_buf_out_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    line_buf_out_d0 <= line_buf_out_d0_local;

    line_buf_out_d0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_CS_fsm_pp0_stage2, ap_CS_fsm_pp0_stage1, shl_ln156_1_reg_659, ap_block_pp0_stage1, ap_block_pp0_stage2, ap_block_pp0_stage0, shl_ln154_1_fu_399_p2, shl_ln155_1_fu_474_p2)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            line_buf_out_d0_local <= shl_ln156_1_reg_659;
        elsif (((ap_const_boolean_0 = ap_block_pp0_stage2) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
            line_buf_out_d0_local <= shl_ln155_1_fu_474_p2;
        elsif (((ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            line_buf_out_d0_local <= shl_ln154_1_fu_399_p2;
        else 
            line_buf_out_d0_local <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;

    line_buf_out_we0 <= line_buf_out_we0_local;

    line_buf_out_we0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_CS_fsm_pp0_stage2, ap_block_pp0_stage2_11001, ap_block_pp0_stage0_11001, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001, shl_ln154_reg_619, shl_ln155_reg_639, shl_ln156_reg_654)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            line_buf_out_we0_local <= shl_ln156_reg_654;
        elsif (((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
            line_buf_out_we0_local <= shl_ln155_reg_639;
        elsif (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            line_buf_out_we0_local <= shl_ln154_reg_619;
        else 
            line_buf_out_we0_local <= ap_const_lv16_0;
        end if; 
    end process;

    lshr_ln154_fu_308_p2 <= std_logic_vector(shift_right(unsigned(reg_135),to_integer(unsigned('0' & zext_ln154_5_fu_304_p1(31-1 downto 0)))));
    lshr_ln155_fu_376_p2 <= std_logic_vector(shift_right(unsigned(line_buf_in_load_1_reg_588),to_integer(unsigned('0' & zext_ln155_1_fu_372_p1(31-1 downto 0)))));
    lshr_ln156_fu_450_p2 <= std_logic_vector(shift_right(unsigned(reg_135),to_integer(unsigned('0' & zext_ln156_1_fu_446_p1(31-1 downto 0)))));
    lshr_ln3_fu_216_p4 <= add_ln154_fu_210_p2(12 downto 4);
    lshr_ln4_fu_241_p4 <= add_ln155_fu_235_p2(12 downto 4);
    lshr_ln5_fu_270_p4 <= add_ln156_fu_265_p2(12 downto 4);
    p_shl1_fu_154_p3 <= (ap_sig_allocacmp_i_1 & ap_const_lv3_0);
    p_shl2_fu_193_p3 <= (tmp_7_reg_557 & ap_const_lv2_0);
    p_shl_fu_318_p3 <= (i_1_reg_546 & ap_const_lv2_0);
    shl_ln154_1_fu_399_p2 <= std_logic_vector(shift_left(unsigned(zext_ln154_2_fu_385_p1),to_integer(unsigned('0' & zext_ln154_7_fu_395_p1(31-1 downto 0)))));
    shl_ln154_2_fu_388_p3 <= (trunc_ln154_2_reg_614 & ap_const_lv3_0);
    shl_ln154_fu_349_p2 <= std_logic_vector(shift_left(unsigned(ap_const_lv16_1),to_integer(unsigned('0' & zext_ln154_3_fu_345_p1(16-1 downto 0)))));
    shl_ln155_1_fu_474_p2 <= std_logic_vector(shift_left(unsigned(zext_ln155_2_fu_460_p1),to_integer(unsigned('0' & zext_ln155_4_fu_470_p1(31-1 downto 0)))));
    shl_ln155_2_fu_463_p3 <= (trunc_ln155_2_reg_634 & ap_const_lv3_0);
    shl_ln155_fu_423_p2 <= std_logic_vector(shift_left(unsigned(ap_const_lv16_1),to_integer(unsigned('0' & zext_ln155_3_fu_419_p1(16-1 downto 0)))));
    shl_ln156_1_fu_519_p2 <= std_logic_vector(shift_left(unsigned(zext_ln156_2_fu_490_p1),to_integer(unsigned('0' & zext_ln156_4_fu_515_p1(31-1 downto 0)))));
    shl_ln156_2_fu_507_p3 <= (trunc_ln156_2_fu_493_p1 & ap_const_lv3_0);
    shl_ln156_fu_501_p2 <= std_logic_vector(shift_left(unsigned(ap_const_lv16_1),to_integer(unsigned('0' & zext_ln156_3_fu_497_p1(16-1 downto 0)))));
    shl_ln4_fu_297_p3 <= (trunc_ln154_reg_573 & ap_const_lv3_0);
    shl_ln5_fu_365_p3 <= (trunc_ln155_reg_583 & ap_const_lv3_0);
    shl_ln6_fu_439_p3 <= (trunc_ln156_reg_598 & ap_const_lv3_0);
    sub_ln154_1_fu_325_p2 <= std_logic_vector(unsigned(p_shl_fu_318_p3) - unsigned(zext_ln146_fu_294_p1));
    sub_ln154_fu_200_p2 <= std_logic_vector(unsigned(p_shl2_fu_193_p3) - unsigned(zext_ln154_4_fu_190_p1));
    tmp_fu_162_p3 <= (ap_sig_allocacmp_i_1 & ap_const_lv1_0);
    trunc_ln154_1_fu_314_p1 <= lshr_ln154_fu_308_p2(8 - 1 downto 0);
    trunc_ln154_2_fu_341_p1 <= add_ln154_1_fu_335_p2(4 - 1 downto 0);
    trunc_ln154_fu_231_p1 <= add_ln154_fu_210_p2(4 - 1 downto 0);
    trunc_ln155_1_fu_381_p1 <= lshr_ln155_fu_376_p2(8 - 1 downto 0);
    trunc_ln155_2_fu_415_p1 <= add_ln155_1_fu_410_p2(4 - 1 downto 0);
    trunc_ln155_fu_256_p1 <= add_ln155_fu_235_p2(4 - 1 downto 0);
    trunc_ln156_1_fu_456_p1 <= lshr_ln156_fu_450_p2(8 - 1 downto 0);
    trunc_ln156_2_fu_493_p1 <= add_ln156_1_fu_485_p2(4 - 1 downto 0);
    trunc_ln156_fu_285_p1 <= add_ln156_fu_265_p2(4 - 1 downto 0);
    zext_ln146_fu_294_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(i_1_reg_546),12));
    zext_ln148_fu_170_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_fu_162_p3),13));
    zext_ln154_1_fu_206_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sub_ln154_fu_200_p2),13));
    zext_ln154_2_fu_385_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(trunc_ln154_1_reg_603),128));
    zext_ln154_3_fu_345_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(trunc_ln154_2_fu_341_p1),16));
    zext_ln154_4_fu_190_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_7_reg_557),12));
    zext_ln154_5_fu_304_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln4_fu_297_p3),128));
    zext_ln154_6_fu_331_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sub_ln154_1_fu_325_p2),13));
    zext_ln154_7_fu_395_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln154_2_fu_388_p3),128));
    zext_ln154_8_fu_406_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(lshr_ln154_2_reg_624),64));
    zext_ln154_fu_226_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(lshr_ln3_fu_216_p4),64));
    zext_ln155_1_fu_372_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln5_fu_365_p3),128));
    zext_ln155_2_fu_460_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(trunc_ln155_1_reg_629),128));
    zext_ln155_3_fu_419_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(trunc_ln155_2_fu_415_p1),16));
    zext_ln155_4_fu_470_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln155_2_fu_463_p3),128));
    zext_ln155_5_fu_481_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(lshr_ln155_2_reg_644),64));
    zext_ln155_fu_251_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(lshr_ln4_fu_241_p4),64));
    zext_ln156_1_fu_446_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln6_fu_439_p3),128));
    zext_ln156_2_fu_490_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(trunc_ln156_1_reg_649),128));
    zext_ln156_3_fu_497_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(trunc_ln156_2_fu_493_p1),16));
    zext_ln156_4_fu_515_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln156_2_fu_507_p3),128));
    zext_ln156_5_fu_535_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(lshr_ln156_2_reg_664),64));
    zext_ln156_fu_280_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(lshr_ln5_fu_270_p4),64));
end behav;
