domain_path: C:\quad_frame_remapper\vitis_embrdded_workspace\platform\zynq_fsbl\zynq_fsbl_bsp
app_src_dir: C:\Xilinx\2025.1\2025.1\Vitis\data\embeddedsw\lib\sw_apps\zynq_fsbl
template: zynq_fsbl
lang: c
