# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/project9/project1.srcs/sources_1/bd/project1/ip/project1_axi_interconnect_0_imp_auto_cc_0/project1_axi_interconnect_0_imp_auto_cc_0.xci
# IP: The module: 'project1_axi_interconnect_0_imp_auto_cc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/project9/project1.gen/sources_1/bd/project1/ip/project1_axi_interconnect_0_imp_auto_cc_0/project1_axi_interconnect_0_imp_auto_cc_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'project1_axi_interconnect_0_imp_auto_cc_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/project9/project1.gen/sources_1/bd/project1/ip/project1_axi_interconnect_0_imp_auto_cc_0/project1_axi_interconnect_0_imp_auto_cc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'project1_axi_interconnect_0_imp_auto_cc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/project9/project1.srcs/sources_1/bd/project1/ip/project1_axi_interconnect_0_imp_auto_cc_0/project1_axi_interconnect_0_imp_auto_cc_0.xci
# IP: The module: 'project1_axi_interconnect_0_imp_auto_cc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/project9/project1.gen/sources_1/bd/project1/ip/project1_axi_interconnect_0_imp_auto_cc_0/project1_axi_interconnect_0_imp_auto_cc_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'project1_axi_interconnect_0_imp_auto_cc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/project9/project1.gen/sources_1/bd/project1/ip/project1_axi_interconnect_0_imp_auto_cc_0/project1_axi_interconnect_0_imp_auto_cc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'project1_axi_interconnect_0_imp_auto_cc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
