// ==============================================================
// Generated by Vitis HLS v2025.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module quad_frame_remapper_quad_frame_remapper_Pipeline_VITIS_LOOP_132_2 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        line_buf_in_address0,
        line_buf_in_ce0,
        line_buf_in_q0,
        line_buf_in_address1,
        line_buf_in_ce1,
        line_buf_in_q1,
        line_buf_out_address0,
        line_buf_out_ce0,
        line_buf_out_we0,
        line_buf_out_d0
);

parameter    ap_ST_fsm_pp0_stage0 = 3'd1;
parameter    ap_ST_fsm_pp0_stage1 = 3'd2;
parameter    ap_ST_fsm_pp0_stage2 = 3'd4;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [8:0] line_buf_in_address0;
output   line_buf_in_ce0;
input  [127:0] line_buf_in_q0;
output  [8:0] line_buf_in_address1;
output   line_buf_in_ce1;
input  [127:0] line_buf_in_q1;
output  [8:0] line_buf_out_address0;
output   line_buf_out_ce0;
output  [15:0] line_buf_out_we0;
output  [127:0] line_buf_out_d0;

reg ap_idle;

(* fsm_encoding = "none" *) reg   [2:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_idle_pp0;
wire    ap_CS_fsm_pp0_stage2;
wire    ap_block_pp0_stage2_subdone;
reg    ap_enable_reg_pp0_iter0_reg;
reg   [0:0] icmp_ln132_reg_539;
reg    ap_condition_exit_pp0_iter0_stage2;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg   [127:0] reg_135;
wire    ap_block_pp0_stage2_11001;
wire    ap_block_pp0_stage0_11001;
reg   [9:0] i_2_reg_532;
wire   [0:0] icmp_ln132_fu_148_p2;
reg   [9:0] tmp_reg_543;
wire   [11:0] sub_ln140_fu_200_p2;
reg   [11:0] sub_ln140_reg_549;
wire    ap_CS_fsm_pp0_stage1;
wire    ap_block_pp0_stage1_11001;
wire   [3:0] trunc_ln140_fu_221_p1;
reg   [3:0] trunc_ln140_reg_559;
wire   [3:0] trunc_ln141_fu_246_p1;
reg   [3:0] trunc_ln141_reg_569;
reg   [127:0] line_buf_in_load_1_reg_574;
wire   [3:0] trunc_ln142_fu_275_p1;
reg   [3:0] trunc_ln142_reg_584;
wire   [7:0] trunc_ln140_1_fu_304_p1;
reg   [7:0] trunc_ln140_1_reg_589;
wire   [11:0] sub_ln140_1_fu_315_p2;
reg   [11:0] sub_ln140_1_reg_594;
wire   [3:0] trunc_ln140_2_fu_327_p1;
reg   [3:0] trunc_ln140_2_reg_600;
wire   [15:0] shl_ln140_fu_335_p2;
reg   [15:0] shl_ln140_reg_605;
reg   [7:0] lshr_ln140_2_reg_610;
wire   [7:0] trunc_ln141_1_fu_367_p1;
reg   [7:0] trunc_ln141_1_reg_615;
wire   [3:0] trunc_ln141_2_fu_401_p1;
reg   [3:0] trunc_ln141_2_reg_620;
wire   [15:0] shl_ln141_fu_409_p2;
reg   [15:0] shl_ln141_reg_625;
reg   [7:0] lshr_ln141_2_reg_630;
wire   [7:0] trunc_ln142_1_fu_442_p1;
reg   [7:0] trunc_ln142_1_reg_635;
wire   [15:0] shl_ln142_fu_487_p2;
reg   [15:0] shl_ln142_reg_640;
wire   [127:0] shl_ln142_1_fu_505_p2;
reg   [127:0] shl_ln142_1_reg_645;
reg   [7:0] lshr_ln142_2_reg_650;
wire    ap_block_pp0_stage0_subdone;
wire   [63:0] zext_ln140_fu_216_p1;
wire    ap_block_pp0_stage1;
wire   [63:0] zext_ln141_fu_241_p1;
wire   [63:0] zext_ln142_fu_270_p1;
wire    ap_block_pp0_stage2;
wire   [63:0] zext_ln140_5_fu_392_p1;
wire   [63:0] zext_ln141_5_fu_467_p1;
wire   [63:0] zext_ln142_5_fu_521_p1;
wire    ap_block_pp0_stage0;
reg   [9:0] i_fu_72;
wire   [9:0] add_ln132_fu_250_p2;
wire    ap_loop_init;
reg   [9:0] ap_sig_allocacmp_i_2;
reg    line_buf_in_ce1_local;
reg    line_buf_in_ce0_local;
reg   [8:0] line_buf_in_address0_local;
reg    line_buf_out_ce0_local;
reg   [15:0] line_buf_out_we0_local;
reg   [8:0] line_buf_out_address0_local;
reg   [127:0] line_buf_out_d0_local;
wire   [127:0] shl_ln140_1_fu_385_p2;
wire   [127:0] shl_ln141_1_fu_460_p2;
wire   [10:0] tmp_1_fu_162_p3;
wire   [12:0] p_shl3_fu_154_p3;
wire   [12:0] zext_ln134_fu_170_p1;
wire   [12:0] add_ln134_fu_174_p2;
wire   [11:0] p_shl4_fu_193_p3;
wire   [11:0] zext_ln134_1_fu_190_p1;
wire   [7:0] lshr_ln_fu_206_p4;
wire   [11:0] add_ln141_fu_225_p2;
wire   [7:0] lshr_ln1_fu_231_p4;
wire   [11:0] add_ln142_fu_255_p2;
wire   [7:0] lshr_ln2_fu_260_p4;
wire   [6:0] shl_ln1_fu_287_p3;
wire   [127:0] zext_ln140_1_fu_294_p1;
wire   [127:0] lshr_ln140_fu_298_p2;
wire   [11:0] p_shl_fu_308_p3;
wire   [11:0] zext_ln132_fu_284_p1;
wire   [11:0] add_ln140_fu_321_p2;
wire   [15:0] zext_ln140_3_fu_331_p1;
wire   [6:0] shl_ln2_fu_351_p3;
wire   [127:0] zext_ln141_1_fu_358_p1;
wire   [127:0] lshr_ln141_fu_362_p2;
wire   [6:0] shl_ln140_2_fu_374_p3;
wire   [127:0] zext_ln140_2_fu_371_p1;
wire   [127:0] zext_ln140_4_fu_381_p1;
wire   [11:0] add_ln141_1_fu_396_p2;
wire   [15:0] zext_ln141_3_fu_405_p1;
wire   [6:0] shl_ln3_fu_425_p3;
wire   [127:0] zext_ln142_1_fu_432_p1;
wire   [127:0] lshr_ln142_fu_436_p2;
wire   [6:0] shl_ln141_2_fu_449_p3;
wire   [127:0] zext_ln141_2_fu_446_p1;
wire   [127:0] zext_ln141_4_fu_456_p1;
wire   [11:0] add_ln142_1_fu_471_p2;
wire   [3:0] trunc_ln142_2_fu_479_p1;
wire   [15:0] zext_ln142_3_fu_483_p1;
wire   [6:0] shl_ln142_2_fu_493_p3;
wire   [127:0] zext_ln142_2_fu_476_p1;
wire   [127:0] zext_ln142_4_fu_501_p1;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_condition_exit_pp0_iter1_stage0;
reg    ap_idle_pp0_0to0;
reg   [2:0] ap_NS_fsm;
reg    ap_idle_pp0_1to2;
wire    ap_block_pp0_stage1_subdone;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 3'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter0_reg = 1'b0;
#0 i_fu_72 = 10'd0;
#0 ap_done_reg = 1'b0;
end

quad_frame_remapper_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage2),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            ap_enable_reg_pp0_iter0_reg <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage2)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage2_subdone) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter2 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage2_subdone) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to0 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter1_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        i_fu_72 <= 10'd0;
    end else if (((icmp_ln132_reg_539 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        i_fu_72 <= add_ln132_fu_250_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        reg_135 <= line_buf_in_q0;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        reg_135 <= line_buf_in_q1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        i_2_reg_532 <= ap_sig_allocacmp_i_2;
        icmp_ln132_reg_539 <= icmp_ln132_fu_148_p2;
        lshr_ln140_2_reg_610 <= {{add_ln140_fu_321_p2[11:4]}};
        shl_ln140_reg_605 <= shl_ln140_fu_335_p2;
        sub_ln140_1_reg_594 <= sub_ln140_1_fu_315_p2;
        tmp_reg_543 <= {{add_ln134_fu_174_p2[12:3]}};
        trunc_ln140_1_reg_589 <= trunc_ln140_1_fu_304_p1;
        trunc_ln140_2_reg_600 <= trunc_ln140_2_fu_327_p1;
        trunc_ln141_1_reg_615 <= trunc_ln141_1_fu_367_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        line_buf_in_load_1_reg_574 <= line_buf_in_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        lshr_ln141_2_reg_630 <= {{add_ln141_1_fu_396_p2[11:4]}};
        shl_ln141_reg_625 <= shl_ln141_fu_409_p2;
        sub_ln140_reg_549 <= sub_ln140_fu_200_p2;
        trunc_ln140_reg_559 <= trunc_ln140_fu_221_p1;
        trunc_ln141_2_reg_620 <= trunc_ln141_2_fu_401_p1;
        trunc_ln141_reg_569 <= trunc_ln141_fu_246_p1;
        trunc_ln142_1_reg_635 <= trunc_ln142_1_fu_442_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        lshr_ln142_2_reg_650 <= {{add_ln142_1_fu_471_p2[11:4]}};
        shl_ln142_1_reg_645 <= shl_ln142_1_fu_505_p2;
        shl_ln142_reg_640 <= shl_ln142_fu_487_p2;
        trunc_ln142_reg_584 <= trunc_ln142_fu_275_p1;
    end
end

always @ (*) begin
    if (((icmp_ln132_reg_539 == 1'd1) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2_subdone) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        ap_condition_exit_pp0_iter0_stage2 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage2 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln132_reg_539 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        ap_enable_reg_pp0_iter0 = ap_start_int;
    end else begin
        ap_enable_reg_pp0_iter0 = ap_enable_reg_pp0_iter0_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b0)) begin
        ap_idle_pp0_0to0 = 1'b1;
    end else begin
        ap_idle_pp0_0to0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0))) begin
        ap_idle_pp0_1to2 = 1'b1;
    end else begin
        ap_idle_pp0_1to2 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2_subdone) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_i_2 = 10'd0;
    end else begin
        ap_sig_allocacmp_i_2 = i_fu_72;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0_reg == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            line_buf_in_address0_local = zext_ln142_fu_270_p1;
        end else if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            line_buf_in_address0_local = zext_ln141_fu_241_p1;
        end else begin
            line_buf_in_address0_local = 'bx;
        end
    end else begin
        line_buf_in_address0_local = 'bx;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
        line_buf_in_ce0_local = 1'b1;
    end else begin
        line_buf_in_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        line_buf_in_ce1_local = 1'b1;
    end else begin
        line_buf_in_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        line_buf_out_address0_local = zext_ln142_5_fu_521_p1;
    end else if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        line_buf_out_address0_local = zext_ln141_5_fu_467_p1;
    end else if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        line_buf_out_address0_local = zext_ln140_5_fu_392_p1;
    end else begin
        line_buf_out_address0_local = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
        line_buf_out_ce0_local = 1'b1;
    end else begin
        line_buf_out_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        line_buf_out_d0_local = shl_ln142_1_reg_645;
    end else if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        line_buf_out_d0_local = shl_ln141_1_fu_460_p2;
    end else if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        line_buf_out_d0_local = shl_ln140_1_fu_385_p2;
    end else begin
        line_buf_out_d0_local = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        line_buf_out_we0_local = shl_ln142_reg_640;
    end else if (((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        line_buf_out_we0_local = shl_ln141_reg_625;
    end else if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        line_buf_out_we0_local = shl_ln140_reg_605;
    end else begin
        line_buf_out_we0_local = 16'd0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            if (((ap_idle_pp0_0to0 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter1_stage0))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((~((ap_start_int == 1'b0) & (ap_idle_pp0_1to2 == 1'b1)) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        ap_ST_fsm_pp0_stage2 : begin
            if ((1'b0 == ap_block_pp0_stage2_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln132_fu_250_p2 = (i_2_reg_532 + 10'd1);

assign add_ln134_fu_174_p2 = (p_shl3_fu_154_p3 + zext_ln134_fu_170_p1);

assign add_ln140_fu_321_p2 = (sub_ln140_1_fu_315_p2 + 12'd288);

assign add_ln141_1_fu_396_p2 = (sub_ln140_1_reg_594 + 12'd289);

assign add_ln141_fu_225_p2 = (sub_ln140_fu_200_p2 + 12'd1);

assign add_ln142_1_fu_471_p2 = (sub_ln140_1_reg_594 + 12'd290);

assign add_ln142_fu_255_p2 = (sub_ln140_reg_549 + 12'd2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_pp0_stage2 = ap_CS_fsm[32'd2];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage2;

assign ap_ready = ap_ready_sig;

assign icmp_ln132_fu_148_p2 = ((ap_sig_allocacmp_i_2 == 10'd768) ? 1'b1 : 1'b0);

assign line_buf_in_address0 = line_buf_in_address0_local;

assign line_buf_in_address1 = zext_ln140_fu_216_p1;

assign line_buf_in_ce0 = line_buf_in_ce0_local;

assign line_buf_in_ce1 = line_buf_in_ce1_local;

assign line_buf_out_address0 = line_buf_out_address0_local;

assign line_buf_out_ce0 = line_buf_out_ce0_local;

assign line_buf_out_d0 = line_buf_out_d0_local;

assign line_buf_out_we0 = line_buf_out_we0_local;

assign lshr_ln140_fu_298_p2 = reg_135 >> zext_ln140_1_fu_294_p1;

assign lshr_ln141_fu_362_p2 = line_buf_in_load_1_reg_574 >> zext_ln141_1_fu_358_p1;

assign lshr_ln142_fu_436_p2 = reg_135 >> zext_ln142_1_fu_432_p1;

assign lshr_ln1_fu_231_p4 = {{add_ln141_fu_225_p2[11:4]}};

assign lshr_ln2_fu_260_p4 = {{add_ln142_fu_255_p2[11:4]}};

assign lshr_ln_fu_206_p4 = {{sub_ln140_fu_200_p2[11:4]}};

assign p_shl3_fu_154_p3 = {{ap_sig_allocacmp_i_2}, {3'd0}};

assign p_shl4_fu_193_p3 = {{tmp_reg_543}, {2'd0}};

assign p_shl_fu_308_p3 = {{i_2_reg_532}, {2'd0}};

assign shl_ln140_1_fu_385_p2 = zext_ln140_2_fu_371_p1 << zext_ln140_4_fu_381_p1;

assign shl_ln140_2_fu_374_p3 = {{trunc_ln140_2_reg_600}, {3'd0}};

assign shl_ln140_fu_335_p2 = 16'd1 << zext_ln140_3_fu_331_p1;

assign shl_ln141_1_fu_460_p2 = zext_ln141_2_fu_446_p1 << zext_ln141_4_fu_456_p1;

assign shl_ln141_2_fu_449_p3 = {{trunc_ln141_2_reg_620}, {3'd0}};

assign shl_ln141_fu_409_p2 = 16'd1 << zext_ln141_3_fu_405_p1;

assign shl_ln142_1_fu_505_p2 = zext_ln142_2_fu_476_p1 << zext_ln142_4_fu_501_p1;

assign shl_ln142_2_fu_493_p3 = {{trunc_ln142_2_fu_479_p1}, {3'd0}};

assign shl_ln142_fu_487_p2 = 16'd1 << zext_ln142_3_fu_483_p1;

assign shl_ln1_fu_287_p3 = {{trunc_ln140_reg_559}, {3'd0}};

assign shl_ln2_fu_351_p3 = {{trunc_ln141_reg_569}, {3'd0}};

assign shl_ln3_fu_425_p3 = {{trunc_ln142_reg_584}, {3'd0}};

assign sub_ln140_1_fu_315_p2 = (p_shl_fu_308_p3 - zext_ln132_fu_284_p1);

assign sub_ln140_fu_200_p2 = (p_shl4_fu_193_p3 - zext_ln134_1_fu_190_p1);

assign tmp_1_fu_162_p3 = {{ap_sig_allocacmp_i_2}, {1'd0}};

assign trunc_ln140_1_fu_304_p1 = lshr_ln140_fu_298_p2[7:0];

assign trunc_ln140_2_fu_327_p1 = add_ln140_fu_321_p2[3:0];

assign trunc_ln140_fu_221_p1 = sub_ln140_fu_200_p2[3:0];

assign trunc_ln141_1_fu_367_p1 = lshr_ln141_fu_362_p2[7:0];

assign trunc_ln141_2_fu_401_p1 = add_ln141_1_fu_396_p2[3:0];

assign trunc_ln141_fu_246_p1 = add_ln141_fu_225_p2[3:0];

assign trunc_ln142_1_fu_442_p1 = lshr_ln142_fu_436_p2[7:0];

assign trunc_ln142_2_fu_479_p1 = add_ln142_1_fu_471_p2[3:0];

assign trunc_ln142_fu_275_p1 = add_ln142_fu_255_p2[3:0];

assign zext_ln132_fu_284_p1 = i_2_reg_532;

assign zext_ln134_1_fu_190_p1 = tmp_reg_543;

assign zext_ln134_fu_170_p1 = tmp_1_fu_162_p3;

assign zext_ln140_1_fu_294_p1 = shl_ln1_fu_287_p3;

assign zext_ln140_2_fu_371_p1 = trunc_ln140_1_reg_589;

assign zext_ln140_3_fu_331_p1 = trunc_ln140_2_fu_327_p1;

assign zext_ln140_4_fu_381_p1 = shl_ln140_2_fu_374_p3;

assign zext_ln140_5_fu_392_p1 = lshr_ln140_2_reg_610;

assign zext_ln140_fu_216_p1 = lshr_ln_fu_206_p4;

assign zext_ln141_1_fu_358_p1 = shl_ln2_fu_351_p3;

assign zext_ln141_2_fu_446_p1 = trunc_ln141_1_reg_615;

assign zext_ln141_3_fu_405_p1 = trunc_ln141_2_fu_401_p1;

assign zext_ln141_4_fu_456_p1 = shl_ln141_2_fu_449_p3;

assign zext_ln141_5_fu_467_p1 = lshr_ln141_2_reg_630;

assign zext_ln141_fu_241_p1 = lshr_ln1_fu_231_p4;

assign zext_ln142_1_fu_432_p1 = shl_ln3_fu_425_p3;

assign zext_ln142_2_fu_476_p1 = trunc_ln142_1_reg_635;

assign zext_ln142_3_fu_483_p1 = trunc_ln142_2_fu_479_p1;

assign zext_ln142_4_fu_501_p1 = shl_ln142_2_fu_493_p3;

assign zext_ln142_5_fu_521_p1 = lshr_ln142_2_reg_650;

assign zext_ln142_fu_270_p1 = lshr_ln2_fu_260_p4;

endmodule //quad_frame_remapper_quad_frame_remapper_Pipeline_VITIS_LOOP_132_2
