-- ==============================================================
-- Generated by Vitis HLS v2025.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity quad_frame_remapper_quad_frame_remapper_Pipeline_VITIS_LOOP_132_2 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    line_buf_in_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
    line_buf_in_ce0 : OUT STD_LOGIC;
    line_buf_in_q0 : IN STD_LOGIC_VECTOR (127 downto 0);
    line_buf_in_address1 : OUT STD_LOGIC_VECTOR (8 downto 0);
    line_buf_in_ce1 : OUT STD_LOGIC;
    line_buf_in_q1 : IN STD_LOGIC_VECTOR (127 downto 0);
    line_buf_out_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
    line_buf_out_ce0 : OUT STD_LOGIC;
    line_buf_out_we0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    line_buf_out_d0 : OUT STD_LOGIC_VECTOR (127 downto 0) );
end;


architecture behav of quad_frame_remapper_quad_frame_remapper_Pipeline_VITIS_LOOP_132_2 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_ST_fsm_pp0_stage1 : STD_LOGIC_VECTOR (2 downto 0) := "010";
    constant ap_ST_fsm_pp0_stage2 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv10_0 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_lv10_300 : STD_LOGIC_VECTOR (9 downto 0) := "1100000000";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001100";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001011";
    constant ap_const_lv12_1 : STD_LOGIC_VECTOR (11 downto 0) := "000000000001";
    constant ap_const_lv10_1 : STD_LOGIC_VECTOR (9 downto 0) := "0000000001";
    constant ap_const_lv12_2 : STD_LOGIC_VECTOR (11 downto 0) := "000000000010";
    constant ap_const_lv12_120 : STD_LOGIC_VECTOR (11 downto 0) := "000100100000";
    constant ap_const_lv16_1 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000001";
    constant ap_const_lv12_121 : STD_LOGIC_VECTOR (11 downto 0) := "000100100001";
    constant ap_const_lv12_122 : STD_LOGIC_VECTOR (11 downto 0) := "000100100010";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (2 downto 0) := "001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_CS_fsm_pp0_stage2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage2 : signal is "none";
    signal ap_block_pp0_stage2_subdone : BOOLEAN;
    signal ap_enable_reg_pp0_iter0_reg : STD_LOGIC := '0';
    signal icmp_ln132_reg_539 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage2 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal reg_135 : STD_LOGIC_VECTOR (127 downto 0);
    signal ap_block_pp0_stage2_11001 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal i_2_reg_532 : STD_LOGIC_VECTOR (9 downto 0);
    signal icmp_ln132_fu_148_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_reg_543 : STD_LOGIC_VECTOR (9 downto 0);
    signal sub_ln140_fu_200_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal sub_ln140_reg_549 : STD_LOGIC_VECTOR (11 downto 0);
    signal ap_CS_fsm_pp0_stage1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage1 : signal is "none";
    signal ap_block_pp0_stage1_11001 : BOOLEAN;
    signal trunc_ln140_fu_221_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal trunc_ln140_reg_559 : STD_LOGIC_VECTOR (3 downto 0);
    signal trunc_ln141_fu_246_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal trunc_ln141_reg_569 : STD_LOGIC_VECTOR (3 downto 0);
    signal line_buf_in_load_1_reg_574 : STD_LOGIC_VECTOR (127 downto 0);
    signal trunc_ln142_fu_275_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal trunc_ln142_reg_584 : STD_LOGIC_VECTOR (3 downto 0);
    signal trunc_ln140_1_fu_304_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln140_1_reg_589 : STD_LOGIC_VECTOR (7 downto 0);
    signal sub_ln140_1_fu_315_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal sub_ln140_1_reg_594 : STD_LOGIC_VECTOR (11 downto 0);
    signal trunc_ln140_2_fu_327_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal trunc_ln140_2_reg_600 : STD_LOGIC_VECTOR (3 downto 0);
    signal shl_ln140_fu_335_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal shl_ln140_reg_605 : STD_LOGIC_VECTOR (15 downto 0);
    signal lshr_ln140_2_reg_610 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln141_1_fu_367_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln141_1_reg_615 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln141_2_fu_401_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal trunc_ln141_2_reg_620 : STD_LOGIC_VECTOR (3 downto 0);
    signal shl_ln141_fu_409_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal shl_ln141_reg_625 : STD_LOGIC_VECTOR (15 downto 0);
    signal lshr_ln141_2_reg_630 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln142_1_fu_442_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln142_1_reg_635 : STD_LOGIC_VECTOR (7 downto 0);
    signal shl_ln142_fu_487_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal shl_ln142_reg_640 : STD_LOGIC_VECTOR (15 downto 0);
    signal shl_ln142_1_fu_505_p2 : STD_LOGIC_VECTOR (127 downto 0);
    signal shl_ln142_1_reg_645 : STD_LOGIC_VECTOR (127 downto 0);
    signal lshr_ln142_2_reg_650 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal zext_ln140_fu_216_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage1 : BOOLEAN;
    signal zext_ln141_fu_241_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln142_fu_270_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage2 : BOOLEAN;
    signal zext_ln140_5_fu_392_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln141_5_fu_467_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln142_5_fu_521_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal i_fu_72 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    signal add_ln132_fu_250_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_i_2 : STD_LOGIC_VECTOR (9 downto 0);
    signal line_buf_in_ce1_local : STD_LOGIC;
    signal line_buf_in_ce0_local : STD_LOGIC;
    signal line_buf_in_address0_local : STD_LOGIC_VECTOR (8 downto 0);
    signal line_buf_out_ce0_local : STD_LOGIC;
    signal line_buf_out_we0_local : STD_LOGIC_VECTOR (15 downto 0);
    signal line_buf_out_address0_local : STD_LOGIC_VECTOR (8 downto 0);
    signal line_buf_out_d0_local : STD_LOGIC_VECTOR (127 downto 0);
    signal shl_ln140_1_fu_385_p2 : STD_LOGIC_VECTOR (127 downto 0);
    signal shl_ln141_1_fu_460_p2 : STD_LOGIC_VECTOR (127 downto 0);
    signal tmp_1_fu_162_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal p_shl3_fu_154_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal zext_ln134_fu_170_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal add_ln134_fu_174_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal p_shl4_fu_193_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal zext_ln134_1_fu_190_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal lshr_ln_fu_206_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln141_fu_225_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal lshr_ln1_fu_231_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln142_fu_255_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal lshr_ln2_fu_260_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal shl_ln1_fu_287_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal zext_ln140_1_fu_294_p1 : STD_LOGIC_VECTOR (127 downto 0);
    signal lshr_ln140_fu_298_p2 : STD_LOGIC_VECTOR (127 downto 0);
    signal p_shl_fu_308_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal zext_ln132_fu_284_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal add_ln140_fu_321_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal zext_ln140_3_fu_331_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal shl_ln2_fu_351_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal zext_ln141_1_fu_358_p1 : STD_LOGIC_VECTOR (127 downto 0);
    signal lshr_ln141_fu_362_p2 : STD_LOGIC_VECTOR (127 downto 0);
    signal shl_ln140_2_fu_374_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal zext_ln140_2_fu_371_p1 : STD_LOGIC_VECTOR (127 downto 0);
    signal zext_ln140_4_fu_381_p1 : STD_LOGIC_VECTOR (127 downto 0);
    signal add_ln141_1_fu_396_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal zext_ln141_3_fu_405_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal shl_ln3_fu_425_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal zext_ln142_1_fu_432_p1 : STD_LOGIC_VECTOR (127 downto 0);
    signal lshr_ln142_fu_436_p2 : STD_LOGIC_VECTOR (127 downto 0);
    signal shl_ln141_2_fu_449_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal zext_ln141_2_fu_446_p1 : STD_LOGIC_VECTOR (127 downto 0);
    signal zext_ln141_4_fu_456_p1 : STD_LOGIC_VECTOR (127 downto 0);
    signal add_ln142_1_fu_471_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal trunc_ln142_2_fu_479_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal zext_ln142_3_fu_483_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal shl_ln142_2_fu_493_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal zext_ln142_2_fu_476_p1 : STD_LOGIC_VECTOR (127 downto 0);
    signal zext_ln142_4_fu_501_p1 : STD_LOGIC_VECTOR (127 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_condition_exit_pp0_iter1_stage0 : STD_LOGIC;
    signal ap_idle_pp0_0to0 : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_idle_pp0_1to2 : STD_LOGIC;
    signal ap_block_pp0_stage1_subdone : BOOLEAN;
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component quad_frame_remapper_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    flow_control_loop_pipe_sequential_init_U : component quad_frame_remapper_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage2,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter0_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter0_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then 
                    ap_enable_reg_pp0_iter0_reg <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage2)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage2_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
                    ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage2_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_loop_exit_ready_pp0_iter1_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_idle_pp0_0to0 = ap_const_logic_1) and (ap_const_logic_1 = ap_condition_exit_pp0_iter1_stage0))) then 
                ap_loop_exit_ready_pp0_iter1_reg <= ap_const_logic_0;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
            end if; 
        end if;
    end process;

    i_fu_72_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
                i_fu_72 <= ap_const_lv10_0;
            elsif (((icmp_ln132_reg_539 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
                i_fu_72 <= add_ln132_fu_250_p2;
            end if; 
        end if;
    end process;

    reg_135_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                reg_135 <= line_buf_in_q0;
            elsif (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
                reg_135 <= line_buf_in_q1;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                i_2_reg_532 <= ap_sig_allocacmp_i_2;
                icmp_ln132_reg_539 <= icmp_ln132_fu_148_p2;
                lshr_ln140_2_reg_610 <= add_ln140_fu_321_p2(11 downto 4);
                shl_ln140_reg_605 <= shl_ln140_fu_335_p2;
                sub_ln140_1_reg_594 <= sub_ln140_1_fu_315_p2;
                tmp_reg_543 <= add_ln134_fu_174_p2(12 downto 3);
                trunc_ln140_1_reg_589 <= trunc_ln140_1_fu_304_p1;
                trunc_ln140_2_reg_600 <= trunc_ln140_2_fu_327_p1;
                trunc_ln141_1_reg_615 <= trunc_ln141_1_fu_367_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then
                line_buf_in_load_1_reg_574 <= line_buf_in_q0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then
                lshr_ln141_2_reg_630 <= add_ln141_1_fu_396_p2(11 downto 4);
                shl_ln141_reg_625 <= shl_ln141_fu_409_p2;
                sub_ln140_reg_549 <= sub_ln140_fu_200_p2;
                trunc_ln140_reg_559 <= trunc_ln140_fu_221_p1;
                trunc_ln141_2_reg_620 <= trunc_ln141_2_fu_401_p1;
                trunc_ln141_reg_569 <= trunc_ln141_fu_246_p1;
                trunc_ln142_1_reg_635 <= trunc_ln142_1_fu_442_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then
                lshr_ln142_2_reg_650 <= add_ln142_1_fu_471_p2(11 downto 4);
                shl_ln142_1_reg_645 <= shl_ln142_1_fu_505_p2;
                shl_ln142_reg_640 <= shl_ln142_fu_487_p2;
                trunc_ln142_reg_584 <= trunc_ln142_fu_275_p1;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_block_pp0_stage2_subdone, ap_block_pp0_stage0_subdone, ap_condition_exit_pp0_iter1_stage0, ap_idle_pp0_0to0, ap_idle_pp0_1to2, ap_block_pp0_stage1_subdone, ap_start_int)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                if (((ap_idle_pp0_0to0 = ap_const_logic_1) and (ap_const_logic_1 = ap_condition_exit_pp0_iter1_stage0))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                elsif ((not(((ap_start_int = ap_const_logic_0) and (ap_idle_pp0_1to2 = ap_const_logic_1))) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when ap_ST_fsm_pp0_stage1 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage1_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage2;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                end if;
            when ap_ST_fsm_pp0_stage2 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage2_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage2;
                end if;
            when others =>  
                ap_NS_fsm <= "XXX";
        end case;
    end process;
    add_ln132_fu_250_p2 <= std_logic_vector(unsigned(i_2_reg_532) + unsigned(ap_const_lv10_1));
    add_ln134_fu_174_p2 <= std_logic_vector(unsigned(p_shl3_fu_154_p3) + unsigned(zext_ln134_fu_170_p1));
    add_ln140_fu_321_p2 <= std_logic_vector(unsigned(sub_ln140_1_fu_315_p2) + unsigned(ap_const_lv12_120));
    add_ln141_1_fu_396_p2 <= std_logic_vector(unsigned(sub_ln140_1_reg_594) + unsigned(ap_const_lv12_121));
    add_ln141_fu_225_p2 <= std_logic_vector(unsigned(sub_ln140_fu_200_p2) + unsigned(ap_const_lv12_1));
    add_ln142_1_fu_471_p2 <= std_logic_vector(unsigned(sub_ln140_1_reg_594) + unsigned(ap_const_lv12_122));
    add_ln142_fu_255_p2 <= std_logic_vector(unsigned(sub_ln140_reg_549) + unsigned(ap_const_lv12_2));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
    ap_CS_fsm_pp0_stage1 <= ap_CS_fsm(1);
    ap_CS_fsm_pp0_stage2 <= ap_CS_fsm(2);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage2_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage2_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter0_stage2_assign_proc : process(ap_CS_fsm_pp0_stage2, ap_block_pp0_stage2_subdone, ap_enable_reg_pp0_iter0_reg, icmp_ln132_reg_539)
    begin
        if (((icmp_ln132_reg_539 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage2_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
            ap_condition_exit_pp0_iter0_stage2 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage2 <= ap_const_logic_0;
        end if; 
    end process;


    ap_condition_exit_pp0_iter1_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln132_reg_539, ap_block_pp0_stage0_subdone)
    begin
        if (((icmp_ln132_reg_539 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter1_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter1_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter1_reg)
    begin
        if (((ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);

    ap_enable_reg_pp0_iter0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0_reg, ap_start_int)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then 
            ap_enable_reg_pp0_iter0 <= ap_start_int;
        else 
            ap_enable_reg_pp0_iter0 <= ap_enable_reg_pp0_iter0_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_0to0_assign_proc : process(ap_enable_reg_pp0_iter0)
    begin
        if ((ap_enable_reg_pp0_iter0 = ap_const_logic_0)) then 
            ap_idle_pp0_0to0 <= ap_const_logic_1;
        else 
            ap_idle_pp0_0to0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_1to2_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0))) then 
            ap_idle_pp0_1to2 <= ap_const_logic_1;
        else 
            ap_idle_pp0_1to2 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage2;
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage2, ap_block_pp0_stage2_subdone, ap_enable_reg_pp0_iter0_reg)
    begin
        if (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage2_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_i_2_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, i_fu_72, ap_loop_init)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_i_2 <= ap_const_lv10_0;
        else 
            ap_sig_allocacmp_i_2 <= i_fu_72;
        end if; 
    end process;

    icmp_ln132_fu_148_p2 <= "1" when (ap_sig_allocacmp_i_2 = ap_const_lv10_300) else "0";
    line_buf_in_address0 <= line_buf_in_address0_local;

    line_buf_in_address0_local_assign_proc : process(ap_CS_fsm_pp0_stage2, ap_enable_reg_pp0_iter0_reg, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1, zext_ln141_fu_241_p1, zext_ln142_fu_270_p1, ap_block_pp0_stage2)
    begin
        if ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1)) then
            if (((ap_const_boolean_0 = ap_block_pp0_stage2) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
                line_buf_in_address0_local <= zext_ln142_fu_270_p1(9 - 1 downto 0);
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                line_buf_in_address0_local <= zext_ln141_fu_241_p1(9 - 1 downto 0);
            else 
                line_buf_in_address0_local <= "XXXXXXXXX";
            end if;
        else 
            line_buf_in_address0_local <= "XXXXXXXXX";
        end if; 
    end process;

    line_buf_in_address1 <= zext_ln140_fu_216_p1(9 - 1 downto 0);
    line_buf_in_ce0 <= line_buf_in_ce0_local;

    line_buf_in_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage2, ap_enable_reg_pp0_iter0_reg, ap_block_pp0_stage2_11001, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001)
    begin
        if ((((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2)) or ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)))) then 
            line_buf_in_ce0_local <= ap_const_logic_1;
        else 
            line_buf_in_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    line_buf_in_ce1 <= line_buf_in_ce1_local;

    line_buf_in_ce1_local_assign_proc : process(ap_enable_reg_pp0_iter0_reg, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001)
    begin
        if (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            line_buf_in_ce1_local <= ap_const_logic_1;
        else 
            line_buf_in_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    line_buf_out_address0 <= line_buf_out_address0_local;

    line_buf_out_address0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_CS_fsm_pp0_stage2, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1, ap_block_pp0_stage2, zext_ln140_5_fu_392_p1, zext_ln141_5_fu_467_p1, zext_ln142_5_fu_521_p1, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            line_buf_out_address0_local <= zext_ln142_5_fu_521_p1(9 - 1 downto 0);
        elsif (((ap_const_boolean_0 = ap_block_pp0_stage2) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
            line_buf_out_address0_local <= zext_ln141_5_fu_467_p1(9 - 1 downto 0);
        elsif (((ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            line_buf_out_address0_local <= zext_ln140_5_fu_392_p1(9 - 1 downto 0);
        else 
            line_buf_out_address0_local <= "XXXXXXXXX";
        end if; 
    end process;

    line_buf_out_ce0 <= line_buf_out_ce0_local;

    line_buf_out_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_CS_fsm_pp0_stage2, ap_block_pp0_stage2_11001, ap_block_pp0_stage0_11001, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2)) or ((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)))) then 
            line_buf_out_ce0_local <= ap_const_logic_1;
        else 
            line_buf_out_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    line_buf_out_d0 <= line_buf_out_d0_local;

    line_buf_out_d0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_CS_fsm_pp0_stage2, ap_CS_fsm_pp0_stage1, shl_ln142_1_reg_645, ap_block_pp0_stage1, ap_block_pp0_stage2, ap_block_pp0_stage0, shl_ln140_1_fu_385_p2, shl_ln141_1_fu_460_p2)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            line_buf_out_d0_local <= shl_ln142_1_reg_645;
        elsif (((ap_const_boolean_0 = ap_block_pp0_stage2) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
            line_buf_out_d0_local <= shl_ln141_1_fu_460_p2;
        elsif (((ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            line_buf_out_d0_local <= shl_ln140_1_fu_385_p2;
        else 
            line_buf_out_d0_local <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;

    line_buf_out_we0 <= line_buf_out_we0_local;

    line_buf_out_we0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_CS_fsm_pp0_stage2, ap_block_pp0_stage2_11001, ap_block_pp0_stage0_11001, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001, shl_ln140_reg_605, shl_ln141_reg_625, shl_ln142_reg_640)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            line_buf_out_we0_local <= shl_ln142_reg_640;
        elsif (((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
            line_buf_out_we0_local <= shl_ln141_reg_625;
        elsif (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            line_buf_out_we0_local <= shl_ln140_reg_605;
        else 
            line_buf_out_we0_local <= ap_const_lv16_0;
        end if; 
    end process;

    lshr_ln140_fu_298_p2 <= std_logic_vector(shift_right(unsigned(reg_135),to_integer(unsigned('0' & zext_ln140_1_fu_294_p1(31-1 downto 0)))));
    lshr_ln141_fu_362_p2 <= std_logic_vector(shift_right(unsigned(line_buf_in_load_1_reg_574),to_integer(unsigned('0' & zext_ln141_1_fu_358_p1(31-1 downto 0)))));
    lshr_ln142_fu_436_p2 <= std_logic_vector(shift_right(unsigned(reg_135),to_integer(unsigned('0' & zext_ln142_1_fu_432_p1(31-1 downto 0)))));
    lshr_ln1_fu_231_p4 <= add_ln141_fu_225_p2(11 downto 4);
    lshr_ln2_fu_260_p4 <= add_ln142_fu_255_p2(11 downto 4);
    lshr_ln_fu_206_p4 <= sub_ln140_fu_200_p2(11 downto 4);
    p_shl3_fu_154_p3 <= (ap_sig_allocacmp_i_2 & ap_const_lv3_0);
    p_shl4_fu_193_p3 <= (tmp_reg_543 & ap_const_lv2_0);
    p_shl_fu_308_p3 <= (i_2_reg_532 & ap_const_lv2_0);
    shl_ln140_1_fu_385_p2 <= std_logic_vector(shift_left(unsigned(zext_ln140_2_fu_371_p1),to_integer(unsigned('0' & zext_ln140_4_fu_381_p1(31-1 downto 0)))));
    shl_ln140_2_fu_374_p3 <= (trunc_ln140_2_reg_600 & ap_const_lv3_0);
    shl_ln140_fu_335_p2 <= std_logic_vector(shift_left(unsigned(ap_const_lv16_1),to_integer(unsigned('0' & zext_ln140_3_fu_331_p1(16-1 downto 0)))));
    shl_ln141_1_fu_460_p2 <= std_logic_vector(shift_left(unsigned(zext_ln141_2_fu_446_p1),to_integer(unsigned('0' & zext_ln141_4_fu_456_p1(31-1 downto 0)))));
    shl_ln141_2_fu_449_p3 <= (trunc_ln141_2_reg_620 & ap_const_lv3_0);
    shl_ln141_fu_409_p2 <= std_logic_vector(shift_left(unsigned(ap_const_lv16_1),to_integer(unsigned('0' & zext_ln141_3_fu_405_p1(16-1 downto 0)))));
    shl_ln142_1_fu_505_p2 <= std_logic_vector(shift_left(unsigned(zext_ln142_2_fu_476_p1),to_integer(unsigned('0' & zext_ln142_4_fu_501_p1(31-1 downto 0)))));
    shl_ln142_2_fu_493_p3 <= (trunc_ln142_2_fu_479_p1 & ap_const_lv3_0);
    shl_ln142_fu_487_p2 <= std_logic_vector(shift_left(unsigned(ap_const_lv16_1),to_integer(unsigned('0' & zext_ln142_3_fu_483_p1(16-1 downto 0)))));
    shl_ln1_fu_287_p3 <= (trunc_ln140_reg_559 & ap_const_lv3_0);
    shl_ln2_fu_351_p3 <= (trunc_ln141_reg_569 & ap_const_lv3_0);
    shl_ln3_fu_425_p3 <= (trunc_ln142_reg_584 & ap_const_lv3_0);
    sub_ln140_1_fu_315_p2 <= std_logic_vector(unsigned(p_shl_fu_308_p3) - unsigned(zext_ln132_fu_284_p1));
    sub_ln140_fu_200_p2 <= std_logic_vector(unsigned(p_shl4_fu_193_p3) - unsigned(zext_ln134_1_fu_190_p1));
    tmp_1_fu_162_p3 <= (ap_sig_allocacmp_i_2 & ap_const_lv1_0);
    trunc_ln140_1_fu_304_p1 <= lshr_ln140_fu_298_p2(8 - 1 downto 0);
    trunc_ln140_2_fu_327_p1 <= add_ln140_fu_321_p2(4 - 1 downto 0);
    trunc_ln140_fu_221_p1 <= sub_ln140_fu_200_p2(4 - 1 downto 0);
    trunc_ln141_1_fu_367_p1 <= lshr_ln141_fu_362_p2(8 - 1 downto 0);
    trunc_ln141_2_fu_401_p1 <= add_ln141_1_fu_396_p2(4 - 1 downto 0);
    trunc_ln141_fu_246_p1 <= add_ln141_fu_225_p2(4 - 1 downto 0);
    trunc_ln142_1_fu_442_p1 <= lshr_ln142_fu_436_p2(8 - 1 downto 0);
    trunc_ln142_2_fu_479_p1 <= add_ln142_1_fu_471_p2(4 - 1 downto 0);
    trunc_ln142_fu_275_p1 <= add_ln142_fu_255_p2(4 - 1 downto 0);
    zext_ln132_fu_284_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(i_2_reg_532),12));
    zext_ln134_1_fu_190_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_reg_543),12));
    zext_ln134_fu_170_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_1_fu_162_p3),13));
    zext_ln140_1_fu_294_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln1_fu_287_p3),128));
    zext_ln140_2_fu_371_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(trunc_ln140_1_reg_589),128));
    zext_ln140_3_fu_331_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(trunc_ln140_2_fu_327_p1),16));
    zext_ln140_4_fu_381_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln140_2_fu_374_p3),128));
    zext_ln140_5_fu_392_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(lshr_ln140_2_reg_610),64));
    zext_ln140_fu_216_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(lshr_ln_fu_206_p4),64));
    zext_ln141_1_fu_358_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln2_fu_351_p3),128));
    zext_ln141_2_fu_446_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(trunc_ln141_1_reg_615),128));
    zext_ln141_3_fu_405_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(trunc_ln141_2_fu_401_p1),16));
    zext_ln141_4_fu_456_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln141_2_fu_449_p3),128));
    zext_ln141_5_fu_467_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(lshr_ln141_2_reg_630),64));
    zext_ln141_fu_241_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(lshr_ln1_fu_231_p4),64));
    zext_ln142_1_fu_432_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln3_fu_425_p3),128));
    zext_ln142_2_fu_476_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(trunc_ln142_1_reg_635),128));
    zext_ln142_3_fu_483_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(trunc_ln142_2_fu_479_p1),16));
    zext_ln142_4_fu_501_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln142_2_fu_493_p3),128));
    zext_ln142_5_fu_521_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(lshr_ln142_2_reg_650),64));
    zext_ln142_fu_270_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(lshr_ln2_fu_260_p4),64));
end behav;
